apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sandbox-java.fullname" . }}
  labels:
    {{- include "sandbox-java.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sandbox-java.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sandbox-java.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/git-commit-id: "{{ .Values.gitcommitid | default "" }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sandbox-java.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "sandbox-java.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containers.command }}
          command: {{ .Values.containers.command }}
          {{- else }}
          command: ["java", "-jar", "-Dspring.profiles.active=$(APP_PROFILES)","/root/$(APP)-0.0.1-SNAPSHOT.jar"]
          {{- end }}
          {{- if .Values.containers.args }}
          args: ["{{ .Values.containers.args | replace "$" "^$" }}"]
          {{- else }}
          args: ["-Dfile.encoding=UTF-8", "$(APP_PARAMETER)"]
          {{- end }}
          {{- if .Values.containers.port }}
          ports:
            - name: http
              containerPort: {{ .Values.containers.port }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: APP_PROFILES
            value: "{{ .Values.extraEnvs.APP_PROFILES }}"
          - name: APP
            value: "{{ .Values.extraEnvs.APP }}"
          - name: APP_PARAMETER
            value: "{{ .Values.extraEnvs.APP_PARAMETER }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 121