// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.LocalTeams}
 */
public  final class LocalTeams extends
    com.google.protobuf.GeneratedMessageLite<
        LocalTeams, LocalTeams.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.LocalTeams)
    LocalTeamsOrBuilder {
  private LocalTeams() {
    teams_ = emptyProtobufList();
  }
  public static final int TEAMS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<Team> teams_;
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  public java.util.List<Team> getTeamsList() {
    return teams_;
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  public java.util.List<? extends TeamOrBuilder>
      getTeamsOrBuilderList() {
    return teams_;
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  public int getTeamsCount() {
    return teams_.size();
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  public Team getTeams(int index) {
    return teams_.get(index);
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  public TeamOrBuilder getTeamsOrBuilder(
      int index) {
    return teams_.get(index);
  }
  private void ensureTeamsIsMutable() {
    if (!teams_.isModifiable()) {
      teams_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(teams_);
     }
  }

  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void setTeams(
      int index, Team value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTeamsIsMutable();
    teams_.set(index, value);
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void setTeams(
      int index, Team.Builder builderForValue) {
    ensureTeamsIsMutable();
    teams_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void addTeams(Team value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTeamsIsMutable();
    teams_.add(value);
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void addTeams(
      int index, Team value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTeamsIsMutable();
    teams_.add(index, value);
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void addTeams(
      Team.Builder builderForValue) {
    ensureTeamsIsMutable();
    teams_.add(builderForValue.build());
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void addTeams(
      int index, Team.Builder builderForValue) {
    ensureTeamsIsMutable();
    teams_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void addAllTeams(
      Iterable<? extends Team> values) {
    ensureTeamsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, teams_);
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void clearTeams() {
    teams_ = emptyProtobufList();
  }
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  private void removeTeams(int index) {
    ensureTeamsIsMutable();
    teams_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < teams_.size(); i++) {
      output.writeMessage(1, teams_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < teams_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, teams_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static LocalTeams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static LocalTeams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static LocalTeams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static LocalTeams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static LocalTeams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static LocalTeams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static LocalTeams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static LocalTeams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static LocalTeams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static LocalTeams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LocalTeams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.LocalTeams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        LocalTeams, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.LocalTeams)
      LocalTeamsOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.LocalTeams.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public java.util.List<Team> getTeamsList() {
      return java.util.Collections.unmodifiableList(
          instance.getTeamsList());
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public int getTeamsCount() {
      return instance.getTeamsCount();
    }/**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Team getTeams(int index) {
      return instance.getTeams(index);
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder setTeams(
        int index, Team value) {
      copyOnWrite();
      instance.setTeams(index, value);
      return this;
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder setTeams(
        int index, Team.Builder builderForValue) {
      copyOnWrite();
      instance.setTeams(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder addTeams(Team value) {
      copyOnWrite();
      instance.addTeams(value);
      return this;
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder addTeams(
        int index, Team value) {
      copyOnWrite();
      instance.addTeams(index, value);
      return this;
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder addTeams(
        Team.Builder builderForValue) {
      copyOnWrite();
      instance.addTeams(builderForValue);
      return this;
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder addTeams(
        int index, Team.Builder builderForValue) {
      copyOnWrite();
      instance.addTeams(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder addAllTeams(
        Iterable<? extends Team> values) {
      copyOnWrite();
      instance.addAllTeams(values);
      return this;
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder clearTeams() {
      copyOnWrite();
      instance.clearTeams();
      return this;
    }
    /**
     * <code>repeated .teammgr.Team teams = 1;</code>
     */
    public Builder removeTeams(int index) {
      copyOnWrite();
      instance.removeTeams(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.LocalTeams)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new LocalTeams();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        teams_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        LocalTeams other = (LocalTeams) arg1;
        teams_= visitor.visitList(teams_, other.teams_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!teams_.isModifiable()) {
                  teams_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(teams_);
                }
                teams_.add(
                    input.readMessage(Team.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (LocalTeams.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.LocalTeams)
  private static final LocalTeams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LocalTeams();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static LocalTeams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LocalTeams> PARSER;

  public static com.google.protobuf.Parser<LocalTeams> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

