// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface LocalTeamsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.LocalTeamsResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .teammgr.LocalTeams teams = 1;</code>
   */
  LocalTeams getTeams();

  /**
   * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
   */
  RemoveLocalTeams getRmvteams();

  /**
   * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
   */
  UpdateLocalTeams getUpdateteams();

  public LocalTeamsResponse.StateCase getStateCase();
}
