// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.LocalTeamsRequest}
 */
public  final class LocalTeamsRequest extends
    com.google.protobuf.GeneratedMessageLite<
        LocalTeamsRequest, LocalTeamsRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.LocalTeamsRequest)
    LocalTeamsRequestOrBuilder {
  private LocalTeamsRequest() {
    gametype_ = "";
  }
  public static final int GAMETYPE_FIELD_NUMBER = 2;
  private String gametype_;
  /**
   * <code>optional string gametype = 2;</code>
   */
  public String getGametype() {
    return gametype_;
  }
  /**
   * <code>optional string gametype = 2;</code>
   */
  public com.google.protobuf.ByteString
      getGametypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gametype_);
  }
  /**
   * <code>optional string gametype = 2;</code>
   */
  private void setGametype(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    gametype_ = value;
  }
  /**
   * <code>optional string gametype = 2;</code>
   */
  private void clearGametype() {
    
    gametype_ = getDefaultInstance().getGametype();
  }
  /**
   * <code>optional string gametype = 2;</code>
   */
  private void setGametypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    gametype_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!gametype_.isEmpty()) {
      output.writeString(2, getGametype());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!gametype_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getGametype());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static LocalTeamsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static LocalTeamsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static LocalTeamsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static LocalTeamsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static LocalTeamsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static LocalTeamsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static LocalTeamsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static LocalTeamsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static LocalTeamsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static LocalTeamsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LocalTeamsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.LocalTeamsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        LocalTeamsRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.LocalTeamsRequest)
      LocalTeamsRequestOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.LocalTeamsRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string gametype = 2;</code>
     */
    public String getGametype() {
      return instance.getGametype();
    }
    /**
     * <code>optional string gametype = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGametypeBytes() {
      return instance.getGametypeBytes();
    }
    /**
     * <code>optional string gametype = 2;</code>
     */
    public Builder setGametype(
        String value) {
      copyOnWrite();
      instance.setGametype(value);
      return this;
    }
    /**
     * <code>optional string gametype = 2;</code>
     */
    public Builder clearGametype() {
      copyOnWrite();
      instance.clearGametype();
      return this;
    }
    /**
     * <code>optional string gametype = 2;</code>
     */
    public Builder setGametypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGametypeBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.LocalTeamsRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new LocalTeamsRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        LocalTeamsRequest other = (LocalTeamsRequest) arg1;
        gametype_ = visitor.visitString(!gametype_.isEmpty(), gametype_,
            !other.gametype_.isEmpty(), other.gametype_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                gametype_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (LocalTeamsRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.LocalTeamsRequest)
  private static final LocalTeamsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LocalTeamsRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static LocalTeamsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LocalTeamsRequest> PARSER;

  public static com.google.protobuf.Parser<LocalTeamsRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

