// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.LocalTeamsResponse}
 */
public  final class LocalTeamsResponse extends
    com.google.protobuf.GeneratedMessageLite<
        LocalTeamsResponse, LocalTeamsResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.LocalTeamsResponse)
    LocalTeamsResponseOrBuilder {
  private LocalTeamsResponse() {
  }
  private int stateCase_ = 0;
  private Object state_;
  public enum StateCase
      implements com.google.protobuf.Internal.EnumLite {
    TEAMS(1),
    RMVTEAMS(2),
    UPDATETEAMS(3),
    STATE_NOT_SET(0);
    private final int value;
    private StateCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StateCase valueOf(int value) {
      return forNumber(value);
    }

    public static StateCase forNumber(int value) {
      switch (value) {
        case 1: return TEAMS;
        case 2: return RMVTEAMS;
        case 3: return UPDATETEAMS;
        case 0: return STATE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public StateCase
  getStateCase() {
    return StateCase.forNumber(
        stateCase_);
  }

  private void clearState() {
    stateCase_ = 0;
    state_ = null;
  }

  public static final int TEAMS_FIELD_NUMBER = 1;
  /**
   * <code>optional .teammgr.LocalTeams teams = 1;</code>
   */
  public LocalTeams getTeams() {
    if (stateCase_ == 1) {
       return (LocalTeams) state_;
    }
    return LocalTeams.getDefaultInstance();
  }
  /**
   * <code>optional .teammgr.LocalTeams teams = 1;</code>
   */
  private void setTeams(LocalTeams value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 1;
  }
  /**
   * <code>optional .teammgr.LocalTeams teams = 1;</code>
   */
  private void setTeams(
      LocalTeams.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 1;
  }
  /**
   * <code>optional .teammgr.LocalTeams teams = 1;</code>
   */
  private void mergeTeams(LocalTeams value) {
    if (stateCase_ == 1 &&
        state_ != LocalTeams.getDefaultInstance()) {
      state_ = LocalTeams.newBuilder((LocalTeams) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 1;
  }
  /**
   * <code>optional .teammgr.LocalTeams teams = 1;</code>
   */
  private void clearTeams() {
    if (stateCase_ == 1) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int RMVTEAMS_FIELD_NUMBER = 2;
  /**
   * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
   */
  public RemoveLocalTeams getRmvteams() {
    if (stateCase_ == 2) {
       return (RemoveLocalTeams) state_;
    }
    return RemoveLocalTeams.getDefaultInstance();
  }
  /**
   * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
   */
  private void setRmvteams(RemoveLocalTeams value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 2;
  }
  /**
   * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
   */
  private void setRmvteams(
      RemoveLocalTeams.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 2;
  }
  /**
   * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
   */
  private void mergeRmvteams(RemoveLocalTeams value) {
    if (stateCase_ == 2 &&
        state_ != RemoveLocalTeams.getDefaultInstance()) {
      state_ = RemoveLocalTeams.newBuilder((RemoveLocalTeams) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 2;
  }
  /**
   * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
   */
  private void clearRmvteams() {
    if (stateCase_ == 2) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int UPDATETEAMS_FIELD_NUMBER = 3;
  /**
   * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
   */
  public UpdateLocalTeams getUpdateteams() {
    if (stateCase_ == 3) {
       return (UpdateLocalTeams) state_;
    }
    return UpdateLocalTeams.getDefaultInstance();
  }
  /**
   * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
   */
  private void setUpdateteams(UpdateLocalTeams value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 3;
  }
  /**
   * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
   */
  private void setUpdateteams(
      UpdateLocalTeams.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 3;
  }
  /**
   * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
   */
  private void mergeUpdateteams(UpdateLocalTeams value) {
    if (stateCase_ == 3 &&
        state_ != UpdateLocalTeams.getDefaultInstance()) {
      state_ = UpdateLocalTeams.newBuilder((UpdateLocalTeams) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 3;
  }
  /**
   * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
   */
  private void clearUpdateteams() {
    if (stateCase_ == 3) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stateCase_ == 1) {
      output.writeMessage(1, (LocalTeams) state_);
    }
    if (stateCase_ == 2) {
      output.writeMessage(2, (RemoveLocalTeams) state_);
    }
    if (stateCase_ == 3) {
      output.writeMessage(3, (UpdateLocalTeams) state_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (stateCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (LocalTeams) state_);
    }
    if (stateCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (RemoveLocalTeams) state_);
    }
    if (stateCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (UpdateLocalTeams) state_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static LocalTeamsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static LocalTeamsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static LocalTeamsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static LocalTeamsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static LocalTeamsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static LocalTeamsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static LocalTeamsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static LocalTeamsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static LocalTeamsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static LocalTeamsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LocalTeamsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.LocalTeamsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        LocalTeamsResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.LocalTeamsResponse)
      LocalTeamsResponseOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.LocalTeamsResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public StateCase
        getStateCase() {
      return instance.getStateCase();
    }

    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }


    /**
     * <code>optional .teammgr.LocalTeams teams = 1;</code>
     */
    public LocalTeams getTeams() {
      return instance.getTeams();
    }
    /**
     * <code>optional .teammgr.LocalTeams teams = 1;</code>
     */
    public Builder setTeams(LocalTeams value) {
      copyOnWrite();
      instance.setTeams(value);
      return this;
    }
    /**
     * <code>optional .teammgr.LocalTeams teams = 1;</code>
     */
    public Builder setTeams(
        LocalTeams.Builder builderForValue) {
      copyOnWrite();
      instance.setTeams(builderForValue);
      return this;
    }
    /**
     * <code>optional .teammgr.LocalTeams teams = 1;</code>
     */
    public Builder mergeTeams(LocalTeams value) {
      copyOnWrite();
      instance.mergeTeams(value);
      return this;
    }
    /**
     * <code>optional .teammgr.LocalTeams teams = 1;</code>
     */
    public Builder clearTeams() {
      copyOnWrite();
      instance.clearTeams();
      return this;
    }

    /**
     * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
     */
    public RemoveLocalTeams getRmvteams() {
      return instance.getRmvteams();
    }
    /**
     * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
     */
    public Builder setRmvteams(RemoveLocalTeams value) {
      copyOnWrite();
      instance.setRmvteams(value);
      return this;
    }
    /**
     * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
     */
    public Builder setRmvteams(
        RemoveLocalTeams.Builder builderForValue) {
      copyOnWrite();
      instance.setRmvteams(builderForValue);
      return this;
    }
    /**
     * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
     */
    public Builder mergeRmvteams(RemoveLocalTeams value) {
      copyOnWrite();
      instance.mergeRmvteams(value);
      return this;
    }
    /**
     * <code>optional .teammgr.RemoveLocalTeams rmvteams = 2;</code>
     */
    public Builder clearRmvteams() {
      copyOnWrite();
      instance.clearRmvteams();
      return this;
    }

    /**
     * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
     */
    public UpdateLocalTeams getUpdateteams() {
      return instance.getUpdateteams();
    }
    /**
     * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
     */
    public Builder setUpdateteams(UpdateLocalTeams value) {
      copyOnWrite();
      instance.setUpdateteams(value);
      return this;
    }
    /**
     * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
     */
    public Builder setUpdateteams(
        UpdateLocalTeams.Builder builderForValue) {
      copyOnWrite();
      instance.setUpdateteams(builderForValue);
      return this;
    }
    /**
     * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
     */
    public Builder mergeUpdateteams(UpdateLocalTeams value) {
      copyOnWrite();
      instance.mergeUpdateteams(value);
      return this;
    }
    /**
     * <code>optional .teammgr.UpdateLocalTeams updateteams = 3;</code>
     */
    public Builder clearUpdateteams() {
      copyOnWrite();
      instance.clearUpdateteams();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.LocalTeamsResponse)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new LocalTeamsResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        LocalTeamsResponse other = (LocalTeamsResponse) arg1;
        switch (other.getStateCase()) {
          case TEAMS: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 1,
                state_,
                other.state_);
            break;
          }
          case RMVTEAMS: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 2,
                state_,
                other.state_);
            break;
          }
          case UPDATETEAMS: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 3,
                state_,
                other.state_);
            break;
          }
          case STATE_NOT_SET: {
            visitor.visitOneofNotSet(stateCase_ != 0);
            break;
          }
        }
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          if (other.stateCase_ != 0) {
            stateCase_ = other.stateCase_;
          }
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                LocalTeams.Builder subBuilder = null;
                if (stateCase_ == 1) {
                  subBuilder = ((LocalTeams) state_).toBuilder();
                }
                state_ =
                     input.readMessage(LocalTeams.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((LocalTeams) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 1;
                break;
              }
              case 18: {
                RemoveLocalTeams.Builder subBuilder = null;
                if (stateCase_ == 2) {
                  subBuilder = ((RemoveLocalTeams) state_).toBuilder();
                }
                state_ =
                     input.readMessage(RemoveLocalTeams.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((RemoveLocalTeams) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 2;
                break;
              }
              case 26: {
                UpdateLocalTeams.Builder subBuilder = null;
                if (stateCase_ == 3) {
                  subBuilder = ((UpdateLocalTeams) state_).toBuilder();
                }
                state_ =
                     input.readMessage(UpdateLocalTeams.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((UpdateLocalTeams) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 3;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (LocalTeamsResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.LocalTeamsResponse)
  private static final LocalTeamsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LocalTeamsResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static LocalTeamsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LocalTeamsResponse> PARSER;

  public static com.google.protobuf.Parser<LocalTeamsResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

