// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface LocalTeamsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.LocalTeamsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string gametype = 2;</code>
   */
  String getGametype();
  /**
   * <code>optional string gametype = 2;</code>
   */
  com.google.protobuf.ByteString
      getGametypeBytes();
}
