// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface RemoveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.RemoveRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string gametype = 1;</code>
   */
  String getGametype();
  /**
   * <code>optional string gametype = 1;</code>
   */
  com.google.protobuf.ByteString
      getGametypeBytes();

  /**
   * <code>optional uint64 captainid = 2;</code>
   */
  long getCaptainid();

  /**
   * <code>optional uint64 userid = 3;</code>
   */
  long getUserid();
}
