// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.RemoveLocalTeams}
 */
public  final class RemoveLocalTeams extends
    com.google.protobuf.GeneratedMessageLite<
        RemoveLocalTeams, RemoveLocalTeams.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.RemoveLocalTeams)
    RemoveLocalTeamsOrBuilder {
  private RemoveLocalTeams() {
    teams_ = emptyLongList();
  }
  public static final int TEAMS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList teams_;
  /**
   * <code>repeated uint64 teams = 1;</code>
   */
  public java.util.List<Long>
      getTeamsList() {
    return teams_;
  }
  /**
   * <code>repeated uint64 teams = 1;</code>
   */
  public int getTeamsCount() {
    return teams_.size();
  }
  /**
   * <code>repeated uint64 teams = 1;</code>
   */
  public long getTeams(int index) {
    return teams_.getLong(index);
  }
  private void ensureTeamsIsMutable() {
    if (!teams_.isModifiable()) {
      teams_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(teams_);
     }
  }
  /**
   * <code>repeated uint64 teams = 1;</code>
   */
  private void setTeams(
      int index, long value) {
    ensureTeamsIsMutable();
    teams_.setLong(index, value);
  }
  /**
   * <code>repeated uint64 teams = 1;</code>
   */
  private void addTeams(long value) {
    ensureTeamsIsMutable();
    teams_.addLong(value);
  }
  /**
   * <code>repeated uint64 teams = 1;</code>
   */
  private void addAllTeams(
      Iterable<? extends Long> values) {
    ensureTeamsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, teams_);
  }
  /**
   * <code>repeated uint64 teams = 1;</code>
   */
  private void clearTeams() {
    teams_ = emptyLongList();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < teams_.size(); i++) {
      output.writeUInt64(1, teams_.getLong(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < teams_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(teams_.getLong(i));
      }
      size += dataSize;
      size += 1 * getTeamsList().size();
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static RemoveLocalTeams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static RemoveLocalTeams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static RemoveLocalTeams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static RemoveLocalTeams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static RemoveLocalTeams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static RemoveLocalTeams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static RemoveLocalTeams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static RemoveLocalTeams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static RemoveLocalTeams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static RemoveLocalTeams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RemoveLocalTeams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.RemoveLocalTeams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        RemoveLocalTeams, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.RemoveLocalTeams)
      RemoveLocalTeamsOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.RemoveLocalTeams.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated uint64 teams = 1;</code>
     */
    public java.util.List<Long>
        getTeamsList() {
      return java.util.Collections.unmodifiableList(
          instance.getTeamsList());
    }
    /**
     * <code>repeated uint64 teams = 1;</code>
     */
    public int getTeamsCount() {
      return instance.getTeamsCount();
    }
    /**
     * <code>repeated uint64 teams = 1;</code>
     */
    public long getTeams(int index) {
      return instance.getTeams(index);
    }
    /**
     * <code>repeated uint64 teams = 1;</code>
     */
    public Builder setTeams(
        int index, long value) {
      copyOnWrite();
      instance.setTeams(index, value);
      return this;
    }
    /**
     * <code>repeated uint64 teams = 1;</code>
     */
    public Builder addTeams(long value) {
      copyOnWrite();
      instance.addTeams(value);
      return this;
    }
    /**
     * <code>repeated uint64 teams = 1;</code>
     */
    public Builder addAllTeams(
        Iterable<? extends Long> values) {
      copyOnWrite();
      instance.addAllTeams(values);
      return this;
    }
    /**
     * <code>repeated uint64 teams = 1;</code>
     */
    public Builder clearTeams() {
      copyOnWrite();
      instance.clearTeams();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.RemoveLocalTeams)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new RemoveLocalTeams();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        teams_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        RemoveLocalTeams other = (RemoveLocalTeams) arg1;
        teams_= visitor.visitLongList(teams_, other.teams_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                if (!teams_.isModifiable()) {
                  teams_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(teams_);
                }
                teams_.addLong(input.readUInt64());
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!teams_.isModifiable() && input.getBytesUntilLimit() > 0) {
                  teams_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(teams_);
                }
                while (input.getBytesUntilLimit() > 0) {
                  teams_.addLong(input.readUInt64());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (RemoveLocalTeams.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.RemoveLocalTeams)
  private static final RemoveLocalTeams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RemoveLocalTeams();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static RemoveLocalTeams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoveLocalTeams> PARSER;

  public static com.google.protobuf.Parser<RemoveLocalTeams> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

