// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.RemoveRequest}
 */
public  final class RemoveRequest extends
    com.google.protobuf.GeneratedMessageLite<
        RemoveRequest, RemoveRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.RemoveRequest)
    RemoveRequestOrBuilder {
  private RemoveRequest() {
    gametype_ = "";
  }
  public static final int GAMETYPE_FIELD_NUMBER = 1;
  private String gametype_;
  /**
   * <code>optional string gametype = 1;</code>
   */
  public String getGametype() {
    return gametype_;
  }
  /**
   * <code>optional string gametype = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGametypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gametype_);
  }
  /**
   * <code>optional string gametype = 1;</code>
   */
  private void setGametype(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    gametype_ = value;
  }
  /**
   * <code>optional string gametype = 1;</code>
   */
  private void clearGametype() {
    
    gametype_ = getDefaultInstance().getGametype();
  }
  /**
   * <code>optional string gametype = 1;</code>
   */
  private void setGametypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    gametype_ = value.toStringUtf8();
  }

  public static final int CAPTAINID_FIELD_NUMBER = 2;
  private long captainid_;
  /**
   * <code>optional uint64 captainid = 2;</code>
   */
  public long getCaptainid() {
    return captainid_;
  }
  /**
   * <code>optional uint64 captainid = 2;</code>
   */
  private void setCaptainid(long value) {
    
    captainid_ = value;
  }
  /**
   * <code>optional uint64 captainid = 2;</code>
   */
  private void clearCaptainid() {
    
    captainid_ = 0L;
  }

  public static final int USERID_FIELD_NUMBER = 3;
  private long userid_;
  /**
   * <code>optional uint64 userid = 3;</code>
   */
  public long getUserid() {
    return userid_;
  }
  /**
   * <code>optional uint64 userid = 3;</code>
   */
  private void setUserid(long value) {
    
    userid_ = value;
  }
  /**
   * <code>optional uint64 userid = 3;</code>
   */
  private void clearUserid() {
    
    userid_ = 0L;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!gametype_.isEmpty()) {
      output.writeString(1, getGametype());
    }
    if (captainid_ != 0L) {
      output.writeUInt64(2, captainid_);
    }
    if (userid_ != 0L) {
      output.writeUInt64(3, userid_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!gametype_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getGametype());
    }
    if (captainid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, captainid_);
    }
    if (userid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, userid_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static RemoveRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static RemoveRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static RemoveRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static RemoveRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static RemoveRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static RemoveRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static RemoveRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static RemoveRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static RemoveRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static RemoveRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RemoveRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.RemoveRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        RemoveRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.RemoveRequest)
      RemoveRequestOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.RemoveRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string gametype = 1;</code>
     */
    public String getGametype() {
      return instance.getGametype();
    }
    /**
     * <code>optional string gametype = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGametypeBytes() {
      return instance.getGametypeBytes();
    }
    /**
     * <code>optional string gametype = 1;</code>
     */
    public Builder setGametype(
        String value) {
      copyOnWrite();
      instance.setGametype(value);
      return this;
    }
    /**
     * <code>optional string gametype = 1;</code>
     */
    public Builder clearGametype() {
      copyOnWrite();
      instance.clearGametype();
      return this;
    }
    /**
     * <code>optional string gametype = 1;</code>
     */
    public Builder setGametypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGametypeBytes(value);
      return this;
    }

    /**
     * <code>optional uint64 captainid = 2;</code>
     */
    public long getCaptainid() {
      return instance.getCaptainid();
    }
    /**
     * <code>optional uint64 captainid = 2;</code>
     */
    public Builder setCaptainid(long value) {
      copyOnWrite();
      instance.setCaptainid(value);
      return this;
    }
    /**
     * <code>optional uint64 captainid = 2;</code>
     */
    public Builder clearCaptainid() {
      copyOnWrite();
      instance.clearCaptainid();
      return this;
    }

    /**
     * <code>optional uint64 userid = 3;</code>
     */
    public long getUserid() {
      return instance.getUserid();
    }
    /**
     * <code>optional uint64 userid = 3;</code>
     */
    public Builder setUserid(long value) {
      copyOnWrite();
      instance.setUserid(value);
      return this;
    }
    /**
     * <code>optional uint64 userid = 3;</code>
     */
    public Builder clearUserid() {
      copyOnWrite();
      instance.clearUserid();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.RemoveRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new RemoveRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        RemoveRequest other = (RemoveRequest) arg1;
        gametype_ = visitor.visitString(!gametype_.isEmpty(), gametype_,
            !other.gametype_.isEmpty(), other.gametype_);
        captainid_ = visitor.visitLong(captainid_ != 0L, captainid_,
            other.captainid_ != 0L, other.captainid_);
        userid_ = visitor.visitLong(userid_ != 0L, userid_,
            other.userid_ != 0L, other.userid_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                gametype_ = s;
                break;
              }
              case 16: {

                captainid_ = input.readUInt64();
                break;
              }
              case 24: {

                userid_ = input.readUInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (RemoveRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.RemoveRequest)
  private static final RemoveRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RemoveRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static RemoveRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoveRequest> PARSER;

  public static com.google.protobuf.Parser<RemoveRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

