// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.TeamGoing}
 */
public  final class TeamGoing extends
    com.google.protobuf.GeneratedMessageLite<
        TeamGoing, TeamGoing.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.TeamGoing)
    TeamGoingOrBuilder {
  private TeamGoing() {
    teammembers_ = emptyProtobufList();
  }
  public static final int TEAMMEMBERS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<TeamMember> teammembers_;
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  public java.util.List<TeamMember> getTeammembersList() {
    return teammembers_;
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  public java.util.List<? extends TeamMemberOrBuilder>
      getTeammembersOrBuilderList() {
    return teammembers_;
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  public int getTeammembersCount() {
    return teammembers_.size();
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  public TeamMember getTeammembers(int index) {
    return teammembers_.get(index);
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  public TeamMemberOrBuilder getTeammembersOrBuilder(
      int index) {
    return teammembers_.get(index);
  }
  private void ensureTeammembersIsMutable() {
    if (!teammembers_.isModifiable()) {
      teammembers_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(teammembers_);
     }
  }

  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void setTeammembers(
      int index, TeamMember value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTeammembersIsMutable();
    teammembers_.set(index, value);
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void setTeammembers(
      int index, TeamMember.Builder builderForValue) {
    ensureTeammembersIsMutable();
    teammembers_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void addTeammembers(TeamMember value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTeammembersIsMutable();
    teammembers_.add(value);
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void addTeammembers(
      int index, TeamMember value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTeammembersIsMutable();
    teammembers_.add(index, value);
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void addTeammembers(
      TeamMember.Builder builderForValue) {
    ensureTeammembersIsMutable();
    teammembers_.add(builderForValue.build());
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void addTeammembers(
      int index, TeamMember.Builder builderForValue) {
    ensureTeammembersIsMutable();
    teammembers_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void addAllTeammembers(
      Iterable<? extends TeamMember> values) {
    ensureTeammembersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, teammembers_);
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void clearTeammembers() {
    teammembers_ = emptyProtobufList();
  }
  /**
   * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
   */
  private void removeTeammembers(int index) {
    ensureTeammembersIsMutable();
    teammembers_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < teammembers_.size(); i++) {
      output.writeMessage(1, teammembers_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < teammembers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, teammembers_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static TeamGoing parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamGoing parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamGoing parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamGoing parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamGoing parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamGoing parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamGoing parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static TeamGoing parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamGoing parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamGoing parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeamGoing prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.TeamGoing}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        TeamGoing, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.TeamGoing)
      TeamGoingOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.TeamGoing.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public java.util.List<TeamMember> getTeammembersList() {
      return java.util.Collections.unmodifiableList(
          instance.getTeammembersList());
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public int getTeammembersCount() {
      return instance.getTeammembersCount();
    }/**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public TeamMember getTeammembers(int index) {
      return instance.getTeammembers(index);
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder setTeammembers(
        int index, TeamMember value) {
      copyOnWrite();
      instance.setTeammembers(index, value);
      return this;
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder setTeammembers(
        int index, TeamMember.Builder builderForValue) {
      copyOnWrite();
      instance.setTeammembers(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder addTeammembers(TeamMember value) {
      copyOnWrite();
      instance.addTeammembers(value);
      return this;
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder addTeammembers(
        int index, TeamMember value) {
      copyOnWrite();
      instance.addTeammembers(index, value);
      return this;
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder addTeammembers(
        TeamMember.Builder builderForValue) {
      copyOnWrite();
      instance.addTeammembers(builderForValue);
      return this;
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder addTeammembers(
        int index, TeamMember.Builder builderForValue) {
      copyOnWrite();
      instance.addTeammembers(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder addAllTeammembers(
        Iterable<? extends TeamMember> values) {
      copyOnWrite();
      instance.addAllTeammembers(values);
      return this;
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder clearTeammembers() {
      copyOnWrite();
      instance.clearTeammembers();
      return this;
    }
    /**
     * <code>repeated .teammgr.TeamMember teammembers = 1;</code>
     */
    public Builder removeTeammembers(int index) {
      copyOnWrite();
      instance.removeTeammembers(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.TeamGoing)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new TeamGoing();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        teammembers_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        TeamGoing other = (TeamGoing) arg1;
        teammembers_= visitor.visitList(teammembers_, other.teammembers_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!teammembers_.isModifiable()) {
                  teammembers_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(teammembers_);
                }
                teammembers_.add(
                    input.readMessage(TeamMember.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (TeamGoing.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.TeamGoing)
  private static final TeamGoing DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeamGoing();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static TeamGoing getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TeamGoing> PARSER;

  public static com.google.protobuf.Parser<TeamGoing> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

