// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.TeamMember}
 */
public  final class TeamMember extends
    com.google.protobuf.GeneratedMessageLite<
        TeamMember, TeamMember.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.TeamMember)
    TeamMemberOrBuilder {
  private TeamMember() {
    username_ = "";
    picurl_ = "";
  }
  public static final int USERID_FIELD_NUMBER = 1;
  private long userid_;
  /**
   * <pre>
   * user id
   * </pre>
   *
   * <code>optional uint64 userid = 1;</code>
   */
  public long getUserid() {
    return userid_;
  }
  /**
   * <pre>
   * user id
   * </pre>
   *
   * <code>optional uint64 userid = 1;</code>
   */
  private void setUserid(long value) {
    
    userid_ = value;
  }
  /**
   * <pre>
   * user id
   * </pre>
   *
   * <code>optional uint64 userid = 1;</code>
   */
  private void clearUserid() {
    
    userid_ = 0L;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private String username_;
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  public String getUsername() {
    return username_;
  }
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  private void setUsername(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    username_ = value;
  }
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  private void clearUsername() {
    
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    username_ = value.toStringUtf8();
  }

  public static final int LV_FIELD_NUMBER = 3;
  private int lv_;
  /**
   * <pre>
   * user level
   * </pre>
   *
   * <code>optional int32 lv = 3;</code>
   */
  public int getLv() {
    return lv_;
  }
  /**
   * <pre>
   * user level
   * </pre>
   *
   * <code>optional int32 lv = 3;</code>
   */
  private void setLv(int value) {
    
    lv_ = value;
  }
  /**
   * <pre>
   * user level
   * </pre>
   *
   * <code>optional int32 lv = 3;</code>
   */
  private void clearLv() {
    
    lv_ = 0;
  }

  public static final int CLAZZ_FIELD_NUMBER = 4;
  private int clazz_;
  /**
   * <pre>
   * user class
   * </pre>
   *
   * <code>optional int32 clazz = 4;</code>
   */
  public int getClazz() {
    return clazz_;
  }
  /**
   * <pre>
   * user class
   * </pre>
   *
   * <code>optional int32 clazz = 4;</code>
   */
  private void setClazz(int value) {
    
    clazz_ = value;
  }
  /**
   * <pre>
   * user class
   * </pre>
   *
   * <code>optional int32 clazz = 4;</code>
   */
  private void clearClazz() {
    
    clazz_ = 0;
  }

  public static final int ISCAPTAIN_FIELD_NUMBER = 5;
  private boolean isCaptain_;
  /**
   * <pre>
   * is captain
   * </pre>
   *
   * <code>optional bool isCaptain = 5;</code>
   */
  public boolean getIsCaptain() {
    return isCaptain_;
  }
  /**
   * <pre>
   * is captain
   * </pre>
   *
   * <code>optional bool isCaptain = 5;</code>
   */
  private void setIsCaptain(boolean value) {
    
    isCaptain_ = value;
  }
  /**
   * <pre>
   * is captain
   * </pre>
   *
   * <code>optional bool isCaptain = 5;</code>
   */
  private void clearIsCaptain() {
    
    isCaptain_ = false;
  }

  public static final int PICURL_FIELD_NUMBER = 6;
  private String picurl_;
  /**
   * <pre>
   * picture url
   * </pre>
   *
   * <code>optional string picurl = 6;</code>
   */
  public String getPicurl() {
    return picurl_;
  }
  /**
   * <pre>
   * picture url
   * </pre>
   *
   * <code>optional string picurl = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPicurlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(picurl_);
  }
  /**
   * <pre>
   * picture url
   * </pre>
   *
   * <code>optional string picurl = 6;</code>
   */
  private void setPicurl(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    picurl_ = value;
  }
  /**
   * <pre>
   * picture url
   * </pre>
   *
   * <code>optional string picurl = 6;</code>
   */
  private void clearPicurl() {
    
    picurl_ = getDefaultInstance().getPicurl();
  }
  /**
   * <pre>
   * picture url
   * </pre>
   *
   * <code>optional string picurl = 6;</code>
   */
  private void setPicurlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    picurl_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userid_ != 0L) {
      output.writeUInt64(1, userid_);
    }
    if (!username_.isEmpty()) {
      output.writeString(2, getUsername());
    }
    if (lv_ != 0) {
      output.writeInt32(3, lv_);
    }
    if (clazz_ != 0) {
      output.writeInt32(4, clazz_);
    }
    if (isCaptain_ != false) {
      output.writeBool(5, isCaptain_);
    }
    if (!picurl_.isEmpty()) {
      output.writeString(6, getPicurl());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (userid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, userid_);
    }
    if (!username_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getUsername());
    }
    if (lv_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, lv_);
    }
    if (clazz_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, clazz_);
    }
    if (isCaptain_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isCaptain_);
    }
    if (!picurl_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getPicurl());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static TeamMember parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamMember parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamMember parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamMember parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamMember parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamMember parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamMember parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static TeamMember parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamMember parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamMember parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeamMember prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.TeamMember}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        TeamMember, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.TeamMember)
      TeamMemberOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.TeamMember.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * user id
     * </pre>
     *
     * <code>optional uint64 userid = 1;</code>
     */
    public long getUserid() {
      return instance.getUserid();
    }
    /**
     * <pre>
     * user id
     * </pre>
     *
     * <code>optional uint64 userid = 1;</code>
     */
    public Builder setUserid(long value) {
      copyOnWrite();
      instance.setUserid(value);
      return this;
    }
    /**
     * <pre>
     * user id
     * </pre>
     *
     * <code>optional uint64 userid = 1;</code>
     */
    public Builder clearUserid() {
      copyOnWrite();
      instance.clearUserid();
      return this;
    }

    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public String getUsername() {
      return instance.getUsername();
    }
    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public Builder setUsername(
        String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string username = 2;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <pre>
     * user level
     * </pre>
     *
     * <code>optional int32 lv = 3;</code>
     */
    public int getLv() {
      return instance.getLv();
    }
    /**
     * <pre>
     * user level
     * </pre>
     *
     * <code>optional int32 lv = 3;</code>
     */
    public Builder setLv(int value) {
      copyOnWrite();
      instance.setLv(value);
      return this;
    }
    /**
     * <pre>
     * user level
     * </pre>
     *
     * <code>optional int32 lv = 3;</code>
     */
    public Builder clearLv() {
      copyOnWrite();
      instance.clearLv();
      return this;
    }

    /**
     * <pre>
     * user class
     * </pre>
     *
     * <code>optional int32 clazz = 4;</code>
     */
    public int getClazz() {
      return instance.getClazz();
    }
    /**
     * <pre>
     * user class
     * </pre>
     *
     * <code>optional int32 clazz = 4;</code>
     */
    public Builder setClazz(int value) {
      copyOnWrite();
      instance.setClazz(value);
      return this;
    }
    /**
     * <pre>
     * user class
     * </pre>
     *
     * <code>optional int32 clazz = 4;</code>
     */
    public Builder clearClazz() {
      copyOnWrite();
      instance.clearClazz();
      return this;
    }

    /**
     * <pre>
     * is captain
     * </pre>
     *
     * <code>optional bool isCaptain = 5;</code>
     */
    public boolean getIsCaptain() {
      return instance.getIsCaptain();
    }
    /**
     * <pre>
     * is captain
     * </pre>
     *
     * <code>optional bool isCaptain = 5;</code>
     */
    public Builder setIsCaptain(boolean value) {
      copyOnWrite();
      instance.setIsCaptain(value);
      return this;
    }
    /**
     * <pre>
     * is captain
     * </pre>
     *
     * <code>optional bool isCaptain = 5;</code>
     */
    public Builder clearIsCaptain() {
      copyOnWrite();
      instance.clearIsCaptain();
      return this;
    }

    /**
     * <pre>
     * picture url
     * </pre>
     *
     * <code>optional string picurl = 6;</code>
     */
    public String getPicurl() {
      return instance.getPicurl();
    }
    /**
     * <pre>
     * picture url
     * </pre>
     *
     * <code>optional string picurl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPicurlBytes() {
      return instance.getPicurlBytes();
    }
    /**
     * <pre>
     * picture url
     * </pre>
     *
     * <code>optional string picurl = 6;</code>
     */
    public Builder setPicurl(
        String value) {
      copyOnWrite();
      instance.setPicurl(value);
      return this;
    }
    /**
     * <pre>
     * picture url
     * </pre>
     *
     * <code>optional string picurl = 6;</code>
     */
    public Builder clearPicurl() {
      copyOnWrite();
      instance.clearPicurl();
      return this;
    }
    /**
     * <pre>
     * picture url
     * </pre>
     *
     * <code>optional string picurl = 6;</code>
     */
    public Builder setPicurlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPicurlBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.TeamMember)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new TeamMember();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        TeamMember other = (TeamMember) arg1;
        userid_ = visitor.visitLong(userid_ != 0L, userid_,
            other.userid_ != 0L, other.userid_);
        username_ = visitor.visitString(!username_.isEmpty(), username_,
            !other.username_.isEmpty(), other.username_);
        lv_ = visitor.visitInt(lv_ != 0, lv_,
            other.lv_ != 0, other.lv_);
        clazz_ = visitor.visitInt(clazz_ != 0, clazz_,
            other.clazz_ != 0, other.clazz_);
        isCaptain_ = visitor.visitBoolean(isCaptain_ != false, isCaptain_,
            other.isCaptain_ != false, other.isCaptain_);
        picurl_ = visitor.visitString(!picurl_.isEmpty(), picurl_,
            !other.picurl_.isEmpty(), other.picurl_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                userid_ = input.readUInt64();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                username_ = s;
                break;
              }
              case 24: {

                lv_ = input.readInt32();
                break;
              }
              case 32: {

                clazz_ = input.readInt32();
                break;
              }
              case 40: {

                isCaptain_ = input.readBool();
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                picurl_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (TeamMember.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.TeamMember)
  private static final TeamMember DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeamMember();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static TeamMember getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TeamMember> PARSER;

  public static com.google.protobuf.Parser<TeamMember> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

