// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.Team}
 */
public  final class Team extends
    com.google.protobuf.GeneratedMessageLite<
        Team, Team.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.Team)
    TeamOrBuilder {
  private Team() {
    captainname_ = "";
    picurl_ = "";
  }
  public static final int CAPTAINID_FIELD_NUMBER = 1;
  private long captainid_;
  /**
   * <code>optional uint64 captainid = 1;</code>
   */
  public long getCaptainid() {
    return captainid_;
  }
  /**
   * <code>optional uint64 captainid = 1;</code>
   */
  private void setCaptainid(long value) {
    
    captainid_ = value;
  }
  /**
   * <code>optional uint64 captainid = 1;</code>
   */
  private void clearCaptainid() {
    
    captainid_ = 0L;
  }

  public static final int CAPTAINNAME_FIELD_NUMBER = 2;
  private String captainname_;
  /**
   * <code>optional string captainname = 2;</code>
   */
  public String getCaptainname() {
    return captainname_;
  }
  /**
   * <code>optional string captainname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCaptainnameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(captainname_);
  }
  /**
   * <code>optional string captainname = 2;</code>
   */
  private void setCaptainname(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    captainname_ = value;
  }
  /**
   * <code>optional string captainname = 2;</code>
   */
  private void clearCaptainname() {
    
    captainname_ = getDefaultInstance().getCaptainname();
  }
  /**
   * <code>optional string captainname = 2;</code>
   */
  private void setCaptainnameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    captainname_ = value.toStringUtf8();
  }

  public static final int LV_FIELD_NUMBER = 3;
  private int lv_;
  /**
   * <code>optional int32 lv = 3;</code>
   */
  public int getLv() {
    return lv_;
  }
  /**
   * <code>optional int32 lv = 3;</code>
   */
  private void setLv(int value) {
    
    lv_ = value;
  }
  /**
   * <code>optional int32 lv = 3;</code>
   */
  private void clearLv() {
    
    lv_ = 0;
  }

  public static final int MAX_FIELD_NUMBER = 4;
  private int max_;
  /**
   * <code>optional int32 max = 4;</code>
   */
  public int getMax() {
    return max_;
  }
  /**
   * <code>optional int32 max = 4;</code>
   */
  private void setMax(int value) {
    
    max_ = value;
  }
  /**
   * <code>optional int32 max = 4;</code>
   */
  private void clearMax() {
    
    max_ = 0;
  }

  public static final int NUM_FIELD_NUMBER = 5;
  private int num_;
  /**
   * <code>optional int32 num = 5;</code>
   */
  public int getNum() {
    return num_;
  }
  /**
   * <code>optional int32 num = 5;</code>
   */
  private void setNum(int value) {
    
    num_ = value;
  }
  /**
   * <code>optional int32 num = 5;</code>
   */
  private void clearNum() {
    
    num_ = 0;
  }

  public static final int PICURL_FIELD_NUMBER = 6;
  private String picurl_;
  /**
   * <code>optional string picurl = 6;</code>
   */
  public String getPicurl() {
    return picurl_;
  }
  /**
   * <code>optional string picurl = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPicurlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(picurl_);
  }
  /**
   * <code>optional string picurl = 6;</code>
   */
  private void setPicurl(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    picurl_ = value;
  }
  /**
   * <code>optional string picurl = 6;</code>
   */
  private void clearPicurl() {
    
    picurl_ = getDefaultInstance().getPicurl();
  }
  /**
   * <code>optional string picurl = 6;</code>
   */
  private void setPicurlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    picurl_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (captainid_ != 0L) {
      output.writeUInt64(1, captainid_);
    }
    if (!captainname_.isEmpty()) {
      output.writeString(2, getCaptainname());
    }
    if (lv_ != 0) {
      output.writeInt32(3, lv_);
    }
    if (max_ != 0) {
      output.writeInt32(4, max_);
    }
    if (num_ != 0) {
      output.writeInt32(5, num_);
    }
    if (!picurl_.isEmpty()) {
      output.writeString(6, getPicurl());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (captainid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, captainid_);
    }
    if (!captainname_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getCaptainname());
    }
    if (lv_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, lv_);
    }
    if (max_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, max_);
    }
    if (num_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, num_);
    }
    if (!picurl_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getPicurl());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static Team parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Team parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Team parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Team parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Team parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Team parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Team parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static Team parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Team parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Team parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Team prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.Team}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        Team, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.Team)
      TeamOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.Team.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional uint64 captainid = 1;</code>
     */
    public long getCaptainid() {
      return instance.getCaptainid();
    }
    /**
     * <code>optional uint64 captainid = 1;</code>
     */
    public Builder setCaptainid(long value) {
      copyOnWrite();
      instance.setCaptainid(value);
      return this;
    }
    /**
     * <code>optional uint64 captainid = 1;</code>
     */
    public Builder clearCaptainid() {
      copyOnWrite();
      instance.clearCaptainid();
      return this;
    }

    /**
     * <code>optional string captainname = 2;</code>
     */
    public String getCaptainname() {
      return instance.getCaptainname();
    }
    /**
     * <code>optional string captainname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCaptainnameBytes() {
      return instance.getCaptainnameBytes();
    }
    /**
     * <code>optional string captainname = 2;</code>
     */
    public Builder setCaptainname(
        String value) {
      copyOnWrite();
      instance.setCaptainname(value);
      return this;
    }
    /**
     * <code>optional string captainname = 2;</code>
     */
    public Builder clearCaptainname() {
      copyOnWrite();
      instance.clearCaptainname();
      return this;
    }
    /**
     * <code>optional string captainname = 2;</code>
     */
    public Builder setCaptainnameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCaptainnameBytes(value);
      return this;
    }

    /**
     * <code>optional int32 lv = 3;</code>
     */
    public int getLv() {
      return instance.getLv();
    }
    /**
     * <code>optional int32 lv = 3;</code>
     */
    public Builder setLv(int value) {
      copyOnWrite();
      instance.setLv(value);
      return this;
    }
    /**
     * <code>optional int32 lv = 3;</code>
     */
    public Builder clearLv() {
      copyOnWrite();
      instance.clearLv();
      return this;
    }

    /**
     * <code>optional int32 max = 4;</code>
     */
    public int getMax() {
      return instance.getMax();
    }
    /**
     * <code>optional int32 max = 4;</code>
     */
    public Builder setMax(int value) {
      copyOnWrite();
      instance.setMax(value);
      return this;
    }
    /**
     * <code>optional int32 max = 4;</code>
     */
    public Builder clearMax() {
      copyOnWrite();
      instance.clearMax();
      return this;
    }

    /**
     * <code>optional int32 num = 5;</code>
     */
    public int getNum() {
      return instance.getNum();
    }
    /**
     * <code>optional int32 num = 5;</code>
     */
    public Builder setNum(int value) {
      copyOnWrite();
      instance.setNum(value);
      return this;
    }
    /**
     * <code>optional int32 num = 5;</code>
     */
    public Builder clearNum() {
      copyOnWrite();
      instance.clearNum();
      return this;
    }

    /**
     * <code>optional string picurl = 6;</code>
     */
    public String getPicurl() {
      return instance.getPicurl();
    }
    /**
     * <code>optional string picurl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPicurlBytes() {
      return instance.getPicurlBytes();
    }
    /**
     * <code>optional string picurl = 6;</code>
     */
    public Builder setPicurl(
        String value) {
      copyOnWrite();
      instance.setPicurl(value);
      return this;
    }
    /**
     * <code>optional string picurl = 6;</code>
     */
    public Builder clearPicurl() {
      copyOnWrite();
      instance.clearPicurl();
      return this;
    }
    /**
     * <code>optional string picurl = 6;</code>
     */
    public Builder setPicurlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPicurlBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.Team)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new Team();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        Team other = (Team) arg1;
        captainid_ = visitor.visitLong(captainid_ != 0L, captainid_,
            other.captainid_ != 0L, other.captainid_);
        captainname_ = visitor.visitString(!captainname_.isEmpty(), captainname_,
            !other.captainname_.isEmpty(), other.captainname_);
        lv_ = visitor.visitInt(lv_ != 0, lv_,
            other.lv_ != 0, other.lv_);
        max_ = visitor.visitInt(max_ != 0, max_,
            other.max_ != 0, other.max_);
        num_ = visitor.visitInt(num_ != 0, num_,
            other.num_ != 0, other.num_);
        picurl_ = visitor.visitString(!picurl_.isEmpty(), picurl_,
            !other.picurl_.isEmpty(), other.picurl_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                captainid_ = input.readUInt64();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                captainname_ = s;
                break;
              }
              case 24: {

                lv_ = input.readInt32();
                break;
              }
              case 32: {

                max_ = input.readInt32();
                break;
              }
              case 40: {

                num_ = input.readInt32();
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                picurl_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (Team.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.Team)
  private static final Team DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Team();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static Team getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Team> PARSER;

  public static com.google.protobuf.Parser<Team> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

