// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface TeamInQueueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.TeamInQueue)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string cntoraddr = 1;</code>
   */
  String getCntoraddr();
  /**
   * <code>optional string cntoraddr = 1;</code>
   */
  com.google.protobuf.ByteString
      getCntoraddrBytes();
}
