// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.TeamDone}
 */
public  final class TeamDone extends
    com.google.protobuf.GeneratedMessageLite<
        TeamDone, TeamDone.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.TeamDone)
    TeamDoneOrBuilder {
  private TeamDone() {
    gameaddr_ = "";
    name_ = "";
    mname_ = "";
    downurl_ = "";
  }
  public static final int DONE_FIELD_NUMBER = 1;
  private int done_;
  /**
   * <pre>
   * 0: close 1: done 2: kickout
   * </pre>
   *
   * <code>optional int32 done = 1;</code>
   */
  public int getDone() {
    return done_;
  }
  /**
   * <pre>
   * 0: close 1: done 2: kickout
   * </pre>
   *
   * <code>optional int32 done = 1;</code>
   */
  private void setDone(int value) {
    
    done_ = value;
  }
  /**
   * <pre>
   * 0: close 1: done 2: kickout
   * </pre>
   *
   * <code>optional int32 done = 1;</code>
   */
  private void clearDone() {
    
    done_ = 0;
  }

  public static final int GAMEADDR_FIELD_NUMBER = 2;
  private String gameaddr_;
  /**
   * <pre>
   * game address
   * </pre>
   *
   * <code>optional string gameaddr = 2;</code>
   */
  public String getGameaddr() {
    return gameaddr_;
  }
  /**
   * <pre>
   * game address
   * </pre>
   *
   * <code>optional string gameaddr = 2;</code>
   */
  public com.google.protobuf.ByteString
      getGameaddrBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gameaddr_);
  }
  /**
   * <pre>
   * game address
   * </pre>
   *
   * <code>optional string gameaddr = 2;</code>
   */
  private void setGameaddr(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    gameaddr_ = value;
  }
  /**
   * <pre>
   * game address
   * </pre>
   *
   * <code>optional string gameaddr = 2;</code>
   */
  private void clearGameaddr() {
    
    gameaddr_ = getDefaultInstance().getGameaddr();
  }
  /**
   * <pre>
   * game address
   * </pre>
   *
   * <code>optional string gameaddr = 2;</code>
   */
  private void setGameaddrBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    gameaddr_ = value.toStringUtf8();
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private String name_;
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string name = 3;</code>
   */
  public String getName() {
    return name_;
  }
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string name = 3;</code>
   */
  private void setName(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string name = 3;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string name = 3;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int MNAME_FIELD_NUMBER = 4;
  private String mname_;
  /**
   * <pre>
   * map Name
   * </pre>
   *
   * <code>optional string mname = 4;</code>
   */
  public String getMname() {
    return mname_;
  }
  /**
   * <pre>
   * map Name
   * </pre>
   *
   * <code>optional string mname = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMnameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mname_);
  }
  /**
   * <pre>
   * map Name
   * </pre>
   *
   * <code>optional string mname = 4;</code>
   */
  private void setMname(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mname_ = value;
  }
  /**
   * <pre>
   * map Name
   * </pre>
   *
   * <code>optional string mname = 4;</code>
   */
  private void clearMname() {
    
    mname_ = getDefaultInstance().getMname();
  }
  /**
   * <pre>
   * map Name
   * </pre>
   *
   * <code>optional string mname = 4;</code>
   */
  private void setMnameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mname_ = value.toStringUtf8();
  }

  public static final int DOWNURL_FIELD_NUMBER = 5;
  private String downurl_;
  /**
   * <pre>
   *download map url
   * </pre>
   *
   * <code>optional string downurl = 5;</code>
   */
  public String getDownurl() {
    return downurl_;
  }
  /**
   * <pre>
   *download map url
   * </pre>
   *
   * <code>optional string downurl = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDownurlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(downurl_);
  }
  /**
   * <pre>
   *download map url
   * </pre>
   *
   * <code>optional string downurl = 5;</code>
   */
  private void setDownurl(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    downurl_ = value;
  }
  /**
   * <pre>
   *download map url
   * </pre>
   *
   * <code>optional string downurl = 5;</code>
   */
  private void clearDownurl() {
    
    downurl_ = getDefaultInstance().getDownurl();
  }
  /**
   * <pre>
   *download map url
   * </pre>
   *
   * <code>optional string downurl = 5;</code>
   */
  private void setDownurlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    downurl_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (done_ != 0) {
      output.writeInt32(1, done_);
    }
    if (!gameaddr_.isEmpty()) {
      output.writeString(2, getGameaddr());
    }
    if (!name_.isEmpty()) {
      output.writeString(3, getName());
    }
    if (!mname_.isEmpty()) {
      output.writeString(4, getMname());
    }
    if (!downurl_.isEmpty()) {
      output.writeString(5, getDownurl());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (done_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, done_);
    }
    if (!gameaddr_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getGameaddr());
    }
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getName());
    }
    if (!mname_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getMname());
    }
    if (!downurl_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getDownurl());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static TeamDone parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamDone parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamDone parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamDone parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamDone parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamDone parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamDone parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static TeamDone parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamDone parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamDone parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeamDone prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.TeamDone}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        TeamDone, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.TeamDone)
      TeamDoneOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.TeamDone.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 0: close 1: done 2: kickout
     * </pre>
     *
     * <code>optional int32 done = 1;</code>
     */
    public int getDone() {
      return instance.getDone();
    }
    /**
     * <pre>
     * 0: close 1: done 2: kickout
     * </pre>
     *
     * <code>optional int32 done = 1;</code>
     */
    public Builder setDone(int value) {
      copyOnWrite();
      instance.setDone(value);
      return this;
    }
    /**
     * <pre>
     * 0: close 1: done 2: kickout
     * </pre>
     *
     * <code>optional int32 done = 1;</code>
     */
    public Builder clearDone() {
      copyOnWrite();
      instance.clearDone();
      return this;
    }

    /**
     * <pre>
     * game address
     * </pre>
     *
     * <code>optional string gameaddr = 2;</code>
     */
    public String getGameaddr() {
      return instance.getGameaddr();
    }
    /**
     * <pre>
     * game address
     * </pre>
     *
     * <code>optional string gameaddr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGameaddrBytes() {
      return instance.getGameaddrBytes();
    }
    /**
     * <pre>
     * game address
     * </pre>
     *
     * <code>optional string gameaddr = 2;</code>
     */
    public Builder setGameaddr(
        String value) {
      copyOnWrite();
      instance.setGameaddr(value);
      return this;
    }
    /**
     * <pre>
     * game address
     * </pre>
     *
     * <code>optional string gameaddr = 2;</code>
     */
    public Builder clearGameaddr() {
      copyOnWrite();
      instance.clearGameaddr();
      return this;
    }
    /**
     * <pre>
     * game address
     * </pre>
     *
     * <code>optional string gameaddr = 2;</code>
     */
    public Builder setGameaddrBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGameaddrBytes(value);
      return this;
    }

    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public String getName() {
      return instance.getName();
    }
    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public Builder setName(
        String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <pre>
     * user name
     * </pre>
     *
     * <code>optional string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * map Name
     * </pre>
     *
     * <code>optional string mname = 4;</code>
     */
    public String getMname() {
      return instance.getMname();
    }
    /**
     * <pre>
     * map Name
     * </pre>
     *
     * <code>optional string mname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMnameBytes() {
      return instance.getMnameBytes();
    }
    /**
     * <pre>
     * map Name
     * </pre>
     *
     * <code>optional string mname = 4;</code>
     */
    public Builder setMname(
        String value) {
      copyOnWrite();
      instance.setMname(value);
      return this;
    }
    /**
     * <pre>
     * map Name
     * </pre>
     *
     * <code>optional string mname = 4;</code>
     */
    public Builder clearMname() {
      copyOnWrite();
      instance.clearMname();
      return this;
    }
    /**
     * <pre>
     * map Name
     * </pre>
     *
     * <code>optional string mname = 4;</code>
     */
    public Builder setMnameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMnameBytes(value);
      return this;
    }

    /**
     * <pre>
     *download map url
     * </pre>
     *
     * <code>optional string downurl = 5;</code>
     */
    public String getDownurl() {
      return instance.getDownurl();
    }
    /**
     * <pre>
     *download map url
     * </pre>
     *
     * <code>optional string downurl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDownurlBytes() {
      return instance.getDownurlBytes();
    }
    /**
     * <pre>
     *download map url
     * </pre>
     *
     * <code>optional string downurl = 5;</code>
     */
    public Builder setDownurl(
        String value) {
      copyOnWrite();
      instance.setDownurl(value);
      return this;
    }
    /**
     * <pre>
     *download map url
     * </pre>
     *
     * <code>optional string downurl = 5;</code>
     */
    public Builder clearDownurl() {
      copyOnWrite();
      instance.clearDownurl();
      return this;
    }
    /**
     * <pre>
     *download map url
     * </pre>
     *
     * <code>optional string downurl = 5;</code>
     */
    public Builder setDownurlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDownurlBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.TeamDone)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new TeamDone();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        TeamDone other = (TeamDone) arg1;
        done_ = visitor.visitInt(done_ != 0, done_,
            other.done_ != 0, other.done_);
        gameaddr_ = visitor.visitString(!gameaddr_.isEmpty(), gameaddr_,
            !other.gameaddr_.isEmpty(), other.gameaddr_);
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        mname_ = visitor.visitString(!mname_.isEmpty(), mname_,
            !other.mname_.isEmpty(), other.mname_);
        downurl_ = visitor.visitString(!downurl_.isEmpty(), downurl_,
            !other.downurl_.isEmpty(), other.downurl_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                done_ = input.readInt32();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                gameaddr_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                mname_ = s;
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                downurl_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (TeamDone.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.TeamDone)
  private static final TeamDone DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeamDone();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static TeamDone getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TeamDone> PARSER;

  public static com.google.protobuf.Parser<TeamDone> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

