// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.TeamRequest}
 */
public  final class TeamRequest extends
    com.google.protobuf.GeneratedMessageLite<
        TeamRequest, TeamRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.TeamRequest)
    TeamRequestOrBuilder {
  private TeamRequest() {
  }
  private int operateCase_ = 0;
  private Object operate_;
  public enum OperateCase
      implements com.google.protobuf.Internal.EnumLite {
    CREATE(1),
    JOIN(2),
    QUEUE(3),
    REMOVE(4),
    OPERATE_NOT_SET(0);
    private final int value;
    private OperateCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static OperateCase valueOf(int value) {
      return forNumber(value);
    }

    public static OperateCase forNumber(int value) {
      switch (value) {
        case 1: return CREATE;
        case 2: return JOIN;
        case 3: return QUEUE;
        case 4: return REMOVE;
        case 0: return OPERATE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OperateCase
  getOperateCase() {
    return OperateCase.forNumber(
        operateCase_);
  }

  private void clearOperate() {
    operateCase_ = 0;
    operate_ = null;
  }

  public static final int CREATE_FIELD_NUMBER = 1;
  /**
   * <code>optional .teammgr.TeamCreate create = 1;</code>
   */
  public TeamCreate getCreate() {
    if (operateCase_ == 1) {
       return (TeamCreate) operate_;
    }
    return TeamCreate.getDefaultInstance();
  }
  /**
   * <code>optional .teammgr.TeamCreate create = 1;</code>
   */
  private void setCreate(TeamCreate value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 1;
  }
  /**
   * <code>optional .teammgr.TeamCreate create = 1;</code>
   */
  private void setCreate(
      TeamCreate.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 1;
  }
  /**
   * <code>optional .teammgr.TeamCreate create = 1;</code>
   */
  private void mergeCreate(TeamCreate value) {
    if (operateCase_ == 1 &&
        operate_ != TeamCreate.getDefaultInstance()) {
      operate_ = TeamCreate.newBuilder((TeamCreate) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 1;
  }
  /**
   * <code>optional .teammgr.TeamCreate create = 1;</code>
   */
  private void clearCreate() {
    if (operateCase_ == 1) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public static final int JOIN_FIELD_NUMBER = 2;
  /**
   * <code>optional .teammgr.TeamJoin join = 2;</code>
   */
  public TeamJoin getJoin() {
    if (operateCase_ == 2) {
       return (TeamJoin) operate_;
    }
    return TeamJoin.getDefaultInstance();
  }
  /**
   * <code>optional .teammgr.TeamJoin join = 2;</code>
   */
  private void setJoin(TeamJoin value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 2;
  }
  /**
   * <code>optional .teammgr.TeamJoin join = 2;</code>
   */
  private void setJoin(
      TeamJoin.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 2;
  }
  /**
   * <code>optional .teammgr.TeamJoin join = 2;</code>
   */
  private void mergeJoin(TeamJoin value) {
    if (operateCase_ == 2 &&
        operate_ != TeamJoin.getDefaultInstance()) {
      operate_ = TeamJoin.newBuilder((TeamJoin) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 2;
  }
  /**
   * <code>optional .teammgr.TeamJoin join = 2;</code>
   */
  private void clearJoin() {
    if (operateCase_ == 2) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public static final int QUEUE_FIELD_NUMBER = 3;
  /**
   * <code>optional .teammgr.TeamInQueue queue = 3;</code>
   */
  public TeamInQueue getQueue() {
    if (operateCase_ == 3) {
       return (TeamInQueue) operate_;
    }
    return TeamInQueue.getDefaultInstance();
  }
  /**
   * <code>optional .teammgr.TeamInQueue queue = 3;</code>
   */
  private void setQueue(TeamInQueue value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 3;
  }
  /**
   * <code>optional .teammgr.TeamInQueue queue = 3;</code>
   */
  private void setQueue(
      TeamInQueue.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 3;
  }
  /**
   * <code>optional .teammgr.TeamInQueue queue = 3;</code>
   */
  private void mergeQueue(TeamInQueue value) {
    if (operateCase_ == 3 &&
        operate_ != TeamInQueue.getDefaultInstance()) {
      operate_ = TeamInQueue.newBuilder((TeamInQueue) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 3;
  }
  /**
   * <code>optional .teammgr.TeamInQueue queue = 3;</code>
   */
  private void clearQueue() {
    if (operateCase_ == 3) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public static final int REMOVE_FIELD_NUMBER = 4;
  /**
   * <code>optional .teammgr.RemoveMember remove = 4;</code>
   */
  public RemoveMember getRemove() {
    if (operateCase_ == 4) {
       return (RemoveMember) operate_;
    }
    return RemoveMember.getDefaultInstance();
  }
  /**
   * <code>optional .teammgr.RemoveMember remove = 4;</code>
   */
  private void setRemove(RemoveMember value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 4;
  }
  /**
   * <code>optional .teammgr.RemoveMember remove = 4;</code>
   */
  private void setRemove(
      RemoveMember.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 4;
  }
  /**
   * <code>optional .teammgr.RemoveMember remove = 4;</code>
   */
  private void mergeRemove(RemoveMember value) {
    if (operateCase_ == 4 &&
        operate_ != RemoveMember.getDefaultInstance()) {
      operate_ = RemoveMember.newBuilder((RemoveMember) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 4;
  }
  /**
   * <code>optional .teammgr.RemoveMember remove = 4;</code>
   */
  private void clearRemove() {
    if (operateCase_ == 4) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (operateCase_ == 1) {
      output.writeMessage(1, (TeamCreate) operate_);
    }
    if (operateCase_ == 2) {
      output.writeMessage(2, (TeamJoin) operate_);
    }
    if (operateCase_ == 3) {
      output.writeMessage(3, (TeamInQueue) operate_);
    }
    if (operateCase_ == 4) {
      output.writeMessage(4, (RemoveMember) operate_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (operateCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (TeamCreate) operate_);
    }
    if (operateCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (TeamJoin) operate_);
    }
    if (operateCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (TeamInQueue) operate_);
    }
    if (operateCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (RemoveMember) operate_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static TeamRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static TeamRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeamRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.TeamRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        TeamRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.TeamRequest)
      TeamRequestOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.TeamRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public OperateCase
        getOperateCase() {
      return instance.getOperateCase();
    }

    public Builder clearOperate() {
      copyOnWrite();
      instance.clearOperate();
      return this;
    }


    /**
     * <code>optional .teammgr.TeamCreate create = 1;</code>
     */
    public TeamCreate getCreate() {
      return instance.getCreate();
    }
    /**
     * <code>optional .teammgr.TeamCreate create = 1;</code>
     */
    public Builder setCreate(TeamCreate value) {
      copyOnWrite();
      instance.setCreate(value);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamCreate create = 1;</code>
     */
    public Builder setCreate(
        TeamCreate.Builder builderForValue) {
      copyOnWrite();
      instance.setCreate(builderForValue);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamCreate create = 1;</code>
     */
    public Builder mergeCreate(TeamCreate value) {
      copyOnWrite();
      instance.mergeCreate(value);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamCreate create = 1;</code>
     */
    public Builder clearCreate() {
      copyOnWrite();
      instance.clearCreate();
      return this;
    }

    /**
     * <code>optional .teammgr.TeamJoin join = 2;</code>
     */
    public TeamJoin getJoin() {
      return instance.getJoin();
    }
    /**
     * <code>optional .teammgr.TeamJoin join = 2;</code>
     */
    public Builder setJoin(TeamJoin value) {
      copyOnWrite();
      instance.setJoin(value);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamJoin join = 2;</code>
     */
    public Builder setJoin(
        TeamJoin.Builder builderForValue) {
      copyOnWrite();
      instance.setJoin(builderForValue);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamJoin join = 2;</code>
     */
    public Builder mergeJoin(TeamJoin value) {
      copyOnWrite();
      instance.mergeJoin(value);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamJoin join = 2;</code>
     */
    public Builder clearJoin() {
      copyOnWrite();
      instance.clearJoin();
      return this;
    }

    /**
     * <code>optional .teammgr.TeamInQueue queue = 3;</code>
     */
    public TeamInQueue getQueue() {
      return instance.getQueue();
    }
    /**
     * <code>optional .teammgr.TeamInQueue queue = 3;</code>
     */
    public Builder setQueue(TeamInQueue value) {
      copyOnWrite();
      instance.setQueue(value);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamInQueue queue = 3;</code>
     */
    public Builder setQueue(
        TeamInQueue.Builder builderForValue) {
      copyOnWrite();
      instance.setQueue(builderForValue);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamInQueue queue = 3;</code>
     */
    public Builder mergeQueue(TeamInQueue value) {
      copyOnWrite();
      instance.mergeQueue(value);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamInQueue queue = 3;</code>
     */
    public Builder clearQueue() {
      copyOnWrite();
      instance.clearQueue();
      return this;
    }

    /**
     * <code>optional .teammgr.RemoveMember remove = 4;</code>
     */
    public RemoveMember getRemove() {
      return instance.getRemove();
    }
    /**
     * <code>optional .teammgr.RemoveMember remove = 4;</code>
     */
    public Builder setRemove(RemoveMember value) {
      copyOnWrite();
      instance.setRemove(value);
      return this;
    }
    /**
     * <code>optional .teammgr.RemoveMember remove = 4;</code>
     */
    public Builder setRemove(
        RemoveMember.Builder builderForValue) {
      copyOnWrite();
      instance.setRemove(builderForValue);
      return this;
    }
    /**
     * <code>optional .teammgr.RemoveMember remove = 4;</code>
     */
    public Builder mergeRemove(RemoveMember value) {
      copyOnWrite();
      instance.mergeRemove(value);
      return this;
    }
    /**
     * <code>optional .teammgr.RemoveMember remove = 4;</code>
     */
    public Builder clearRemove() {
      copyOnWrite();
      instance.clearRemove();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.TeamRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new TeamRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        TeamRequest other = (TeamRequest) arg1;
        switch (other.getOperateCase()) {
          case CREATE: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 1,
                operate_,
                other.operate_);
            break;
          }
          case JOIN: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 2,
                operate_,
                other.operate_);
            break;
          }
          case QUEUE: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 3,
                operate_,
                other.operate_);
            break;
          }
          case REMOVE: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 4,
                operate_,
                other.operate_);
            break;
          }
          case OPERATE_NOT_SET: {
            visitor.visitOneofNotSet(operateCase_ != 0);
            break;
          }
        }
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          if (other.operateCase_ != 0) {
            operateCase_ = other.operateCase_;
          }
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                TeamCreate.Builder subBuilder = null;
                if (operateCase_ == 1) {
                  subBuilder = ((TeamCreate) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(TeamCreate.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((TeamCreate) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 1;
                break;
              }
              case 18: {
                TeamJoin.Builder subBuilder = null;
                if (operateCase_ == 2) {
                  subBuilder = ((TeamJoin) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(TeamJoin.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((TeamJoin) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 2;
                break;
              }
              case 26: {
                TeamInQueue.Builder subBuilder = null;
                if (operateCase_ == 3) {
                  subBuilder = ((TeamInQueue) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(TeamInQueue.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((TeamInQueue) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 3;
                break;
              }
              case 34: {
                RemoveMember.Builder subBuilder = null;
                if (operateCase_ == 4) {
                  subBuilder = ((RemoveMember) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(RemoveMember.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((RemoveMember) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 4;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (TeamRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.TeamRequest)
  private static final TeamRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeamRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static TeamRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TeamRequest> PARSER;

  public static com.google.protobuf.Parser<TeamRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

