// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.TeamJoin}
 */
public  final class TeamJoin extends
    com.google.protobuf.GeneratedMessageLite<
        TeamJoin, TeamJoin.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.TeamJoin)
    TeamJoinOrBuilder {
  private TeamJoin() {
    gametype_ = "";
  }
  public static final int GAMETYPE_FIELD_NUMBER = 1;
  private String gametype_;
  /**
   * <code>optional string gametype = 1;</code>
   */
  public String getGametype() {
    return gametype_;
  }
  /**
   * <code>optional string gametype = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGametypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gametype_);
  }
  /**
   * <code>optional string gametype = 1;</code>
   */
  private void setGametype(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    gametype_ = value;
  }
  /**
   * <code>optional string gametype = 1;</code>
   */
  private void clearGametype() {
    
    gametype_ = getDefaultInstance().getGametype();
  }
  /**
   * <code>optional string gametype = 1;</code>
   */
  private void setGametypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    gametype_ = value.toStringUtf8();
  }

  public static final int CAPTAINID_FIELD_NUMBER = 2;
  private long captainid_;
  /**
   * <pre>
   * captain id
   * </pre>
   *
   * <code>optional uint64 captainid = 2;</code>
   */
  public long getCaptainid() {
    return captainid_;
  }
  /**
   * <pre>
   * captain id
   * </pre>
   *
   * <code>optional uint64 captainid = 2;</code>
   */
  private void setCaptainid(long value) {
    
    captainid_ = value;
  }
  /**
   * <pre>
   * captain id
   * </pre>
   *
   * <code>optional uint64 captainid = 2;</code>
   */
  private void clearCaptainid() {
    
    captainid_ = 0L;
  }

  public static final int USER_FIELD_NUMBER = 3;
  private TeamMember user_;
  /**
   * <code>optional .teammgr.TeamMember user = 3;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>optional .teammgr.TeamMember user = 3;</code>
   */
  public TeamMember getUser() {
    return user_ == null ? TeamMember.getDefaultInstance() : user_;
  }
  /**
   * <code>optional .teammgr.TeamMember user = 3;</code>
   */
  private void setUser(TeamMember value) {
    if (value == null) {
      throw new NullPointerException();
    }
    user_ = value;
    
    }
  /**
   * <code>optional .teammgr.TeamMember user = 3;</code>
   */
  private void setUser(
      TeamMember.Builder builderForValue) {
    user_ = builderForValue.build();
    
  }
  /**
   * <code>optional .teammgr.TeamMember user = 3;</code>
   */
  private void mergeUser(TeamMember value) {
    if (user_ != null &&
        user_ != TeamMember.getDefaultInstance()) {
      user_ =
        TeamMember.newBuilder(user_).mergeFrom(value).buildPartial();
    } else {
      user_ = value;
    }
    
  }
  /**
   * <code>optional .teammgr.TeamMember user = 3;</code>
   */
  private void clearUser() {  user_ = null;
    
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!gametype_.isEmpty()) {
      output.writeString(1, getGametype());
    }
    if (captainid_ != 0L) {
      output.writeUInt64(2, captainid_);
    }
    if (user_ != null) {
      output.writeMessage(3, getUser());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!gametype_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getGametype());
    }
    if (captainid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, captainid_);
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUser());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static TeamJoin parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamJoin parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamJoin parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamJoin parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamJoin parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamJoin parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamJoin parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static TeamJoin parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamJoin parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamJoin parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeamJoin prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.TeamJoin}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        TeamJoin, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.TeamJoin)
      TeamJoinOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.TeamJoin.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string gametype = 1;</code>
     */
    public String getGametype() {
      return instance.getGametype();
    }
    /**
     * <code>optional string gametype = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGametypeBytes() {
      return instance.getGametypeBytes();
    }
    /**
     * <code>optional string gametype = 1;</code>
     */
    public Builder setGametype(
        String value) {
      copyOnWrite();
      instance.setGametype(value);
      return this;
    }
    /**
     * <code>optional string gametype = 1;</code>
     */
    public Builder clearGametype() {
      copyOnWrite();
      instance.clearGametype();
      return this;
    }
    /**
     * <code>optional string gametype = 1;</code>
     */
    public Builder setGametypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGametypeBytes(value);
      return this;
    }

    /**
     * <pre>
     * captain id
     * </pre>
     *
     * <code>optional uint64 captainid = 2;</code>
     */
    public long getCaptainid() {
      return instance.getCaptainid();
    }
    /**
     * <pre>
     * captain id
     * </pre>
     *
     * <code>optional uint64 captainid = 2;</code>
     */
    public Builder setCaptainid(long value) {
      copyOnWrite();
      instance.setCaptainid(value);
      return this;
    }
    /**
     * <pre>
     * captain id
     * </pre>
     *
     * <code>optional uint64 captainid = 2;</code>
     */
    public Builder clearCaptainid() {
      copyOnWrite();
      instance.clearCaptainid();
      return this;
    }

    /**
     * <code>optional .teammgr.TeamMember user = 3;</code>
     */
    public boolean hasUser() {
      return instance.hasUser();
    }
    /**
     * <code>optional .teammgr.TeamMember user = 3;</code>
     */
    public TeamMember getUser() {
      return instance.getUser();
    }
    /**
     * <code>optional .teammgr.TeamMember user = 3;</code>
     */
    public Builder setUser(TeamMember value) {
      copyOnWrite();
      instance.setUser(value);
      return this;
      }
    /**
     * <code>optional .teammgr.TeamMember user = 3;</code>
     */
    public Builder setUser(
        TeamMember.Builder builderForValue) {
      copyOnWrite();
      instance.setUser(builderForValue);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamMember user = 3;</code>
     */
    public Builder mergeUser(TeamMember value) {
      copyOnWrite();
      instance.mergeUser(value);
      return this;
    }
    /**
     * <code>optional .teammgr.TeamMember user = 3;</code>
     */
    public Builder clearUser() {  copyOnWrite();
      instance.clearUser();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.TeamJoin)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new TeamJoin();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        TeamJoin other = (TeamJoin) arg1;
        gametype_ = visitor.visitString(!gametype_.isEmpty(), gametype_,
            !other.gametype_.isEmpty(), other.gametype_);
        captainid_ = visitor.visitLong(captainid_ != 0L, captainid_,
            other.captainid_ != 0L, other.captainid_);
        user_ = visitor.visitMessage(user_, other.user_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                gametype_ = s;
                break;
              }
              case 16: {

                captainid_ = input.readUInt64();
                break;
              }
              case 26: {
                TeamMember.Builder subBuilder = null;
                if (user_ != null) {
                  subBuilder = user_.toBuilder();
                }
                user_ = input.readMessage(TeamMember.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(user_);
                  user_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (TeamJoin.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.TeamJoin)
  private static final TeamJoin DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeamJoin();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static TeamJoin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TeamJoin> PARSER;

  public static com.google.protobuf.Parser<TeamJoin> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

