// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

/**
 * Protobuf type {@code teammgr.TeamInQueue}
 */
public  final class TeamInQueue extends
    com.google.protobuf.GeneratedMessageLite<
        TeamInQueue, TeamInQueue.Builder> implements
    // @@protoc_insertion_point(message_implements:teammgr.TeamInQueue)
    TeamInQueueOrBuilder {
  private TeamInQueue() {
    cntoraddr_ = "";
  }
  public static final int CNTORADDR_FIELD_NUMBER = 1;
  private String cntoraddr_;
  /**
   * <code>optional string cntoraddr = 1;</code>
   */
  public String getCntoraddr() {
    return cntoraddr_;
  }
  /**
   * <code>optional string cntoraddr = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCntoraddrBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(cntoraddr_);
  }
  /**
   * <code>optional string cntoraddr = 1;</code>
   */
  private void setCntoraddr(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    cntoraddr_ = value;
  }
  /**
   * <code>optional string cntoraddr = 1;</code>
   */
  private void clearCntoraddr() {
    
    cntoraddr_ = getDefaultInstance().getCntoraddr();
  }
  /**
   * <code>optional string cntoraddr = 1;</code>
   */
  private void setCntoraddrBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    cntoraddr_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!cntoraddr_.isEmpty()) {
      output.writeString(1, getCntoraddr());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!cntoraddr_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getCntoraddr());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static TeamInQueue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamInQueue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamInQueue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamInQueue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamInQueue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamInQueue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamInQueue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static TeamInQueue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamInQueue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamInQueue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeamInQueue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code teammgr.TeamInQueue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        TeamInQueue, Builder> implements
      // @@protoc_insertion_point(builder_implements:teammgr.TeamInQueue)
      TeamInQueueOrBuilder {
    // Construct using com.sandboxol.mgs.teammgr.TeamInQueue.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string cntoraddr = 1;</code>
     */
    public String getCntoraddr() {
      return instance.getCntoraddr();
    }
    /**
     * <code>optional string cntoraddr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCntoraddrBytes() {
      return instance.getCntoraddrBytes();
    }
    /**
     * <code>optional string cntoraddr = 1;</code>
     */
    public Builder setCntoraddr(
        String value) {
      copyOnWrite();
      instance.setCntoraddr(value);
      return this;
    }
    /**
     * <code>optional string cntoraddr = 1;</code>
     */
    public Builder clearCntoraddr() {
      copyOnWrite();
      instance.clearCntoraddr();
      return this;
    }
    /**
     * <code>optional string cntoraddr = 1;</code>
     */
    public Builder setCntoraddrBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCntoraddrBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:teammgr.TeamInQueue)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new TeamInQueue();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        TeamInQueue other = (TeamInQueue) arg1;
        cntoraddr_ = visitor.visitString(!cntoraddr_.isEmpty(), cntoraddr_,
            !other.cntoraddr_.isEmpty(), other.cntoraddr_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                cntoraddr_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (TeamInQueue.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:teammgr.TeamInQueue)
  private static final TeamInQueue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeamInQueue();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static TeamInQueue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TeamInQueue> PARSER;

  public static com.google.protobuf.Parser<TeamInQueue> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

