// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface TeamMemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.TeamMember)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * user id
   * </pre>
   *
   * <code>optional uint64 userid = 1;</code>
   */
  long getUserid();

  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  String getUsername();
  /**
   * <pre>
   * user name
   * </pre>
   *
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * user level
   * </pre>
   *
   * <code>optional int32 lv = 3;</code>
   */
  int getLv();

  /**
   * <pre>
   * user class
   * </pre>
   *
   * <code>optional int32 clazz = 4;</code>
   */
  int getClazz();

  /**
   * <pre>
   * is captain
   * </pre>
   *
   * <code>optional bool isCaptain = 5;</code>
   */
  boolean getIsCaptain();

  /**
   * <pre>
   * picture url
   * </pre>
   *
   * <code>optional string picurl = 6;</code>
   */
  String getPicurl();
  /**
   * <pre>
   * picture url
   * </pre>
   *
   * <code>optional string picurl = 6;</code>
   */
  com.google.protobuf.ByteString
      getPicurlBytes();
}
