// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface TeamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.TeamRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .teammgr.TeamCreate create = 1;</code>
   */
  TeamCreate getCreate();

  /**
   * <code>optional .teammgr.TeamJoin join = 2;</code>
   */
  TeamJoin getJoin();

  /**
   * <code>optional .teammgr.TeamInQueue queue = 3;</code>
   */
  TeamInQueue getQueue();

  /**
   * <code>optional .teammgr.RemoveMember remove = 4;</code>
   */
  RemoveMember getRemove();

  public TeamRequest.OperateCase getOperateCase();
}
