// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface TeamCreateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.TeamCreate)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string gametype = 1;</code>
   */
  String getGametype();
  /**
   * <code>optional string gametype = 1;</code>
   */
  com.google.protobuf.ByteString
      getGametypeBytes();

  /**
   * <code>optional .teammgr.TeamMember captain = 2;</code>
   */
  boolean hasCaptain();
  /**
   * <code>optional .teammgr.TeamMember captain = 2;</code>
   */
  TeamMember getCaptain();

  /**
   * <code>optional int64 regionid = 3;</code>
   */
  long getRegionid();
}
