// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface TeamJoinOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.TeamJoin)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string gametype = 1;</code>
   */
  String getGametype();
  /**
   * <code>optional string gametype = 1;</code>
   */
  com.google.protobuf.ByteString
      getGametypeBytes();

  /**
   * <pre>
   * captain id
   * </pre>
   *
   * <code>optional uint64 captainid = 2;</code>
   */
  long getCaptainid();

  /**
   * <code>optional .teammgr.TeamMember user = 3;</code>
   */
  boolean hasUser();
  /**
   * <code>optional .teammgr.TeamMember user = 3;</code>
   */
  TeamMember getUser();
}
