// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pteammgr.proto

package com.sandboxol.mgs.teammgr;

public interface UpdateLocalTeamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teammgr.UpdateLocalTeams)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  java.util.List<Team>
      getTeamsList();
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  Team getTeams(int index);
  /**
   * <code>repeated .teammgr.Team teams = 1;</code>
   */
  int getTeamsCount();
}
