package com.sandboxol.blockymods.config;

/**
 * Created by Bob on 2017/10/18.
 */
public interface IntConstant {

    int CHANGE_ACCOUNT_LOGIN = 0;
    int CHANGE_ACCOUNT_REGISTER = 1;
    int CHANGE_ACCOUNT_REGISTER_DETAIL = 2;

    int SEX_BOY = 1;
    int SEX_GIRL = 2;

    int UPLOAD_ICON_SELECT_ICON = 1;
    int UPLOAD_ICON_CROP_ICON = 2;

    int ACCOUNT_LOGIN = 1;
    int ACCOUNT_REGISTER = 2;
    int ACCOUNT_LOGOUT = 3;
    int UPDATE_USER_INFO = 4;

    int REGISTER_SUCCESS_DIALOG = 1;

    int LOGIN_SUCCESS = 1;
    int REGISTER_SUCCESS = 2;

    int RECOMMEND_SHOW_RECENTLY_VIEW = 1;
    int RECOMMEND_SHOW_FRIEND_VIEW = 2;

    int RECOMMEND_REFRESH_LATELY_TYPE = 1;

    int GAME_TYPE_ALL = 0;
    int GAME_TYPE_PVP = 1;
    int GAME_TYPE_BUSINESS = 2;
    int GAME_TYPE_ADVENTURE = 3;
    int GAME_TYPE_SHOOTOUT = 4;

    int DRESS_TYPE_NORMAL = 0;
    int DRESS_TYPE_CLOTH = 1;
    int DRESS_TYPE_ORNAMENTS = 2;

    int DECORATION_LOADING = 1;
    int DECORATION_FINISH = 2;

    long DECORATION_TYPE_HAIR = 2;
    long DECORATION_TYPE_EMOTION = 4;
    long DECORATION_TYPE_TOPS = 8;
    long DECORATION_TYPE_PANTS = 9;
    long DECORATION_TYPE_SHOES = 10;
    long DECORATION_TYPE_HAT = 11;
    long DECORATION_TYPE_FACE = 12;
    long DECORATION_TYPE_SHOULDER = 13;
    long DECORATION_TYPE_BACK = 14;

}
