- name: deploy collectlog node
  hosts: "{{ service }}"
  remote_user: ubuntu
  become: true
  vars:
    logcollect_binary: 'logtail.sh'
    logcollect_binary_dest: '/home/ubuntu/logtail.sh'
    collectlog_region: "{{ collectlog_region }}"
    machine_id: "{{ machine_id }}"
    aliyun_uid: "{{ aliyun_uid }}"
    clean_ilogtail_log_file: 'clean_ilogtail_log.sh'
    clean_ilogtail_log_dest: '/home/ubuntu/clean_ilogtail_log.sh'


  tasks:
  - name: copy the binary to {{ logcollect_binary_dest }}
    copy:
      src: "./files/{{ logcollect_binary }}"
      dest: "{{ logcollect_binary_dest }}"
      mode: 0755

  - name: install the logcollect conf to {{ collectlog_region }}
    shell: "{{ logcollect_binary_dest }} install {{ collectlog_region }}"

  - name: create aliyun uid
    file:
      path: "/etc/ilogtail/users/{{ aliyun_uid }}"
      state: touch

  - name: create machine id
    shell: "echo {{ machine_id }} >/etc/ilogtail/user_defined_id"

  - name: copy clean_ilogtail_log
    copy:
      src: "./files/{{ clean_ilogtail_log_file }}"
      dest: "{{ clean_ilogtail_log_dest }}"
      mode: 0755

  - name: create clean ilogtail log job.
    cron:
      name: clean_ilogtail_log key
      job: '/bin/sh {{ clean_ilogtail_log_dest }} 30'
      minute: "0"
      hour: "0"
      day: "*"
      month: "*"
      weekday: "*"
      state: present