- name: deploy collectlog node
  hosts: "{{ service }}"
  remote_user: ubuntu
  become: true
  vars:
    watch_dir: /home/deploy/logs/supervisor

  tasks:
  - file: path=./logs state=directory mode=755
  - template: src=./files/watch_log.py dest=./watch_log.py
  - template: src=./files/watchlog.ini.j2 dest=/etc/supervisor/conf.d/watchlog.ini

  - name: install python module - requests
    pip:
      name: requests

  - name: start watchlog
    supervisorctl: |
      name="watchlog"
      state=present
    when: perform == 'start'

  - name: start watchlog
    supervisorctl: |
      name="watchlog"
      state=stopped
    when: perform == 'stop'

  - name: start watchlog
    supervisorctl: |
      name="watchlog"
      state=restarted
    when: perform == 'restart'
    