// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

public interface CloseResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.CloseResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * success: 1
   * </pre>
   *
   * <code>optional int32 code = 1;</code>
   */
  int getCode();
}
