// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

public interface EnterResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.EnterResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * success: 1, not exist: 2, full: 3, team full: 4
   * </pre>
   *
   * <code>optional int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional string name = 2;</code>
   */
  String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string gameaddr = 3;</code>
   */
  String getGameaddr();
  /**
   * <code>optional string gameaddr = 3;</code>
   */
  com.google.protobuf.ByteString
      getGameaddrBytes();

  /**
   * <code>optional string mname = 4;</code>
   */
  String getMname();
  /**
   * <code>optional string mname = 4;</code>
   */
  com.google.protobuf.ByteString
      getMnameBytes();

  /**
   * <code>optional string downurl = 5;</code>
   */
  String getDownurl();
  /**
   * <code>optional string downurl = 5;</code>
   */
  com.google.protobuf.ByteString
      getDownurlBytes();
}
