// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

/**
 * Protobuf type {@code dispatcher.EnterServer}
 */
public  final class EnterServer extends
    com.google.protobuf.GeneratedMessageLite<
        EnterServer, EnterServer.Builder> implements
    // @@protoc_insertion_point(message_implements:dispatcher.EnterServer)
    EnterServerOrBuilder {
  private EnterServer() {
    username_ = "";
    serverid_ = "";
  }
  public static final int USERID_FIELD_NUMBER = 1;
  private long userid_;
  /**
   * <code>optional int64 userid = 1;</code>
   */
  public long getUserid() {
    return userid_;
  }
  /**
   * <code>optional int64 userid = 1;</code>
   */
  private void setUserid(long value) {
    
    userid_ = value;
  }
  /**
   * <code>optional int64 userid = 1;</code>
   */
  private void clearUserid() {
    
    userid_ = 0L;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private String username_;
  /**
   * <code>optional string username = 2;</code>
   */
  public String getUsername() {
    return username_;
  }
  /**
   * <code>optional string username = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>optional string username = 2;</code>
   */
  private void setUsername(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    username_ = value;
  }
  /**
   * <code>optional string username = 2;</code>
   */
  private void clearUsername() {
    
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>optional string username = 2;</code>
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    username_ = value.toStringUtf8();
  }

  public static final int SERVERID_FIELD_NUMBER = 3;
  private String serverid_;
  /**
   * <code>optional string serverid = 3;</code>
   */
  public String getServerid() {
    return serverid_;
  }
  /**
   * <code>optional string serverid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getServeridBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serverid_);
  }
  /**
   * <code>optional string serverid = 3;</code>
   */
  private void setServerid(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    serverid_ = value;
  }
  /**
   * <code>optional string serverid = 3;</code>
   */
  private void clearServerid() {
    
    serverid_ = getDefaultInstance().getServerid();
  }
  /**
   * <code>optional string serverid = 3;</code>
   */
  private void setServeridBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    serverid_ = value.toStringUtf8();
  }

  public static final int REGIONID_FIELD_NUMBER = 4;
  private int regionid_;
  /**
   * <code>optional int32 regionid = 4;</code>
   */
  public int getRegionid() {
    return regionid_;
  }
  /**
   * <code>optional int32 regionid = 4;</code>
   */
  private void setRegionid(int value) {
    
    regionid_ = value;
  }
  /**
   * <code>optional int32 regionid = 4;</code>
   */
  private void clearRegionid() {
    
    regionid_ = 0;
  }

  public static final int CLAZZ_FIELD_NUMBER = 5;
  private int clazz_;
  /**
   * <code>optional int32 clazz = 5;</code>
   */
  public int getClazz() {
    return clazz_;
  }
  /**
   * <code>optional int32 clazz = 5;</code>
   */
  private void setClazz(int value) {
    
    clazz_ = value;
  }
  /**
   * <code>optional int32 clazz = 5;</code>
   */
  private void clearClazz() {
    
    clazz_ = 0;
  }

  public static final int CLANID_FIELD_NUMBER = 6;
  private long clanid_;
  /**
   * <code>optional int64 clanid = 6;</code>
   */
  public long getClanid() {
    return clanid_;
  }
  /**
   * <code>optional int64 clanid = 6;</code>
   */
  private void setClanid(long value) {
    
    clanid_ = value;
  }
  /**
   * <code>optional int64 clanid = 6;</code>
   */
  private void clearClanid() {
    
    clanid_ = 0L;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userid_ != 0L) {
      output.writeInt64(1, userid_);
    }
    if (!username_.isEmpty()) {
      output.writeString(2, getUsername());
    }
    if (!serverid_.isEmpty()) {
      output.writeString(3, getServerid());
    }
    if (regionid_ != 0) {
      output.writeInt32(4, regionid_);
    }
    if (clazz_ != 0) {
      output.writeInt32(5, clazz_);
    }
    if (clanid_ != 0L) {
      output.writeInt64(6, clanid_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (userid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userid_);
    }
    if (!username_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getUsername());
    }
    if (!serverid_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getServerid());
    }
    if (regionid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, regionid_);
    }
    if (clazz_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, clazz_);
    }
    if (clanid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, clanid_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static EnterServer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static EnterServer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static EnterServer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static EnterServer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static EnterServer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static EnterServer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static EnterServer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static EnterServer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static EnterServer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static EnterServer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EnterServer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code dispatcher.EnterServer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        EnterServer, Builder> implements
      // @@protoc_insertion_point(builder_implements:dispatcher.EnterServer)
      EnterServerOrBuilder {
    // Construct using com.sandboxol.clw.dispatcher.EnterServer.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int64 userid = 1;</code>
     */
    public long getUserid() {
      return instance.getUserid();
    }
    /**
     * <code>optional int64 userid = 1;</code>
     */
    public Builder setUserid(long value) {
      copyOnWrite();
      instance.setUserid(value);
      return this;
    }
    /**
     * <code>optional int64 userid = 1;</code>
     */
    public Builder clearUserid() {
      copyOnWrite();
      instance.clearUserid();
      return this;
    }

    /**
     * <code>optional string username = 2;</code>
     */
    public String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder setUsername(
        String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>optional string serverid = 3;</code>
     */
    public String getServerid() {
      return instance.getServerid();
    }
    /**
     * <code>optional string serverid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServeridBytes() {
      return instance.getServeridBytes();
    }
    /**
     * <code>optional string serverid = 3;</code>
     */
    public Builder setServerid(
        String value) {
      copyOnWrite();
      instance.setServerid(value);
      return this;
    }
    /**
     * <code>optional string serverid = 3;</code>
     */
    public Builder clearServerid() {
      copyOnWrite();
      instance.clearServerid();
      return this;
    }
    /**
     * <code>optional string serverid = 3;</code>
     */
    public Builder setServeridBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServeridBytes(value);
      return this;
    }

    /**
     * <code>optional int32 regionid = 4;</code>
     */
    public int getRegionid() {
      return instance.getRegionid();
    }
    /**
     * <code>optional int32 regionid = 4;</code>
     */
    public Builder setRegionid(int value) {
      copyOnWrite();
      instance.setRegionid(value);
      return this;
    }
    /**
     * <code>optional int32 regionid = 4;</code>
     */
    public Builder clearRegionid() {
      copyOnWrite();
      instance.clearRegionid();
      return this;
    }

    /**
     * <code>optional int32 clazz = 5;</code>
     */
    public int getClazz() {
      return instance.getClazz();
    }
    /**
     * <code>optional int32 clazz = 5;</code>
     */
    public Builder setClazz(int value) {
      copyOnWrite();
      instance.setClazz(value);
      return this;
    }
    /**
     * <code>optional int32 clazz = 5;</code>
     */
    public Builder clearClazz() {
      copyOnWrite();
      instance.clearClazz();
      return this;
    }

    /**
     * <code>optional int64 clanid = 6;</code>
     */
    public long getClanid() {
      return instance.getClanid();
    }
    /**
     * <code>optional int64 clanid = 6;</code>
     */
    public Builder setClanid(long value) {
      copyOnWrite();
      instance.setClanid(value);
      return this;
    }
    /**
     * <code>optional int64 clanid = 6;</code>
     */
    public Builder clearClanid() {
      copyOnWrite();
      instance.clearClanid();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dispatcher.EnterServer)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new EnterServer();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        EnterServer other = (EnterServer) arg1;
        userid_ = visitor.visitLong(userid_ != 0L, userid_,
            other.userid_ != 0L, other.userid_);
        username_ = visitor.visitString(!username_.isEmpty(), username_,
            !other.username_.isEmpty(), other.username_);
        serverid_ = visitor.visitString(!serverid_.isEmpty(), serverid_,
            !other.serverid_.isEmpty(), other.serverid_);
        regionid_ = visitor.visitInt(regionid_ != 0, regionid_,
            other.regionid_ != 0, other.regionid_);
        clazz_ = visitor.visitInt(clazz_ != 0, clazz_,
            other.clazz_ != 0, other.clazz_);
        clanid_ = visitor.visitLong(clanid_ != 0L, clanid_,
            other.clanid_ != 0L, other.clanid_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                userid_ = input.readInt64();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                username_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                serverid_ = s;
                break;
              }
              case 32: {

                regionid_ = input.readInt32();
                break;
              }
              case 40: {

                clazz_ = input.readInt32();
                break;
              }
              case 48: {

                clanid_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (EnterServer.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:dispatcher.EnterServer)
  private static final EnterServer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EnterServer();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static EnterServer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EnterServer> PARSER;

  public static com.google.protobuf.Parser<EnterServer> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

