// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

/**
 * Protobuf type {@code dispatcher.EnterResult}
 */
public  final class EnterResult extends
    com.google.protobuf.GeneratedMessageLite<
        EnterResult, EnterResult.Builder> implements
    // @@protoc_insertion_point(message_implements:dispatcher.EnterResult)
    EnterResultOrBuilder {
  private EnterResult() {
    name_ = "";
    gameaddr_ = "";
    mname_ = "";
    downurl_ = "";
  }
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <pre>
   * success: 1, not exist: 2, full: 3, team full: 4
   * </pre>
   *
   * <code>optional int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }
  /**
   * <pre>
   * success: 1, not exist: 2, full: 3, team full: 4
   * </pre>
   *
   * <code>optional int32 code = 1;</code>
   */
  private void setCode(int value) {
    
    code_ = value;
  }
  /**
   * <pre>
   * success: 1, not exist: 2, full: 3, team full: 4
   * </pre>
   *
   * <code>optional int32 code = 1;</code>
   */
  private void clearCode() {
    
    code_ = 0;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private String name_;
  /**
   * <code>optional string name = 2;</code>
   */
  public String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 2;</code>
   */
  private void setName(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <code>optional string name = 2;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 2;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int GAMEADDR_FIELD_NUMBER = 3;
  private String gameaddr_;
  /**
   * <code>optional string gameaddr = 3;</code>
   */
  public String getGameaddr() {
    return gameaddr_;
  }
  /**
   * <code>optional string gameaddr = 3;</code>
   */
  public com.google.protobuf.ByteString
      getGameaddrBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gameaddr_);
  }
  /**
   * <code>optional string gameaddr = 3;</code>
   */
  private void setGameaddr(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    gameaddr_ = value;
  }
  /**
   * <code>optional string gameaddr = 3;</code>
   */
  private void clearGameaddr() {
    
    gameaddr_ = getDefaultInstance().getGameaddr();
  }
  /**
   * <code>optional string gameaddr = 3;</code>
   */
  private void setGameaddrBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    gameaddr_ = value.toStringUtf8();
  }

  public static final int MNAME_FIELD_NUMBER = 4;
  private String mname_;
  /**
   * <code>optional string mname = 4;</code>
   */
  public String getMname() {
    return mname_;
  }
  /**
   * <code>optional string mname = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMnameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mname_);
  }
  /**
   * <code>optional string mname = 4;</code>
   */
  private void setMname(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mname_ = value;
  }
  /**
   * <code>optional string mname = 4;</code>
   */
  private void clearMname() {
    
    mname_ = getDefaultInstance().getMname();
  }
  /**
   * <code>optional string mname = 4;</code>
   */
  private void setMnameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mname_ = value.toStringUtf8();
  }

  public static final int DOWNURL_FIELD_NUMBER = 5;
  private String downurl_;
  /**
   * <code>optional string downurl = 5;</code>
   */
  public String getDownurl() {
    return downurl_;
  }
  /**
   * <code>optional string downurl = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDownurlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(downurl_);
  }
  /**
   * <code>optional string downurl = 5;</code>
   */
  private void setDownurl(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    downurl_ = value;
  }
  /**
   * <code>optional string downurl = 5;</code>
   */
  private void clearDownurl() {
    
    downurl_ = getDefaultInstance().getDownurl();
  }
  /**
   * <code>optional string downurl = 5;</code>
   */
  private void setDownurlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    downurl_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!name_.isEmpty()) {
      output.writeString(2, getName());
    }
    if (!gameaddr_.isEmpty()) {
      output.writeString(3, getGameaddr());
    }
    if (!mname_.isEmpty()) {
      output.writeString(4, getMname());
    }
    if (!downurl_.isEmpty()) {
      output.writeString(5, getDownurl());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getName());
    }
    if (!gameaddr_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getGameaddr());
    }
    if (!mname_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getMname());
    }
    if (!downurl_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getDownurl());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static EnterResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static EnterResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static EnterResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static EnterResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static EnterResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static EnterResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static EnterResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static EnterResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static EnterResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static EnterResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EnterResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code dispatcher.EnterResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        EnterResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:dispatcher.EnterResult)
      EnterResultOrBuilder {
    // Construct using com.sandboxol.clw.dispatcher.EnterResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * success: 1, not exist: 2, full: 3, team full: 4
     * </pre>
     *
     * <code>optional int32 code = 1;</code>
     */
    public int getCode() {
      return instance.getCode();
    }
    /**
     * <pre>
     * success: 1, not exist: 2, full: 3, team full: 4
     * </pre>
     *
     * <code>optional int32 code = 1;</code>
     */
    public Builder setCode(int value) {
      copyOnWrite();
      instance.setCode(value);
      return this;
    }
    /**
     * <pre>
     * success: 1, not exist: 2, full: 3, team full: 4
     * </pre>
     *
     * <code>optional int32 code = 1;</code>
     */
    public Builder clearCode() {
      copyOnWrite();
      instance.clearCode();
      return this;
    }

    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>optional string gameaddr = 3;</code>
     */
    public String getGameaddr() {
      return instance.getGameaddr();
    }
    /**
     * <code>optional string gameaddr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGameaddrBytes() {
      return instance.getGameaddrBytes();
    }
    /**
     * <code>optional string gameaddr = 3;</code>
     */
    public Builder setGameaddr(
        String value) {
      copyOnWrite();
      instance.setGameaddr(value);
      return this;
    }
    /**
     * <code>optional string gameaddr = 3;</code>
     */
    public Builder clearGameaddr() {
      copyOnWrite();
      instance.clearGameaddr();
      return this;
    }
    /**
     * <code>optional string gameaddr = 3;</code>
     */
    public Builder setGameaddrBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGameaddrBytes(value);
      return this;
    }

    /**
     * <code>optional string mname = 4;</code>
     */
    public String getMname() {
      return instance.getMname();
    }
    /**
     * <code>optional string mname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMnameBytes() {
      return instance.getMnameBytes();
    }
    /**
     * <code>optional string mname = 4;</code>
     */
    public Builder setMname(
        String value) {
      copyOnWrite();
      instance.setMname(value);
      return this;
    }
    /**
     * <code>optional string mname = 4;</code>
     */
    public Builder clearMname() {
      copyOnWrite();
      instance.clearMname();
      return this;
    }
    /**
     * <code>optional string mname = 4;</code>
     */
    public Builder setMnameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMnameBytes(value);
      return this;
    }

    /**
     * <code>optional string downurl = 5;</code>
     */
    public String getDownurl() {
      return instance.getDownurl();
    }
    /**
     * <code>optional string downurl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDownurlBytes() {
      return instance.getDownurlBytes();
    }
    /**
     * <code>optional string downurl = 5;</code>
     */
    public Builder setDownurl(
        String value) {
      copyOnWrite();
      instance.setDownurl(value);
      return this;
    }
    /**
     * <code>optional string downurl = 5;</code>
     */
    public Builder clearDownurl() {
      copyOnWrite();
      instance.clearDownurl();
      return this;
    }
    /**
     * <code>optional string downurl = 5;</code>
     */
    public Builder setDownurlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDownurlBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dispatcher.EnterResult)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new EnterResult();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        EnterResult other = (EnterResult) arg1;
        code_ = visitor.visitInt(code_ != 0, code_,
            other.code_ != 0, other.code_);
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        gameaddr_ = visitor.visitString(!gameaddr_.isEmpty(), gameaddr_,
            !other.gameaddr_.isEmpty(), other.gameaddr_);
        mname_ = visitor.visitString(!mname_.isEmpty(), mname_,
            !other.mname_.isEmpty(), other.mname_);
        downurl_ = visitor.visitString(!downurl_.isEmpty(), downurl_,
            !other.downurl_.isEmpty(), other.downurl_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                code_ = input.readInt32();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                gameaddr_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                mname_ = s;
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                downurl_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (EnterResult.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:dispatcher.EnterResult)
  private static final EnterResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EnterResult();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static EnterResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<EnterResult> PARSER;

  public static com.google.protobuf.Parser<EnterResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

