// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

public interface EnterServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.EnterServer)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int64 userid = 1;</code>
   */
  long getUserid();

  /**
   * <code>optional string username = 2;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string serverid = 3;</code>
   */
  String getServerid();
  /**
   * <code>optional string serverid = 3;</code>
   */
  com.google.protobuf.ByteString
      getServeridBytes();

  /**
   * <code>optional int32 regionid = 4;</code>
   */
  int getRegionid();

  /**
   * <code>optional int32 clazz = 5;</code>
   */
  int getClazz();

  /**
   * <code>optional int64 clanid = 6;</code>
   */
  long getClanid();
}
