// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

public interface GetServerListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.GetServerList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 op = 1;</code>
   */
  int getOp();
}
