// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

/**
 * Protobuf type {@code dispatcher.ServerUpdate}
 */
public  final class ServerUpdate extends
    com.google.protobuf.GeneratedMessageLite<
        ServerUpdate, ServerUpdate.Builder> implements
    // @@protoc_insertion_point(message_implements:dispatcher.ServerUpdate)
    ServerUpdateOrBuilder {
  private ServerUpdate() {
  }
  public static final int ITEM_FIELD_NUMBER = 1;
  private ServerItem item_;
  /**
   * <code>optional .dispatcher.ServerItem item = 1;</code>
   */
  public boolean hasItem() {
    return item_ != null;
  }
  /**
   * <code>optional .dispatcher.ServerItem item = 1;</code>
   */
  public ServerItem getItem() {
    return item_ == null ? ServerItem.getDefaultInstance() : item_;
  }
  /**
   * <code>optional .dispatcher.ServerItem item = 1;</code>
   */
  private void setItem(ServerItem value) {
    if (value == null) {
      throw new NullPointerException();
    }
    item_ = value;
    
    }
  /**
   * <code>optional .dispatcher.ServerItem item = 1;</code>
   */
  private void setItem(
      ServerItem.Builder builderForValue) {
    item_ = builderForValue.build();
    
  }
  /**
   * <code>optional .dispatcher.ServerItem item = 1;</code>
   */
  private void mergeItem(ServerItem value) {
    if (item_ != null &&
        item_ != ServerItem.getDefaultInstance()) {
      item_ =
        ServerItem.newBuilder(item_).mergeFrom(value).buildPartial();
    } else {
      item_ = value;
    }
    
  }
  /**
   * <code>optional .dispatcher.ServerItem item = 1;</code>
   */
  private void clearItem() {  item_ = null;
    
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (item_ != null) {
      output.writeMessage(1, getItem());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (item_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getItem());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ServerUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ServerUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ServerUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code dispatcher.ServerUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ServerUpdate, Builder> implements
      // @@protoc_insertion_point(builder_implements:dispatcher.ServerUpdate)
      ServerUpdateOrBuilder {
    // Construct using com.sandboxol.clw.dispatcher.ServerUpdate.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .dispatcher.ServerItem item = 1;</code>
     */
    public boolean hasItem() {
      return instance.hasItem();
    }
    /**
     * <code>optional .dispatcher.ServerItem item = 1;</code>
     */
    public ServerItem getItem() {
      return instance.getItem();
    }
    /**
     * <code>optional .dispatcher.ServerItem item = 1;</code>
     */
    public Builder setItem(ServerItem value) {
      copyOnWrite();
      instance.setItem(value);
      return this;
      }
    /**
     * <code>optional .dispatcher.ServerItem item = 1;</code>
     */
    public Builder setItem(
        ServerItem.Builder builderForValue) {
      copyOnWrite();
      instance.setItem(builderForValue);
      return this;
    }
    /**
     * <code>optional .dispatcher.ServerItem item = 1;</code>
     */
    public Builder mergeItem(ServerItem value) {
      copyOnWrite();
      instance.mergeItem(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.ServerItem item = 1;</code>
     */
    public Builder clearItem() {  copyOnWrite();
      instance.clearItem();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dispatcher.ServerUpdate)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ServerUpdate();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ServerUpdate other = (ServerUpdate) arg1;
        item_ = visitor.visitMessage(item_, other.item_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                ServerItem.Builder subBuilder = null;
                if (item_ != null) {
                  subBuilder = item_.toBuilder();
                }
                item_ = input.readMessage(ServerItem.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(item_);
                  item_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ServerUpdate.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:dispatcher.ServerUpdate)
  private static final ServerUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ServerUpdate();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ServerUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerUpdate> PARSER;

  public static com.google.protobuf.Parser<ServerUpdate> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

