// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

/**
 * Protobuf type {@code dispatcher.ServerListResponse}
 */
public  final class ServerListResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ServerListResponse, ServerListResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:dispatcher.ServerListResponse)
    ServerListResponseOrBuilder {
  private ServerListResponse() {
  }
  private int stateCase_ = 0;
  private Object state_;
  public enum StateCase
      implements com.google.protobuf.Internal.EnumLite {
    LIST(1),
    UPDATE(2),
    RESULT(3),
    CLOSE(4),
    STATE_NOT_SET(0);
    private final int value;
    private StateCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StateCase valueOf(int value) {
      return forNumber(value);
    }

    public static StateCase forNumber(int value) {
      switch (value) {
        case 1: return LIST;
        case 2: return UPDATE;
        case 3: return RESULT;
        case 4: return CLOSE;
        case 0: return STATE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public StateCase
  getStateCase() {
    return StateCase.forNumber(
        stateCase_);
  }

  private void clearState() {
    stateCase_ = 0;
    state_ = null;
  }

  public static final int LIST_FIELD_NUMBER = 1;
  /**
   * <code>optional .dispatcher.ServerList list = 1;</code>
   */
  public ServerList getList() {
    if (stateCase_ == 1) {
       return (ServerList) state_;
    }
    return ServerList.getDefaultInstance();
  }
  /**
   * <code>optional .dispatcher.ServerList list = 1;</code>
   */
  private void setList(ServerList value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 1;
  }
  /**
   * <code>optional .dispatcher.ServerList list = 1;</code>
   */
  private void setList(
      ServerList.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 1;
  }
  /**
   * <code>optional .dispatcher.ServerList list = 1;</code>
   */
  private void mergeList(ServerList value) {
    if (stateCase_ == 1 &&
        state_ != ServerList.getDefaultInstance()) {
      state_ = ServerList.newBuilder((ServerList) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 1;
  }
  /**
   * <code>optional .dispatcher.ServerList list = 1;</code>
   */
  private void clearList() {
    if (stateCase_ == 1) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int UPDATE_FIELD_NUMBER = 2;
  /**
   * <code>optional .dispatcher.ServerUpdate update = 2;</code>
   */
  public ServerUpdate getUpdate() {
    if (stateCase_ == 2) {
       return (ServerUpdate) state_;
    }
    return ServerUpdate.getDefaultInstance();
  }
  /**
   * <code>optional .dispatcher.ServerUpdate update = 2;</code>
   */
  private void setUpdate(ServerUpdate value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 2;
  }
  /**
   * <code>optional .dispatcher.ServerUpdate update = 2;</code>
   */
  private void setUpdate(
      ServerUpdate.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 2;
  }
  /**
   * <code>optional .dispatcher.ServerUpdate update = 2;</code>
   */
  private void mergeUpdate(ServerUpdate value) {
    if (stateCase_ == 2 &&
        state_ != ServerUpdate.getDefaultInstance()) {
      state_ = ServerUpdate.newBuilder((ServerUpdate) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 2;
  }
  /**
   * <code>optional .dispatcher.ServerUpdate update = 2;</code>
   */
  private void clearUpdate() {
    if (stateCase_ == 2) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int RESULT_FIELD_NUMBER = 3;
  /**
   * <code>optional .dispatcher.EnterResult result = 3;</code>
   */
  public EnterResult getResult() {
    if (stateCase_ == 3) {
       return (EnterResult) state_;
    }
    return EnterResult.getDefaultInstance();
  }
  /**
   * <code>optional .dispatcher.EnterResult result = 3;</code>
   */
  private void setResult(EnterResult value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 3;
  }
  /**
   * <code>optional .dispatcher.EnterResult result = 3;</code>
   */
  private void setResult(
      EnterResult.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 3;
  }
  /**
   * <code>optional .dispatcher.EnterResult result = 3;</code>
   */
  private void mergeResult(EnterResult value) {
    if (stateCase_ == 3 &&
        state_ != EnterResult.getDefaultInstance()) {
      state_ = EnterResult.newBuilder((EnterResult) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 3;
  }
  /**
   * <code>optional .dispatcher.EnterResult result = 3;</code>
   */
  private void clearResult() {
    if (stateCase_ == 3) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int CLOSE_FIELD_NUMBER = 4;
  /**
   * <code>optional .dispatcher.CloseResult close = 4;</code>
   */
  public CloseResult getClose() {
    if (stateCase_ == 4) {
       return (CloseResult) state_;
    }
    return CloseResult.getDefaultInstance();
  }
  /**
   * <code>optional .dispatcher.CloseResult close = 4;</code>
   */
  private void setClose(CloseResult value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 4;
  }
  /**
   * <code>optional .dispatcher.CloseResult close = 4;</code>
   */
  private void setClose(
      CloseResult.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 4;
  }
  /**
   * <code>optional .dispatcher.CloseResult close = 4;</code>
   */
  private void mergeClose(CloseResult value) {
    if (stateCase_ == 4 &&
        state_ != CloseResult.getDefaultInstance()) {
      state_ = CloseResult.newBuilder((CloseResult) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 4;
  }
  /**
   * <code>optional .dispatcher.CloseResult close = 4;</code>
   */
  private void clearClose() {
    if (stateCase_ == 4) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stateCase_ == 1) {
      output.writeMessage(1, (ServerList) state_);
    }
    if (stateCase_ == 2) {
      output.writeMessage(2, (ServerUpdate) state_);
    }
    if (stateCase_ == 3) {
      output.writeMessage(3, (EnterResult) state_);
    }
    if (stateCase_ == 4) {
      output.writeMessage(4, (CloseResult) state_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (stateCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ServerList) state_);
    }
    if (stateCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ServerUpdate) state_);
    }
    if (stateCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (EnterResult) state_);
    }
    if (stateCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (CloseResult) state_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ServerListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ServerListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ServerListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code dispatcher.ServerListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ServerListResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:dispatcher.ServerListResponse)
      ServerListResponseOrBuilder {
    // Construct using com.sandboxol.clw.dispatcher.ServerListResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public StateCase
        getStateCase() {
      return instance.getStateCase();
    }

    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }


    /**
     * <code>optional .dispatcher.ServerList list = 1;</code>
     */
    public ServerList getList() {
      return instance.getList();
    }
    /**
     * <code>optional .dispatcher.ServerList list = 1;</code>
     */
    public Builder setList(ServerList value) {
      copyOnWrite();
      instance.setList(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.ServerList list = 1;</code>
     */
    public Builder setList(
        ServerList.Builder builderForValue) {
      copyOnWrite();
      instance.setList(builderForValue);
      return this;
    }
    /**
     * <code>optional .dispatcher.ServerList list = 1;</code>
     */
    public Builder mergeList(ServerList value) {
      copyOnWrite();
      instance.mergeList(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.ServerList list = 1;</code>
     */
    public Builder clearList() {
      copyOnWrite();
      instance.clearList();
      return this;
    }

    /**
     * <code>optional .dispatcher.ServerUpdate update = 2;</code>
     */
    public ServerUpdate getUpdate() {
      return instance.getUpdate();
    }
    /**
     * <code>optional .dispatcher.ServerUpdate update = 2;</code>
     */
    public Builder setUpdate(ServerUpdate value) {
      copyOnWrite();
      instance.setUpdate(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.ServerUpdate update = 2;</code>
     */
    public Builder setUpdate(
        ServerUpdate.Builder builderForValue) {
      copyOnWrite();
      instance.setUpdate(builderForValue);
      return this;
    }
    /**
     * <code>optional .dispatcher.ServerUpdate update = 2;</code>
     */
    public Builder mergeUpdate(ServerUpdate value) {
      copyOnWrite();
      instance.mergeUpdate(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.ServerUpdate update = 2;</code>
     */
    public Builder clearUpdate() {
      copyOnWrite();
      instance.clearUpdate();
      return this;
    }

    /**
     * <code>optional .dispatcher.EnterResult result = 3;</code>
     */
    public EnterResult getResult() {
      return instance.getResult();
    }
    /**
     * <code>optional .dispatcher.EnterResult result = 3;</code>
     */
    public Builder setResult(EnterResult value) {
      copyOnWrite();
      instance.setResult(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.EnterResult result = 3;</code>
     */
    public Builder setResult(
        EnterResult.Builder builderForValue) {
      copyOnWrite();
      instance.setResult(builderForValue);
      return this;
    }
    /**
     * <code>optional .dispatcher.EnterResult result = 3;</code>
     */
    public Builder mergeResult(EnterResult value) {
      copyOnWrite();
      instance.mergeResult(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.EnterResult result = 3;</code>
     */
    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }

    /**
     * <code>optional .dispatcher.CloseResult close = 4;</code>
     */
    public CloseResult getClose() {
      return instance.getClose();
    }
    /**
     * <code>optional .dispatcher.CloseResult close = 4;</code>
     */
    public Builder setClose(CloseResult value) {
      copyOnWrite();
      instance.setClose(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.CloseResult close = 4;</code>
     */
    public Builder setClose(
        CloseResult.Builder builderForValue) {
      copyOnWrite();
      instance.setClose(builderForValue);
      return this;
    }
    /**
     * <code>optional .dispatcher.CloseResult close = 4;</code>
     */
    public Builder mergeClose(CloseResult value) {
      copyOnWrite();
      instance.mergeClose(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.CloseResult close = 4;</code>
     */
    public Builder clearClose() {
      copyOnWrite();
      instance.clearClose();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dispatcher.ServerListResponse)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ServerListResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ServerListResponse other = (ServerListResponse) arg1;
        switch (other.getStateCase()) {
          case LIST: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 1,
                state_,
                other.state_);
            break;
          }
          case UPDATE: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 2,
                state_,
                other.state_);
            break;
          }
          case RESULT: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 3,
                state_,
                other.state_);
            break;
          }
          case CLOSE: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 4,
                state_,
                other.state_);
            break;
          }
          case STATE_NOT_SET: {
            visitor.visitOneofNotSet(stateCase_ != 0);
            break;
          }
        }
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          if (other.stateCase_ != 0) {
            stateCase_ = other.stateCase_;
          }
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                ServerList.Builder subBuilder = null;
                if (stateCase_ == 1) {
                  subBuilder = ((ServerList) state_).toBuilder();
                }
                state_ =
                     input.readMessage(ServerList.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((ServerList) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 1;
                break;
              }
              case 18: {
                ServerUpdate.Builder subBuilder = null;
                if (stateCase_ == 2) {
                  subBuilder = ((ServerUpdate) state_).toBuilder();
                }
                state_ =
                     input.readMessage(ServerUpdate.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((ServerUpdate) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 2;
                break;
              }
              case 26: {
                EnterResult.Builder subBuilder = null;
                if (stateCase_ == 3) {
                  subBuilder = ((EnterResult) state_).toBuilder();
                }
                state_ =
                     input.readMessage(EnterResult.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((EnterResult) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 3;
                break;
              }
              case 34: {
                CloseResult.Builder subBuilder = null;
                if (stateCase_ == 4) {
                  subBuilder = ((CloseResult) state_).toBuilder();
                }
                state_ =
                     input.readMessage(CloseResult.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((CloseResult) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 4;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ServerListResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:dispatcher.ServerListResponse)
  private static final ServerListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ServerListResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ServerListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerListResponse> PARSER;

  public static com.google.protobuf.Parser<ServerListResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

