// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

public interface ServerListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.ServerListResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .dispatcher.ServerList list = 1;</code>
   */
  ServerList getList();

  /**
   * <code>optional .dispatcher.ServerUpdate update = 2;</code>
   */
  ServerUpdate getUpdate();

  /**
   * <code>optional .dispatcher.EnterResult result = 3;</code>
   */
  EnterResult getResult();

  /**
   * <code>optional .dispatcher.CloseResult close = 4;</code>
   */
  CloseResult getClose();

  public ServerListResponse.StateCase getStateCase();
}
