// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

/**
 * Protobuf type {@code dispatcher.ServerListRequest}
 */
public  final class ServerListRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ServerListRequest, ServerListRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:dispatcher.ServerListRequest)
    ServerListRequestOrBuilder {
  private ServerListRequest() {
  }
  private int operateCase_ = 0;
  private Object operate_;
  public enum OperateCase
      implements com.google.protobuf.Internal.EnumLite {
    LIST(1),
    ENTER(2),
    CLOSE(3),
    OPERATE_NOT_SET(0);
    private final int value;
    private OperateCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static OperateCase valueOf(int value) {
      return forNumber(value);
    }

    public static OperateCase forNumber(int value) {
      switch (value) {
        case 1: return LIST;
        case 2: return ENTER;
        case 3: return CLOSE;
        case 0: return OPERATE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OperateCase
  getOperateCase() {
    return OperateCase.forNumber(
        operateCase_);
  }

  private void clearOperate() {
    operateCase_ = 0;
    operate_ = null;
  }

  public static final int LIST_FIELD_NUMBER = 1;
  /**
   * <code>optional .dispatcher.GetServerList list = 1;</code>
   */
  public GetServerList getList() {
    if (operateCase_ == 1) {
       return (GetServerList) operate_;
    }
    return GetServerList.getDefaultInstance();
  }
  /**
   * <code>optional .dispatcher.GetServerList list = 1;</code>
   */
  private void setList(GetServerList value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 1;
  }
  /**
   * <code>optional .dispatcher.GetServerList list = 1;</code>
   */
  private void setList(
      GetServerList.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 1;
  }
  /**
   * <code>optional .dispatcher.GetServerList list = 1;</code>
   */
  private void mergeList(GetServerList value) {
    if (operateCase_ == 1 &&
        operate_ != GetServerList.getDefaultInstance()) {
      operate_ = GetServerList.newBuilder((GetServerList) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 1;
  }
  /**
   * <code>optional .dispatcher.GetServerList list = 1;</code>
   */
  private void clearList() {
    if (operateCase_ == 1) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public static final int ENTER_FIELD_NUMBER = 2;
  /**
   * <code>optional .dispatcher.EnterServer enter = 2;</code>
   */
  public EnterServer getEnter() {
    if (operateCase_ == 2) {
       return (EnterServer) operate_;
    }
    return EnterServer.getDefaultInstance();
  }
  /**
   * <code>optional .dispatcher.EnterServer enter = 2;</code>
   */
  private void setEnter(EnterServer value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 2;
  }
  /**
   * <code>optional .dispatcher.EnterServer enter = 2;</code>
   */
  private void setEnter(
      EnterServer.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 2;
  }
  /**
   * <code>optional .dispatcher.EnterServer enter = 2;</code>
   */
  private void mergeEnter(EnterServer value) {
    if (operateCase_ == 2 &&
        operate_ != EnterServer.getDefaultInstance()) {
      operate_ = EnterServer.newBuilder((EnterServer) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 2;
  }
  /**
   * <code>optional .dispatcher.EnterServer enter = 2;</code>
   */
  private void clearEnter() {
    if (operateCase_ == 2) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public static final int CLOSE_FIELD_NUMBER = 3;
  /**
   * <code>optional .dispatcher.CloseList close = 3;</code>
   */
  public CloseList getClose() {
    if (operateCase_ == 3) {
       return (CloseList) operate_;
    }
    return CloseList.getDefaultInstance();
  }
  /**
   * <code>optional .dispatcher.CloseList close = 3;</code>
   */
  private void setClose(CloseList value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 3;
  }
  /**
   * <code>optional .dispatcher.CloseList close = 3;</code>
   */
  private void setClose(
      CloseList.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 3;
  }
  /**
   * <code>optional .dispatcher.CloseList close = 3;</code>
   */
  private void mergeClose(CloseList value) {
    if (operateCase_ == 3 &&
        operate_ != CloseList.getDefaultInstance()) {
      operate_ = CloseList.newBuilder((CloseList) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 3;
  }
  /**
   * <code>optional .dispatcher.CloseList close = 3;</code>
   */
  private void clearClose() {
    if (operateCase_ == 3) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (operateCase_ == 1) {
      output.writeMessage(1, (GetServerList) operate_);
    }
    if (operateCase_ == 2) {
      output.writeMessage(2, (EnterServer) operate_);
    }
    if (operateCase_ == 3) {
      output.writeMessage(3, (CloseList) operate_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (operateCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (GetServerList) operate_);
    }
    if (operateCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (EnterServer) operate_);
    }
    if (operateCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (CloseList) operate_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ServerListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ServerListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ServerListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code dispatcher.ServerListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ServerListRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:dispatcher.ServerListRequest)
      ServerListRequestOrBuilder {
    // Construct using com.sandboxol.clw.dispatcher.ServerListRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public OperateCase
        getOperateCase() {
      return instance.getOperateCase();
    }

    public Builder clearOperate() {
      copyOnWrite();
      instance.clearOperate();
      return this;
    }


    /**
     * <code>optional .dispatcher.GetServerList list = 1;</code>
     */
    public GetServerList getList() {
      return instance.getList();
    }
    /**
     * <code>optional .dispatcher.GetServerList list = 1;</code>
     */
    public Builder setList(GetServerList value) {
      copyOnWrite();
      instance.setList(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.GetServerList list = 1;</code>
     */
    public Builder setList(
        GetServerList.Builder builderForValue) {
      copyOnWrite();
      instance.setList(builderForValue);
      return this;
    }
    /**
     * <code>optional .dispatcher.GetServerList list = 1;</code>
     */
    public Builder mergeList(GetServerList value) {
      copyOnWrite();
      instance.mergeList(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.GetServerList list = 1;</code>
     */
    public Builder clearList() {
      copyOnWrite();
      instance.clearList();
      return this;
    }

    /**
     * <code>optional .dispatcher.EnterServer enter = 2;</code>
     */
    public EnterServer getEnter() {
      return instance.getEnter();
    }
    /**
     * <code>optional .dispatcher.EnterServer enter = 2;</code>
     */
    public Builder setEnter(EnterServer value) {
      copyOnWrite();
      instance.setEnter(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.EnterServer enter = 2;</code>
     */
    public Builder setEnter(
        EnterServer.Builder builderForValue) {
      copyOnWrite();
      instance.setEnter(builderForValue);
      return this;
    }
    /**
     * <code>optional .dispatcher.EnterServer enter = 2;</code>
     */
    public Builder mergeEnter(EnterServer value) {
      copyOnWrite();
      instance.mergeEnter(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.EnterServer enter = 2;</code>
     */
    public Builder clearEnter() {
      copyOnWrite();
      instance.clearEnter();
      return this;
    }

    /**
     * <code>optional .dispatcher.CloseList close = 3;</code>
     */
    public CloseList getClose() {
      return instance.getClose();
    }
    /**
     * <code>optional .dispatcher.CloseList close = 3;</code>
     */
    public Builder setClose(CloseList value) {
      copyOnWrite();
      instance.setClose(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.CloseList close = 3;</code>
     */
    public Builder setClose(
        CloseList.Builder builderForValue) {
      copyOnWrite();
      instance.setClose(builderForValue);
      return this;
    }
    /**
     * <code>optional .dispatcher.CloseList close = 3;</code>
     */
    public Builder mergeClose(CloseList value) {
      copyOnWrite();
      instance.mergeClose(value);
      return this;
    }
    /**
     * <code>optional .dispatcher.CloseList close = 3;</code>
     */
    public Builder clearClose() {
      copyOnWrite();
      instance.clearClose();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dispatcher.ServerListRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ServerListRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ServerListRequest other = (ServerListRequest) arg1;
        switch (other.getOperateCase()) {
          case LIST: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 1,
                operate_,
                other.operate_);
            break;
          }
          case ENTER: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 2,
                operate_,
                other.operate_);
            break;
          }
          case CLOSE: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 3,
                operate_,
                other.operate_);
            break;
          }
          case OPERATE_NOT_SET: {
            visitor.visitOneofNotSet(operateCase_ != 0);
            break;
          }
        }
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          if (other.operateCase_ != 0) {
            operateCase_ = other.operateCase_;
          }
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                GetServerList.Builder subBuilder = null;
                if (operateCase_ == 1) {
                  subBuilder = ((GetServerList) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(GetServerList.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((GetServerList) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 1;
                break;
              }
              case 18: {
                EnterServer.Builder subBuilder = null;
                if (operateCase_ == 2) {
                  subBuilder = ((EnterServer) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(EnterServer.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((EnterServer) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 2;
                break;
              }
              case 26: {
                CloseList.Builder subBuilder = null;
                if (operateCase_ == 3) {
                  subBuilder = ((CloseList) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(CloseList.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((CloseList) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 3;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ServerListRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:dispatcher.ServerListRequest)
  private static final ServerListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ServerListRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ServerListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerListRequest> PARSER;

  public static com.google.protobuf.Parser<ServerListRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

