// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

public interface ServerListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.ServerList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  java.util.List<ServerItem>
      getServerlistList();
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  ServerItem getServerlist(int index);
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  int getServerlistCount();
}
