// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

/**
 * Protobuf type {@code dispatcher.ServerList}
 */
public  final class ServerList extends
    com.google.protobuf.GeneratedMessageLite<
        ServerList, ServerList.Builder> implements
    // @@protoc_insertion_point(message_implements:dispatcher.ServerList)
    ServerListOrBuilder {
  private ServerList() {
    serverlist_ = emptyProtobufList();
  }
  public static final int SERVERLIST_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<ServerItem> serverlist_;
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  public java.util.List<ServerItem> getServerlistList() {
    return serverlist_;
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  public java.util.List<? extends ServerItemOrBuilder>
      getServerlistOrBuilderList() {
    return serverlist_;
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  public int getServerlistCount() {
    return serverlist_.size();
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  public ServerItem getServerlist(int index) {
    return serverlist_.get(index);
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  public ServerItemOrBuilder getServerlistOrBuilder(
      int index) {
    return serverlist_.get(index);
  }
  private void ensureServerlistIsMutable() {
    if (!serverlist_.isModifiable()) {
      serverlist_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(serverlist_);
     }
  }

  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void setServerlist(
      int index, ServerItem value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureServerlistIsMutable();
    serverlist_.set(index, value);
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void setServerlist(
      int index, ServerItem.Builder builderForValue) {
    ensureServerlistIsMutable();
    serverlist_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void addServerlist(ServerItem value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureServerlistIsMutable();
    serverlist_.add(value);
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void addServerlist(
      int index, ServerItem value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureServerlistIsMutable();
    serverlist_.add(index, value);
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void addServerlist(
      ServerItem.Builder builderForValue) {
    ensureServerlistIsMutable();
    serverlist_.add(builderForValue.build());
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void addServerlist(
      int index, ServerItem.Builder builderForValue) {
    ensureServerlistIsMutable();
    serverlist_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void addAllServerlist(
      Iterable<? extends ServerItem> values) {
    ensureServerlistIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, serverlist_);
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void clearServerlist() {
    serverlist_ = emptyProtobufList();
  }
  /**
   * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
   */
  private void removeServerlist(int index) {
    ensureServerlistIsMutable();
    serverlist_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < serverlist_.size(); i++) {
      output.writeMessage(1, serverlist_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < serverlist_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, serverlist_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ServerList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ServerList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ServerList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code dispatcher.ServerList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ServerList, Builder> implements
      // @@protoc_insertion_point(builder_implements:dispatcher.ServerList)
      ServerListOrBuilder {
    // Construct using com.sandboxol.clw.dispatcher.ServerList.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public java.util.List<ServerItem> getServerlistList() {
      return java.util.Collections.unmodifiableList(
          instance.getServerlistList());
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public int getServerlistCount() {
      return instance.getServerlistCount();
    }/**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public ServerItem getServerlist(int index) {
      return instance.getServerlist(index);
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder setServerlist(
        int index, ServerItem value) {
      copyOnWrite();
      instance.setServerlist(index, value);
      return this;
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder setServerlist(
        int index, ServerItem.Builder builderForValue) {
      copyOnWrite();
      instance.setServerlist(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder addServerlist(ServerItem value) {
      copyOnWrite();
      instance.addServerlist(value);
      return this;
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder addServerlist(
        int index, ServerItem value) {
      copyOnWrite();
      instance.addServerlist(index, value);
      return this;
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder addServerlist(
        ServerItem.Builder builderForValue) {
      copyOnWrite();
      instance.addServerlist(builderForValue);
      return this;
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder addServerlist(
        int index, ServerItem.Builder builderForValue) {
      copyOnWrite();
      instance.addServerlist(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder addAllServerlist(
        Iterable<? extends ServerItem> values) {
      copyOnWrite();
      instance.addAllServerlist(values);
      return this;
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder clearServerlist() {
      copyOnWrite();
      instance.clearServerlist();
      return this;
    }
    /**
     * <code>repeated .dispatcher.ServerItem serverlist = 1;</code>
     */
    public Builder removeServerlist(int index) {
      copyOnWrite();
      instance.removeServerlist(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dispatcher.ServerList)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ServerList();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        serverlist_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ServerList other = (ServerList) arg1;
        serverlist_= visitor.visitList(serverlist_, other.serverlist_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!serverlist_.isModifiable()) {
                  serverlist_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(serverlist_);
                }
                serverlist_.add(
                    input.readMessage(ServerItem.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ServerList.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:dispatcher.ServerList)
  private static final ServerList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ServerList();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ServerList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerList> PARSER;

  public static com.google.protobuf.Parser<ServerList> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

