// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

public interface ServerUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.ServerUpdate)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .dispatcher.ServerItem item = 1;</code>
   */
  boolean hasItem();
  /**
   * <code>optional .dispatcher.ServerItem item = 1;</code>
   */
  ServerItem getItem();
}
