// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

public interface ServerItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.ServerItem)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional int32 cur = 2;</code>
   */
  int getCur();

  /**
   * <code>optional int32 max = 3;</code>
   */
  int getMax();

  /**
   * <code>optional string name = 4;</code>
   */
  String getName();
  /**
   * <code>optional string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
