// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdispatcher.proto

package com.sandboxol.clw.dispatcher;

/**
 * Protobuf type {@code dispatcher.ServerItem}
 */
public  final class ServerItem extends
    com.google.protobuf.GeneratedMessageLite<
        ServerItem, ServerItem.Builder> implements
    // @@protoc_insertion_point(message_implements:dispatcher.ServerItem)
    ServerItemOrBuilder {
  private ServerItem() {
    id_ = "";
    name_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private String id_;
  /**
   * <code>optional string id = 1;</code>
   */
  public String getId() {
    return id_;
  }
  /**
   * <code>optional string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>optional string id = 1;</code>
   */
  private void setId(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    id_ = value;
  }
  /**
   * <code>optional string id = 1;</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>optional string id = 1;</code>
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    id_ = value.toStringUtf8();
  }

  public static final int CUR_FIELD_NUMBER = 2;
  private int cur_;
  /**
   * <code>optional int32 cur = 2;</code>
   */
  public int getCur() {
    return cur_;
  }
  /**
   * <code>optional int32 cur = 2;</code>
   */
  private void setCur(int value) {
    
    cur_ = value;
  }
  /**
   * <code>optional int32 cur = 2;</code>
   */
  private void clearCur() {
    
    cur_ = 0;
  }

  public static final int MAX_FIELD_NUMBER = 3;
  private int max_;
  /**
   * <code>optional int32 max = 3;</code>
   */
  public int getMax() {
    return max_;
  }
  /**
   * <code>optional int32 max = 3;</code>
   */
  private void setMax(int value) {
    
    max_ = value;
  }
  /**
   * <code>optional int32 max = 3;</code>
   */
  private void clearMax() {
    
    max_ = 0;
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private String name_;
  /**
   * <code>optional string name = 4;</code>
   */
  public String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 4;</code>
   */
  private void setName(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <code>optional string name = 4;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 4;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!id_.isEmpty()) {
      output.writeString(1, getId());
    }
    if (cur_ != 0) {
      output.writeInt32(2, cur_);
    }
    if (max_ != 0) {
      output.writeInt32(3, max_);
    }
    if (!name_.isEmpty()) {
      output.writeString(4, getName());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!id_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getId());
    }
    if (cur_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cur_);
    }
    if (max_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, max_);
    }
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getName());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ServerItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ServerItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ServerItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ServerItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ServerItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ServerItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ServerItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code dispatcher.ServerItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ServerItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:dispatcher.ServerItem)
      ServerItemOrBuilder {
    // Construct using com.sandboxol.clw.dispatcher.ServerItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string id = 1;</code>
     */
    public String getId() {
      return instance.getId();
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder setId(
        String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>optional int32 cur = 2;</code>
     */
    public int getCur() {
      return instance.getCur();
    }
    /**
     * <code>optional int32 cur = 2;</code>
     */
    public Builder setCur(int value) {
      copyOnWrite();
      instance.setCur(value);
      return this;
    }
    /**
     * <code>optional int32 cur = 2;</code>
     */
    public Builder clearCur() {
      copyOnWrite();
      instance.clearCur();
      return this;
    }

    /**
     * <code>optional int32 max = 3;</code>
     */
    public int getMax() {
      return instance.getMax();
    }
    /**
     * <code>optional int32 max = 3;</code>
     */
    public Builder setMax(int value) {
      copyOnWrite();
      instance.setMax(value);
      return this;
    }
    /**
     * <code>optional int32 max = 3;</code>
     */
    public Builder clearMax() {
      copyOnWrite();
      instance.clearMax();
      return this;
    }

    /**
     * <code>optional string name = 4;</code>
     */
    public String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public Builder setName(
        String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dispatcher.ServerItem)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ServerItem();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ServerItem other = (ServerItem) arg1;
        id_ = visitor.visitString(!id_.isEmpty(), id_,
            !other.id_.isEmpty(), other.id_);
        cur_ = visitor.visitInt(cur_ != 0, cur_,
            other.cur_ != 0, other.cur_);
        max_ = visitor.visitInt(max_ != 0, max_,
            other.max_ != 0, other.max_);
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                id_ = s;
                break;
              }
              case 16: {

                cur_ = input.readInt32();
                break;
              }
              case 24: {

                max_ = input.readInt32();
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ServerItem.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:dispatcher.ServerItem)
  private static final ServerItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ServerItem();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ServerItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerItem> PARSER;

  public static com.google.protobuf.Parser<ServerItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

