// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public final class ConnectorProto {
  private ConnectorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
