// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface QueueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.QueueRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .connector.QueueStart start = 1;</code>
   */
  QueueStart getStart();

  /**
   * <code>optional .connector.QueueStop stop = 2;</code>
   */
  QueueStop getStop();

  public QueueRequest.OperateCase getOperateCase();
}
