// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface QueueFailedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.QueueFailed)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
   */
  int getReasonValue();
  /**
   * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
   */
  QueueFailed.Reason getReason();
}
