// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

/**
 * Protobuf type {@code connector.QueueGoing}
 */
public  final class QueueGoing extends
    com.google.protobuf.GeneratedMessageLite<
        QueueGoing, QueueGoing.Builder> implements
    // @@protoc_insertion_point(message_implements:connector.QueueGoing)
    QueueGoingOrBuilder {
  private QueueGoing() {
  }
  public static final int RANK_FIELD_NUMBER = 1;
  private int rank_;
  /**
   * <pre>
   * rank, 0 is the first.
   * </pre>
   *
   * <code>optional int32 rank = 1;</code>
   */
  public int getRank() {
    return rank_;
  }
  /**
   * <pre>
   * rank, 0 is the first.
   * </pre>
   *
   * <code>optional int32 rank = 1;</code>
   */
  private void setRank(int value) {
    
    rank_ = value;
  }
  /**
   * <pre>
   * rank, 0 is the first.
   * </pre>
   *
   * <code>optional int32 rank = 1;</code>
   */
  private void clearRank() {
    
    rank_ = 0;
  }

  public static final int LENGTH_FIELD_NUMBER = 2;
  private int length_;
  /**
   * <pre>
   * queue length
   * </pre>
   *
   * <code>optional int32 length = 2;</code>
   */
  public int getLength() {
    return length_;
  }
  /**
   * <pre>
   * queue length
   * </pre>
   *
   * <code>optional int32 length = 2;</code>
   */
  private void setLength(int value) {
    
    length_ = value;
  }
  /**
   * <pre>
   * queue length
   * </pre>
   *
   * <code>optional int32 length = 2;</code>
   */
  private void clearLength() {
    
    length_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rank_ != 0) {
      output.writeInt32(1, rank_);
    }
    if (length_ != 0) {
      output.writeInt32(2, length_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (rank_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rank_);
    }
    if (length_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, length_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static QueueGoing parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static QueueGoing parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static QueueGoing parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static QueueGoing parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static QueueGoing parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static QueueGoing parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static QueueGoing parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static QueueGoing parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static QueueGoing parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static QueueGoing parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QueueGoing prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code connector.QueueGoing}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        QueueGoing, Builder> implements
      // @@protoc_insertion_point(builder_implements:connector.QueueGoing)
      QueueGoingOrBuilder {
    // Construct using com.sandboxol.mgs.connector.QueueGoing.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * rank, 0 is the first.
     * </pre>
     *
     * <code>optional int32 rank = 1;</code>
     */
    public int getRank() {
      return instance.getRank();
    }
    /**
     * <pre>
     * rank, 0 is the first.
     * </pre>
     *
     * <code>optional int32 rank = 1;</code>
     */
    public Builder setRank(int value) {
      copyOnWrite();
      instance.setRank(value);
      return this;
    }
    /**
     * <pre>
     * rank, 0 is the first.
     * </pre>
     *
     * <code>optional int32 rank = 1;</code>
     */
    public Builder clearRank() {
      copyOnWrite();
      instance.clearRank();
      return this;
    }

    /**
     * <pre>
     * queue length
     * </pre>
     *
     * <code>optional int32 length = 2;</code>
     */
    public int getLength() {
      return instance.getLength();
    }
    /**
     * <pre>
     * queue length
     * </pre>
     *
     * <code>optional int32 length = 2;</code>
     */
    public Builder setLength(int value) {
      copyOnWrite();
      instance.setLength(value);
      return this;
    }
    /**
     * <pre>
     * queue length
     * </pre>
     *
     * <code>optional int32 length = 2;</code>
     */
    public Builder clearLength() {
      copyOnWrite();
      instance.clearLength();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:connector.QueueGoing)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new QueueGoing();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        QueueGoing other = (QueueGoing) arg1;
        rank_ = visitor.visitInt(rank_ != 0, rank_,
            other.rank_ != 0, other.rank_);
        length_ = visitor.visitInt(length_ != 0, length_,
            other.length_ != 0, other.length_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                rank_ = input.readInt32();
                break;
              }
              case 16: {

                length_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (QueueGoing.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:connector.QueueGoing)
  private static final QueueGoing DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QueueGoing();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static QueueGoing getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<QueueGoing> PARSER;

  public static com.google.protobuf.Parser<QueueGoing> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

