// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface QueueGoingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.QueueGoing)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * rank, 0 is the first.
   * </pre>
   *
   * <code>optional int32 rank = 1;</code>
   */
  int getRank();

  /**
   * <pre>
   * queue length
   * </pre>
   *
   * <code>optional int32 length = 2;</code>
   */
  int getLength();
}
