// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

/**
 * Protobuf type {@code connector.QueueRequest}
 */
public  final class QueueRequest extends
    com.google.protobuf.GeneratedMessageLite<
        QueueRequest, QueueRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:connector.QueueRequest)
    QueueRequestOrBuilder {
  private QueueRequest() {
  }
  private int operateCase_ = 0;
  private Object operate_;
  public enum OperateCase
      implements com.google.protobuf.Internal.EnumLite {
    START(1),
    STOP(2),
    OPERATE_NOT_SET(0);
    private final int value;
    private OperateCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static OperateCase valueOf(int value) {
      return forNumber(value);
    }

    public static OperateCase forNumber(int value) {
      switch (value) {
        case 1: return START;
        case 2: return STOP;
        case 0: return OPERATE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OperateCase
  getOperateCase() {
    return OperateCase.forNumber(
        operateCase_);
  }

  private void clearOperate() {
    operateCase_ = 0;
    operate_ = null;
  }

  public static final int START_FIELD_NUMBER = 1;
  /**
   * <code>optional .connector.QueueStart start = 1;</code>
   */
  public QueueStart getStart() {
    if (operateCase_ == 1) {
       return (QueueStart) operate_;
    }
    return QueueStart.getDefaultInstance();
  }
  /**
   * <code>optional .connector.QueueStart start = 1;</code>
   */
  private void setStart(QueueStart value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 1;
  }
  /**
   * <code>optional .connector.QueueStart start = 1;</code>
   */
  private void setStart(
      QueueStart.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 1;
  }
  /**
   * <code>optional .connector.QueueStart start = 1;</code>
   */
  private void mergeStart(QueueStart value) {
    if (operateCase_ == 1 &&
        operate_ != QueueStart.getDefaultInstance()) {
      operate_ = QueueStart.newBuilder((QueueStart) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 1;
  }
  /**
   * <code>optional .connector.QueueStart start = 1;</code>
   */
  private void clearStart() {
    if (operateCase_ == 1) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public static final int STOP_FIELD_NUMBER = 2;
  /**
   * <code>optional .connector.QueueStop stop = 2;</code>
   */
  public QueueStop getStop() {
    if (operateCase_ == 2) {
       return (QueueStop) operate_;
    }
    return QueueStop.getDefaultInstance();
  }
  /**
   * <code>optional .connector.QueueStop stop = 2;</code>
   */
  private void setStop(QueueStop value) {
    if (value == null) {
      throw new NullPointerException();
    }
    operate_ = value;
    operateCase_ = 2;
  }
  /**
   * <code>optional .connector.QueueStop stop = 2;</code>
   */
  private void setStop(
      QueueStop.Builder builderForValue) {
    operate_ = builderForValue.build();
    operateCase_ = 2;
  }
  /**
   * <code>optional .connector.QueueStop stop = 2;</code>
   */
  private void mergeStop(QueueStop value) {
    if (operateCase_ == 2 &&
        operate_ != QueueStop.getDefaultInstance()) {
      operate_ = QueueStop.newBuilder((QueueStop) operate_)
          .mergeFrom(value).buildPartial();
    } else {
      operate_ = value;
    }
    operateCase_ = 2;
  }
  /**
   * <code>optional .connector.QueueStop stop = 2;</code>
   */
  private void clearStop() {
    if (operateCase_ == 2) {
      operateCase_ = 0;
      operate_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (operateCase_ == 1) {
      output.writeMessage(1, (QueueStart) operate_);
    }
    if (operateCase_ == 2) {
      output.writeMessage(2, (QueueStop) operate_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (operateCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (QueueStart) operate_);
    }
    if (operateCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (QueueStop) operate_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static QueueRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static QueueRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static QueueRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static QueueRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static QueueRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static QueueRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static QueueRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static QueueRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static QueueRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static QueueRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QueueRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code connector.QueueRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        QueueRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:connector.QueueRequest)
      QueueRequestOrBuilder {
    // Construct using com.sandboxol.mgs.connector.QueueRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public OperateCase
        getOperateCase() {
      return instance.getOperateCase();
    }

    public Builder clearOperate() {
      copyOnWrite();
      instance.clearOperate();
      return this;
    }


    /**
     * <code>optional .connector.QueueStart start = 1;</code>
     */
    public QueueStart getStart() {
      return instance.getStart();
    }
    /**
     * <code>optional .connector.QueueStart start = 1;</code>
     */
    public Builder setStart(QueueStart value) {
      copyOnWrite();
      instance.setStart(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueStart start = 1;</code>
     */
    public Builder setStart(
        QueueStart.Builder builderForValue) {
      copyOnWrite();
      instance.setStart(builderForValue);
      return this;
    }
    /**
     * <code>optional .connector.QueueStart start = 1;</code>
     */
    public Builder mergeStart(QueueStart value) {
      copyOnWrite();
      instance.mergeStart(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueStart start = 1;</code>
     */
    public Builder clearStart() {
      copyOnWrite();
      instance.clearStart();
      return this;
    }

    /**
     * <code>optional .connector.QueueStop stop = 2;</code>
     */
    public QueueStop getStop() {
      return instance.getStop();
    }
    /**
     * <code>optional .connector.QueueStop stop = 2;</code>
     */
    public Builder setStop(QueueStop value) {
      copyOnWrite();
      instance.setStop(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueStop stop = 2;</code>
     */
    public Builder setStop(
        QueueStop.Builder builderForValue) {
      copyOnWrite();
      instance.setStop(builderForValue);
      return this;
    }
    /**
     * <code>optional .connector.QueueStop stop = 2;</code>
     */
    public Builder mergeStop(QueueStop value) {
      copyOnWrite();
      instance.mergeStop(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueStop stop = 2;</code>
     */
    public Builder clearStop() {
      copyOnWrite();
      instance.clearStop();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:connector.QueueRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new QueueRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        QueueRequest other = (QueueRequest) arg1;
        switch (other.getOperateCase()) {
          case START: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 1,
                operate_,
                other.operate_);
            break;
          }
          case STOP: {
            operate_ = visitor.visitOneofMessage(
                operateCase_ == 2,
                operate_,
                other.operate_);
            break;
          }
          case OPERATE_NOT_SET: {
            visitor.visitOneofNotSet(operateCase_ != 0);
            break;
          }
        }
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          if (other.operateCase_ != 0) {
            operateCase_ = other.operateCase_;
          }
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                QueueStart.Builder subBuilder = null;
                if (operateCase_ == 1) {
                  subBuilder = ((QueueStart) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(QueueStart.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((QueueStart) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 1;
                break;
              }
              case 18: {
                QueueStop.Builder subBuilder = null;
                if (operateCase_ == 2) {
                  subBuilder = ((QueueStop) operate_).toBuilder();
                }
                operate_ =
                     input.readMessage(QueueStop.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((QueueStop) operate_);
                  operate_ = subBuilder.buildPartial();
                }
                operateCase_ = 2;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (QueueRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:connector.QueueRequest)
  private static final QueueRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QueueRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static QueueRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<QueueRequest> PARSER;

  public static com.google.protobuf.Parser<QueueRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

