// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

/**
 * Protobuf type {@code connector.QueueResponse}
 */
public  final class QueueResponse extends
    com.google.protobuf.GeneratedMessageLite<
        QueueResponse, QueueResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:connector.QueueResponse)
    QueueResponseOrBuilder {
  private QueueResponse() {
  }
  private int stateCase_ = 0;
  private Object state_;
  public enum StateCase
      implements com.google.protobuf.Internal.EnumLite {
    GOING(1),
    DONE(2),
    STARTING(3),
    STATE_NOT_SET(0);
    private final int value;
    private StateCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StateCase valueOf(int value) {
      return forNumber(value);
    }

    public static StateCase forNumber(int value) {
      switch (value) {
        case 1: return GOING;
        case 2: return DONE;
        case 3: return STARTING;
        case 0: return STATE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public StateCase
  getStateCase() {
    return StateCase.forNumber(
        stateCase_);
  }

  private void clearState() {
    stateCase_ = 0;
    state_ = null;
  }

  public static final int GOING_FIELD_NUMBER = 1;
  /**
   * <code>optional .connector.QueueGoing going = 1;</code>
   */
  public QueueGoing getGoing() {
    if (stateCase_ == 1) {
       return (QueueGoing) state_;
    }
    return QueueGoing.getDefaultInstance();
  }
  /**
   * <code>optional .connector.QueueGoing going = 1;</code>
   */
  private void setGoing(QueueGoing value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 1;
  }
  /**
   * <code>optional .connector.QueueGoing going = 1;</code>
   */
  private void setGoing(
      QueueGoing.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 1;
  }
  /**
   * <code>optional .connector.QueueGoing going = 1;</code>
   */
  private void mergeGoing(QueueGoing value) {
    if (stateCase_ == 1 &&
        state_ != QueueGoing.getDefaultInstance()) {
      state_ = QueueGoing.newBuilder((QueueGoing) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 1;
  }
  /**
   * <code>optional .connector.QueueGoing going = 1;</code>
   */
  private void clearGoing() {
    if (stateCase_ == 1) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int DONE_FIELD_NUMBER = 2;
  /**
   * <code>optional .connector.QueueDone done = 2;</code>
   */
  public QueueDone getDone() {
    if (stateCase_ == 2) {
       return (QueueDone) state_;
    }
    return QueueDone.getDefaultInstance();
  }
  /**
   * <code>optional .connector.QueueDone done = 2;</code>
   */
  private void setDone(QueueDone value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 2;
  }
  /**
   * <code>optional .connector.QueueDone done = 2;</code>
   */
  private void setDone(
      QueueDone.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 2;
  }
  /**
   * <code>optional .connector.QueueDone done = 2;</code>
   */
  private void mergeDone(QueueDone value) {
    if (stateCase_ == 2 &&
        state_ != QueueDone.getDefaultInstance()) {
      state_ = QueueDone.newBuilder((QueueDone) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 2;
  }
  /**
   * <code>optional .connector.QueueDone done = 2;</code>
   */
  private void clearDone() {
    if (stateCase_ == 2) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int STARTING_FIELD_NUMBER = 3;
  /**
   * <code>optional .connector.GameStarting starting = 3;</code>
   */
  public GameStarting getStarting() {
    if (stateCase_ == 3) {
       return (GameStarting) state_;
    }
    return GameStarting.getDefaultInstance();
  }
  /**
   * <code>optional .connector.GameStarting starting = 3;</code>
   */
  private void setStarting(GameStarting value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 3;
  }
  /**
   * <code>optional .connector.GameStarting starting = 3;</code>
   */
  private void setStarting(
      GameStarting.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 3;
  }
  /**
   * <code>optional .connector.GameStarting starting = 3;</code>
   */
  private void mergeStarting(GameStarting value) {
    if (stateCase_ == 3 &&
        state_ != GameStarting.getDefaultInstance()) {
      state_ = GameStarting.newBuilder((GameStarting) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 3;
  }
  /**
   * <code>optional .connector.GameStarting starting = 3;</code>
   */
  private void clearStarting() {
    if (stateCase_ == 3) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stateCase_ == 1) {
      output.writeMessage(1, (QueueGoing) state_);
    }
    if (stateCase_ == 2) {
      output.writeMessage(2, (QueueDone) state_);
    }
    if (stateCase_ == 3) {
      output.writeMessage(3, (GameStarting) state_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (stateCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (QueueGoing) state_);
    }
    if (stateCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (QueueDone) state_);
    }
    if (stateCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (GameStarting) state_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static QueueResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static QueueResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static QueueResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static QueueResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static QueueResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static QueueResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static QueueResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static QueueResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static QueueResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static QueueResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QueueResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code connector.QueueResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        QueueResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:connector.QueueResponse)
      QueueResponseOrBuilder {
    // Construct using com.sandboxol.mgs.connector.QueueResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public StateCase
        getStateCase() {
      return instance.getStateCase();
    }

    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }


    /**
     * <code>optional .connector.QueueGoing going = 1;</code>
     */
    public QueueGoing getGoing() {
      return instance.getGoing();
    }
    /**
     * <code>optional .connector.QueueGoing going = 1;</code>
     */
    public Builder setGoing(QueueGoing value) {
      copyOnWrite();
      instance.setGoing(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueGoing going = 1;</code>
     */
    public Builder setGoing(
        QueueGoing.Builder builderForValue) {
      copyOnWrite();
      instance.setGoing(builderForValue);
      return this;
    }
    /**
     * <code>optional .connector.QueueGoing going = 1;</code>
     */
    public Builder mergeGoing(QueueGoing value) {
      copyOnWrite();
      instance.mergeGoing(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueGoing going = 1;</code>
     */
    public Builder clearGoing() {
      copyOnWrite();
      instance.clearGoing();
      return this;
    }

    /**
     * <code>optional .connector.QueueDone done = 2;</code>
     */
    public QueueDone getDone() {
      return instance.getDone();
    }
    /**
     * <code>optional .connector.QueueDone done = 2;</code>
     */
    public Builder setDone(QueueDone value) {
      copyOnWrite();
      instance.setDone(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueDone done = 2;</code>
     */
    public Builder setDone(
        QueueDone.Builder builderForValue) {
      copyOnWrite();
      instance.setDone(builderForValue);
      return this;
    }
    /**
     * <code>optional .connector.QueueDone done = 2;</code>
     */
    public Builder mergeDone(QueueDone value) {
      copyOnWrite();
      instance.mergeDone(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueDone done = 2;</code>
     */
    public Builder clearDone() {
      copyOnWrite();
      instance.clearDone();
      return this;
    }

    /**
     * <code>optional .connector.GameStarting starting = 3;</code>
     */
    public GameStarting getStarting() {
      return instance.getStarting();
    }
    /**
     * <code>optional .connector.GameStarting starting = 3;</code>
     */
    public Builder setStarting(GameStarting value) {
      copyOnWrite();
      instance.setStarting(value);
      return this;
    }
    /**
     * <code>optional .connector.GameStarting starting = 3;</code>
     */
    public Builder setStarting(
        GameStarting.Builder builderForValue) {
      copyOnWrite();
      instance.setStarting(builderForValue);
      return this;
    }
    /**
     * <code>optional .connector.GameStarting starting = 3;</code>
     */
    public Builder mergeStarting(GameStarting value) {
      copyOnWrite();
      instance.mergeStarting(value);
      return this;
    }
    /**
     * <code>optional .connector.GameStarting starting = 3;</code>
     */
    public Builder clearStarting() {
      copyOnWrite();
      instance.clearStarting();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:connector.QueueResponse)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new QueueResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        QueueResponse other = (QueueResponse) arg1;
        switch (other.getStateCase()) {
          case GOING: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 1,
                state_,
                other.state_);
            break;
          }
          case DONE: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 2,
                state_,
                other.state_);
            break;
          }
          case STARTING: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 3,
                state_,
                other.state_);
            break;
          }
          case STATE_NOT_SET: {
            visitor.visitOneofNotSet(stateCase_ != 0);
            break;
          }
        }
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          if (other.stateCase_ != 0) {
            stateCase_ = other.stateCase_;
          }
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                QueueGoing.Builder subBuilder = null;
                if (stateCase_ == 1) {
                  subBuilder = ((QueueGoing) state_).toBuilder();
                }
                state_ =
                     input.readMessage(QueueGoing.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((QueueGoing) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 1;
                break;
              }
              case 18: {
                QueueDone.Builder subBuilder = null;
                if (stateCase_ == 2) {
                  subBuilder = ((QueueDone) state_).toBuilder();
                }
                state_ =
                     input.readMessage(QueueDone.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((QueueDone) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 2;
                break;
              }
              case 26: {
                GameStarting.Builder subBuilder = null;
                if (stateCase_ == 3) {
                  subBuilder = ((GameStarting) state_).toBuilder();
                }
                state_ =
                     input.readMessage(GameStarting.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((GameStarting) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 3;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (QueueResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:connector.QueueResponse)
  private static final QueueResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QueueResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static QueueResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<QueueResponse> PARSER;

  public static com.google.protobuf.Parser<QueueResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

