// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

/**
 * Protobuf type {@code connector.QueueFailed}
 */
public  final class QueueFailed extends
    com.google.protobuf.GeneratedMessageLite<
        QueueFailed, QueueFailed.Builder> implements
    // @@protoc_insertion_point(message_implements:connector.QueueFailed)
    QueueFailedOrBuilder {
  private QueueFailed() {
  }
  /**
   * Protobuf enum {@code connector.QueueFailed.Reason}
   */
  public enum Reason
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>InvalidRequest = 0;</code>
     */
    InvalidRequest(0),
    /**
     * <code>ClientAbort = 1;</code>
     */
    ClientAbort(1),
    /**
     * <code>ServerRunout = 2;</code>
     */
    ServerRunout(2),
    /**
     * <code>ServerInternal = 3;</code>
     */
    ServerInternal(3),
    /**
     * <code>UserKicked = 4;</code>
     */
    UserKicked(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>InvalidRequest = 0;</code>
     */
    public static final int InvalidRequest_VALUE = 0;
    /**
     * <code>ClientAbort = 1;</code>
     */
    public static final int ClientAbort_VALUE = 1;
    /**
     * <code>ServerRunout = 2;</code>
     */
    public static final int ServerRunout_VALUE = 2;
    /**
     * <code>ServerInternal = 3;</code>
     */
    public static final int ServerInternal_VALUE = 3;
    /**
     * <code>UserKicked = 4;</code>
     */
    public static final int UserKicked_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Reason valueOf(int value) {
      return forNumber(value);
    }

    public static Reason forNumber(int value) {
      switch (value) {
        case 0: return InvalidRequest;
        case 1: return ClientAbort;
        case 2: return ServerRunout;
        case 3: return ServerInternal;
        case 4: return UserKicked;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Reason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Reason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Reason>() {
            public Reason findValueByNumber(int number) {
              return Reason.forNumber(number);
            }
          };

    private final int value;

    private Reason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:connector.QueueFailed.Reason)
  }

  public static final int REASON_FIELD_NUMBER = 1;
  private int reason_;
  /**
   * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
   */
  public int getReasonValue() {
    return reason_;
  }
  /**
   * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
   */
  public Reason getReason() {
    Reason result = Reason.forNumber(reason_);
    return result == null ? Reason.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
   */
  private void setReasonValue(int value) {
      reason_ = value;
  }
  /**
   * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
   */
  private void setReason(Reason value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    reason_ = value.getNumber();
  }
  /**
   * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
   */
  private void clearReason() {
    
    reason_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reason_ != Reason.InvalidRequest.getNumber()) {
      output.writeEnum(1, reason_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (reason_ != Reason.InvalidRequest.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, reason_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static QueueFailed parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static QueueFailed parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static QueueFailed parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static QueueFailed parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static QueueFailed parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static QueueFailed parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static QueueFailed parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static QueueFailed parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static QueueFailed parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static QueueFailed parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(QueueFailed prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code connector.QueueFailed}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        QueueFailed, Builder> implements
      // @@protoc_insertion_point(builder_implements:connector.QueueFailed)
      com.sandboxol.mgs.connector.QueueFailedOrBuilder {
    // Construct using com.sandboxol.mgs.connector.QueueFailed.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
     */
    public int getReasonValue() {
      return instance.getReasonValue();
    }
    /**
     * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
     */
    public Builder setReasonValue(int value) {
      copyOnWrite();
      instance.setReasonValue(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
     */
    public Reason getReason() {
      return instance.getReason();
    }
    /**
     * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
     */
    public Builder setReason(Reason value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>optional .connector.QueueFailed.Reason reason = 1;</code>
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:connector.QueueFailed)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new QueueFailed();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        QueueFailed other = (QueueFailed) arg1;
        reason_ = visitor.visitInt(reason_ != 0, reason_,    other.reason_ != 0, other.reason_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                reason_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (QueueFailed.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:connector.QueueFailed)
  private static final QueueFailed DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new QueueFailed();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static QueueFailed getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<QueueFailed> PARSER;

  public static com.google.protobuf.Parser<QueueFailed> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

