// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface QueueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.QueueResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .connector.QueueGoing going = 1;</code>
   */
  QueueGoing getGoing();

  /**
   * <code>optional .connector.QueueDone done = 2;</code>
   */
  QueueDone getDone();

  /**
   * <code>optional .connector.GameStarting starting = 3;</code>
   */
  GameStarting getStarting();

  public QueueResponse.StateCase getStateCase();
}
