// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface QueueStopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.QueueStop)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .connector.QueueStop.Reason reason = 1;</code>
   */
  int getReasonValue();
  /**
   * <code>optional .connector.QueueStop.Reason reason = 1;</code>
   */
  QueueStop.Reason getReason();
}
