// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface QueueStartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.QueueStart)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * user priority
   * </pre>
   *
   * <code>optional int64 priority = 1;</code>
   */
  long getPriority();

  /**
   * <pre>
   * user attributes, signed JWS messages.
   * </pre>
   *
   * <code>optional string attributes = 2;</code>
   */
  String getAttributes();
  /**
   * <pre>
   * user attributes, signed JWS messages.
   * </pre>
   *
   * <code>optional string attributes = 2;</code>
   */
  com.google.protobuf.ByteString
      getAttributesBytes();

  /**
   * <pre>
   * game type
   * </pre>
   *
   * <code>optional string gametype = 3;</code>
   */
  String getGametype();
  /**
   * <pre>
   * game type
   * </pre>
   *
   * <code>optional string gametype = 3;</code>
   */
  com.google.protobuf.ByteString
      getGametypeBytes();

  /**
   * <pre>
   * map id
   * </pre>
   *
   * <code>optional string mapid = 4;</code>
   */
  String getMapid();
  /**
   * <pre>
   * map id
   * </pre>
   *
   * <code>optional string mapid = 4;</code>
   */
  com.google.protobuf.ByteString
      getMapidBytes();

  /**
   * <pre>
   * camp id
   * </pre>
   *
   * <code>optional string campid = 5;</code>
   */
  String getCampid();
  /**
   * <pre>
   * camp id
   * </pre>
   *
   * <code>optional string campid = 5;</code>
   */
  com.google.protobuf.ByteString
      getCampidBytes();

  /**
   * <pre>
   * game ex options, json format.
   * </pre>
   *
   * <code>optional string gamexopt = 6;</code>
   */
  String getGamexopt();
  /**
   * <pre>
   * game ex options, json format.
   * </pre>
   *
   * <code>optional string gamexopt = 6;</code>
   */
  com.google.protobuf.ByteString
      getGamexoptBytes();
}
