// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface TeamQueueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.TeamQueueRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .connector.TeamQueueStart start = 1;</code>
   */
  TeamQueueStart getStart();

  /**
   * <code>optional .connector.TeamQueueStop stop = 2;</code>
   */
  TeamQueueStop getStop();

  public TeamQueueRequest.OperateCase getOperateCase();
}
