// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface TeamQueueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.TeamQueueResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .connector.TeamQueueGoing going = 1;</code>
   */
  TeamQueueGoing getGoing();

  /**
   * <code>optional .connector.TeamQueueDone done = 2;</code>
   */
  TeamQueueDone getDone();

  /**
   * <code>optional .connector.TeamGameStarting starting = 3;</code>
   */
  TeamGameStarting getStarting();

  public TeamQueueResponse.StateCase getStateCase();
}
