// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

/**
 * Protobuf type {@code connector.TeamQueueResponse}
 */
public  final class TeamQueueResponse extends
    com.google.protobuf.GeneratedMessageLite<
        TeamQueueResponse, TeamQueueResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:connector.TeamQueueResponse)
    TeamQueueResponseOrBuilder {
  private TeamQueueResponse() {
  }
  private int stateCase_ = 0;
  private Object state_;
  public enum StateCase
      implements com.google.protobuf.Internal.EnumLite {
    GOING(1),
    DONE(2),
    STARTING(3),
    STATE_NOT_SET(0);
    private final int value;
    private StateCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StateCase valueOf(int value) {
      return forNumber(value);
    }

    public static StateCase forNumber(int value) {
      switch (value) {
        case 1: return GOING;
        case 2: return DONE;
        case 3: return STARTING;
        case 0: return STATE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public StateCase
  getStateCase() {
    return StateCase.forNumber(
        stateCase_);
  }

  private void clearState() {
    stateCase_ = 0;
    state_ = null;
  }

  public static final int GOING_FIELD_NUMBER = 1;
  /**
   * <code>optional .connector.TeamQueueGoing going = 1;</code>
   */
  public TeamQueueGoing getGoing() {
    if (stateCase_ == 1) {
       return (TeamQueueGoing) state_;
    }
    return TeamQueueGoing.getDefaultInstance();
  }
  /**
   * <code>optional .connector.TeamQueueGoing going = 1;</code>
   */
  private void setGoing(TeamQueueGoing value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 1;
  }
  /**
   * <code>optional .connector.TeamQueueGoing going = 1;</code>
   */
  private void setGoing(
      TeamQueueGoing.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 1;
  }
  /**
   * <code>optional .connector.TeamQueueGoing going = 1;</code>
   */
  private void mergeGoing(TeamQueueGoing value) {
    if (stateCase_ == 1 &&
        state_ != TeamQueueGoing.getDefaultInstance()) {
      state_ = TeamQueueGoing.newBuilder((TeamQueueGoing) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 1;
  }
  /**
   * <code>optional .connector.TeamQueueGoing going = 1;</code>
   */
  private void clearGoing() {
    if (stateCase_ == 1) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int DONE_FIELD_NUMBER = 2;
  /**
   * <code>optional .connector.TeamQueueDone done = 2;</code>
   */
  public TeamQueueDone getDone() {
    if (stateCase_ == 2) {
       return (TeamQueueDone) state_;
    }
    return TeamQueueDone.getDefaultInstance();
  }
  /**
   * <code>optional .connector.TeamQueueDone done = 2;</code>
   */
  private void setDone(TeamQueueDone value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 2;
  }
  /**
   * <code>optional .connector.TeamQueueDone done = 2;</code>
   */
  private void setDone(
      TeamQueueDone.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 2;
  }
  /**
   * <code>optional .connector.TeamQueueDone done = 2;</code>
   */
  private void mergeDone(TeamQueueDone value) {
    if (stateCase_ == 2 &&
        state_ != TeamQueueDone.getDefaultInstance()) {
      state_ = TeamQueueDone.newBuilder((TeamQueueDone) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 2;
  }
  /**
   * <code>optional .connector.TeamQueueDone done = 2;</code>
   */
  private void clearDone() {
    if (stateCase_ == 2) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public static final int STARTING_FIELD_NUMBER = 3;
  /**
   * <code>optional .connector.TeamGameStarting starting = 3;</code>
   */
  public TeamGameStarting getStarting() {
    if (stateCase_ == 3) {
       return (TeamGameStarting) state_;
    }
    return TeamGameStarting.getDefaultInstance();
  }
  /**
   * <code>optional .connector.TeamGameStarting starting = 3;</code>
   */
  private void setStarting(TeamGameStarting value) {
    if (value == null) {
      throw new NullPointerException();
    }
    state_ = value;
    stateCase_ = 3;
  }
  /**
   * <code>optional .connector.TeamGameStarting starting = 3;</code>
   */
  private void setStarting(
      TeamGameStarting.Builder builderForValue) {
    state_ = builderForValue.build();
    stateCase_ = 3;
  }
  /**
   * <code>optional .connector.TeamGameStarting starting = 3;</code>
   */
  private void mergeStarting(TeamGameStarting value) {
    if (stateCase_ == 3 &&
        state_ != TeamGameStarting.getDefaultInstance()) {
      state_ = TeamGameStarting.newBuilder((TeamGameStarting) state_)
          .mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    stateCase_ = 3;
  }
  /**
   * <code>optional .connector.TeamGameStarting starting = 3;</code>
   */
  private void clearStarting() {
    if (stateCase_ == 3) {
      stateCase_ = 0;
      state_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stateCase_ == 1) {
      output.writeMessage(1, (TeamQueueGoing) state_);
    }
    if (stateCase_ == 2) {
      output.writeMessage(2, (TeamQueueDone) state_);
    }
    if (stateCase_ == 3) {
      output.writeMessage(3, (TeamGameStarting) state_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (stateCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (TeamQueueGoing) state_);
    }
    if (stateCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (TeamQueueDone) state_);
    }
    if (stateCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (TeamGameStarting) state_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static TeamQueueResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamQueueResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamQueueResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamQueueResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamQueueResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamQueueResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamQueueResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static TeamQueueResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamQueueResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamQueueResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeamQueueResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code connector.TeamQueueResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        TeamQueueResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:connector.TeamQueueResponse)
      TeamQueueResponseOrBuilder {
    // Construct using com.sandboxol.mgs.connector.TeamQueueResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public StateCase
        getStateCase() {
      return instance.getStateCase();
    }

    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }


    /**
     * <code>optional .connector.TeamQueueGoing going = 1;</code>
     */
    public TeamQueueGoing getGoing() {
      return instance.getGoing();
    }
    /**
     * <code>optional .connector.TeamQueueGoing going = 1;</code>
     */
    public Builder setGoing(TeamQueueGoing value) {
      copyOnWrite();
      instance.setGoing(value);
      return this;
    }
    /**
     * <code>optional .connector.TeamQueueGoing going = 1;</code>
     */
    public Builder setGoing(
        TeamQueueGoing.Builder builderForValue) {
      copyOnWrite();
      instance.setGoing(builderForValue);
      return this;
    }
    /**
     * <code>optional .connector.TeamQueueGoing going = 1;</code>
     */
    public Builder mergeGoing(TeamQueueGoing value) {
      copyOnWrite();
      instance.mergeGoing(value);
      return this;
    }
    /**
     * <code>optional .connector.TeamQueueGoing going = 1;</code>
     */
    public Builder clearGoing() {
      copyOnWrite();
      instance.clearGoing();
      return this;
    }

    /**
     * <code>optional .connector.TeamQueueDone done = 2;</code>
     */
    public TeamQueueDone getDone() {
      return instance.getDone();
    }
    /**
     * <code>optional .connector.TeamQueueDone done = 2;</code>
     */
    public Builder setDone(TeamQueueDone value) {
      copyOnWrite();
      instance.setDone(value);
      return this;
    }
    /**
     * <code>optional .connector.TeamQueueDone done = 2;</code>
     */
    public Builder setDone(
        TeamQueueDone.Builder builderForValue) {
      copyOnWrite();
      instance.setDone(builderForValue);
      return this;
    }
    /**
     * <code>optional .connector.TeamQueueDone done = 2;</code>
     */
    public Builder mergeDone(TeamQueueDone value) {
      copyOnWrite();
      instance.mergeDone(value);
      return this;
    }
    /**
     * <code>optional .connector.TeamQueueDone done = 2;</code>
     */
    public Builder clearDone() {
      copyOnWrite();
      instance.clearDone();
      return this;
    }

    /**
     * <code>optional .connector.TeamGameStarting starting = 3;</code>
     */
    public TeamGameStarting getStarting() {
      return instance.getStarting();
    }
    /**
     * <code>optional .connector.TeamGameStarting starting = 3;</code>
     */
    public Builder setStarting(TeamGameStarting value) {
      copyOnWrite();
      instance.setStarting(value);
      return this;
    }
    /**
     * <code>optional .connector.TeamGameStarting starting = 3;</code>
     */
    public Builder setStarting(
        TeamGameStarting.Builder builderForValue) {
      copyOnWrite();
      instance.setStarting(builderForValue);
      return this;
    }
    /**
     * <code>optional .connector.TeamGameStarting starting = 3;</code>
     */
    public Builder mergeStarting(TeamGameStarting value) {
      copyOnWrite();
      instance.mergeStarting(value);
      return this;
    }
    /**
     * <code>optional .connector.TeamGameStarting starting = 3;</code>
     */
    public Builder clearStarting() {
      copyOnWrite();
      instance.clearStarting();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:connector.TeamQueueResponse)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new TeamQueueResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        TeamQueueResponse other = (TeamQueueResponse) arg1;
        switch (other.getStateCase()) {
          case GOING: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 1,
                state_,
                other.state_);
            break;
          }
          case DONE: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 2,
                state_,
                other.state_);
            break;
          }
          case STARTING: {
            state_ = visitor.visitOneofMessage(
                stateCase_ == 3,
                state_,
                other.state_);
            break;
          }
          case STATE_NOT_SET: {
            visitor.visitOneofNotSet(stateCase_ != 0);
            break;
          }
        }
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          if (other.stateCase_ != 0) {
            stateCase_ = other.stateCase_;
          }
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                TeamQueueGoing.Builder subBuilder = null;
                if (stateCase_ == 1) {
                  subBuilder = ((TeamQueueGoing) state_).toBuilder();
                }
                state_ =
                     input.readMessage(TeamQueueGoing.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((TeamQueueGoing) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 1;
                break;
              }
              case 18: {
                TeamQueueDone.Builder subBuilder = null;
                if (stateCase_ == 2) {
                  subBuilder = ((TeamQueueDone) state_).toBuilder();
                }
                state_ =
                     input.readMessage(TeamQueueDone.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((TeamQueueDone) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 2;
                break;
              }
              case 26: {
                TeamGameStarting.Builder subBuilder = null;
                if (stateCase_ == 3) {
                  subBuilder = ((TeamGameStarting) state_).toBuilder();
                }
                state_ =
                     input.readMessage(TeamGameStarting.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom((TeamGameStarting) state_);
                  state_ = subBuilder.buildPartial();
                }
                stateCase_ = 3;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (TeamQueueResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:connector.TeamQueueResponse)
  private static final TeamQueueResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeamQueueResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static TeamQueueResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TeamQueueResponse> PARSER;

  public static com.google.protobuf.Parser<TeamQueueResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

