// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

public interface TeamQueueStopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connector.TeamQueueStop)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .connector.TeamQueueStop.Reason reason = 1;</code>
   */
  int getReasonValue();
  /**
   * <code>optional .connector.TeamQueueStop.Reason reason = 1;</code>
   */
  TeamQueueStop.Reason getReason();
}
