// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connector.proto

package com.sandboxol.mgs.connector;

/**
 * Protobuf type {@code connector.TeamQueueStart}
 */
public  final class TeamQueueStart extends
    com.google.protobuf.GeneratedMessageLite<
        TeamQueueStart, TeamQueueStart.Builder> implements
    // @@protoc_insertion_point(message_implements:connector.TeamQueueStart)
    TeamQueueStartOrBuilder {
  private TeamQueueStart() {
    attributes_ = "";
    gametype_ = "";
    mapid_ = "";
    campid_ = "";
    gamexopt_ = "";
  }
  public static final int PRIORITY_FIELD_NUMBER = 1;
  private long priority_;
  /**
   * <pre>
   * user priority
   * </pre>
   *
   * <code>optional int64 priority = 1;</code>
   */
  public long getPriority() {
    return priority_;
  }
  /**
   * <pre>
   * user priority
   * </pre>
   *
   * <code>optional int64 priority = 1;</code>
   */
  private void setPriority(long value) {
    
    priority_ = value;
  }
  /**
   * <pre>
   * user priority
   * </pre>
   *
   * <code>optional int64 priority = 1;</code>
   */
  private void clearPriority() {
    
    priority_ = 0L;
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 2;
  private String attributes_;
  /**
   * <pre>
   * user attributes, signed JWS messages.
   * </pre>
   *
   * <code>optional string attributes = 2;</code>
   */
  public String getAttributes() {
    return attributes_;
  }
  /**
   * <pre>
   * user attributes, signed JWS messages.
   * </pre>
   *
   * <code>optional string attributes = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAttributesBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(attributes_);
  }
  /**
   * <pre>
   * user attributes, signed JWS messages.
   * </pre>
   *
   * <code>optional string attributes = 2;</code>
   */
  private void setAttributes(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    attributes_ = value;
  }
  /**
   * <pre>
   * user attributes, signed JWS messages.
   * </pre>
   *
   * <code>optional string attributes = 2;</code>
   */
  private void clearAttributes() {
    
    attributes_ = getDefaultInstance().getAttributes();
  }
  /**
   * <pre>
   * user attributes, signed JWS messages.
   * </pre>
   *
   * <code>optional string attributes = 2;</code>
   */
  private void setAttributesBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    attributes_ = value.toStringUtf8();
  }

  public static final int GAMETYPE_FIELD_NUMBER = 3;
  private String gametype_;
  /**
   * <pre>
   * game type
   * </pre>
   *
   * <code>optional string gametype = 3;</code>
   */
  public String getGametype() {
    return gametype_;
  }
  /**
   * <pre>
   * game type
   * </pre>
   *
   * <code>optional string gametype = 3;</code>
   */
  public com.google.protobuf.ByteString
      getGametypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gametype_);
  }
  /**
   * <pre>
   * game type
   * </pre>
   *
   * <code>optional string gametype = 3;</code>
   */
  private void setGametype(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    gametype_ = value;
  }
  /**
   * <pre>
   * game type
   * </pre>
   *
   * <code>optional string gametype = 3;</code>
   */
  private void clearGametype() {
    
    gametype_ = getDefaultInstance().getGametype();
  }
  /**
   * <pre>
   * game type
   * </pre>
   *
   * <code>optional string gametype = 3;</code>
   */
  private void setGametypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    gametype_ = value.toStringUtf8();
  }

  public static final int MAPID_FIELD_NUMBER = 4;
  private String mapid_;
  /**
   * <pre>
   * map id
   * </pre>
   *
   * <code>optional string mapid = 4;</code>
   */
  public String getMapid() {
    return mapid_;
  }
  /**
   * <pre>
   * map id
   * </pre>
   *
   * <code>optional string mapid = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMapidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mapid_);
  }
  /**
   * <pre>
   * map id
   * </pre>
   *
   * <code>optional string mapid = 4;</code>
   */
  private void setMapid(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mapid_ = value;
  }
  /**
   * <pre>
   * map id
   * </pre>
   *
   * <code>optional string mapid = 4;</code>
   */
  private void clearMapid() {
    
    mapid_ = getDefaultInstance().getMapid();
  }
  /**
   * <pre>
   * map id
   * </pre>
   *
   * <code>optional string mapid = 4;</code>
   */
  private void setMapidBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mapid_ = value.toStringUtf8();
  }

  public static final int CAMPID_FIELD_NUMBER = 5;
  private String campid_;
  /**
   * <pre>
   * camp id
   * </pre>
   *
   * <code>optional string campid = 5;</code>
   */
  public String getCampid() {
    return campid_;
  }
  /**
   * <pre>
   * camp id
   * </pre>
   *
   * <code>optional string campid = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCampidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(campid_);
  }
  /**
   * <pre>
   * camp id
   * </pre>
   *
   * <code>optional string campid = 5;</code>
   */
  private void setCampid(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    campid_ = value;
  }
  /**
   * <pre>
   * camp id
   * </pre>
   *
   * <code>optional string campid = 5;</code>
   */
  private void clearCampid() {
    
    campid_ = getDefaultInstance().getCampid();
  }
  /**
   * <pre>
   * camp id
   * </pre>
   *
   * <code>optional string campid = 5;</code>
   */
  private void setCampidBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    campid_ = value.toStringUtf8();
  }

  public static final int CAPTAINID_FIELD_NUMBER = 6;
  private long captainid_;
  /**
   * <pre>
   * captain id
   * </pre>
   *
   * <code>optional uint64 captainid = 6;</code>
   */
  public long getCaptainid() {
    return captainid_;
  }
  /**
   * <pre>
   * captain id
   * </pre>
   *
   * <code>optional uint64 captainid = 6;</code>
   */
  private void setCaptainid(long value) {
    
    captainid_ = value;
  }
  /**
   * <pre>
   * captain id
   * </pre>
   *
   * <code>optional uint64 captainid = 6;</code>
   */
  private void clearCaptainid() {
    
    captainid_ = 0L;
  }

  public static final int GAMEXOPT_FIELD_NUMBER = 7;
  private String gamexopt_;
  /**
   * <pre>
   * game ex options, json format.
   * </pre>
   *
   * <code>optional string gamexopt = 7;</code>
   */
  public String getGamexopt() {
    return gamexopt_;
  }
  /**
   * <pre>
   * game ex options, json format.
   * </pre>
   *
   * <code>optional string gamexopt = 7;</code>
   */
  public com.google.protobuf.ByteString
      getGamexoptBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gamexopt_);
  }
  /**
   * <pre>
   * game ex options, json format.
   * </pre>
   *
   * <code>optional string gamexopt = 7;</code>
   */
  private void setGamexopt(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    gamexopt_ = value;
  }
  /**
   * <pre>
   * game ex options, json format.
   * </pre>
   *
   * <code>optional string gamexopt = 7;</code>
   */
  private void clearGamexopt() {
    
    gamexopt_ = getDefaultInstance().getGamexopt();
  }
  /**
   * <pre>
   * game ex options, json format.
   * </pre>
   *
   * <code>optional string gamexopt = 7;</code>
   */
  private void setGamexoptBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    gamexopt_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (priority_ != 0L) {
      output.writeInt64(1, priority_);
    }
    if (!attributes_.isEmpty()) {
      output.writeString(2, getAttributes());
    }
    if (!gametype_.isEmpty()) {
      output.writeString(3, getGametype());
    }
    if (!mapid_.isEmpty()) {
      output.writeString(4, getMapid());
    }
    if (!campid_.isEmpty()) {
      output.writeString(5, getCampid());
    }
    if (captainid_ != 0L) {
      output.writeUInt64(6, captainid_);
    }
    if (!gamexopt_.isEmpty()) {
      output.writeString(7, getGamexopt());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (priority_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, priority_);
    }
    if (!attributes_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getAttributes());
    }
    if (!gametype_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getGametype());
    }
    if (!mapid_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getMapid());
    }
    if (!campid_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getCampid());
    }
    if (captainid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, captainid_);
    }
    if (!gamexopt_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(7, getGamexopt());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static TeamQueueStart parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamQueueStart parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamQueueStart parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static TeamQueueStart parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static TeamQueueStart parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamQueueStart parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamQueueStart parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static TeamQueueStart parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static TeamQueueStart parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static TeamQueueStart parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TeamQueueStart prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code connector.TeamQueueStart}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        TeamQueueStart, Builder> implements
      // @@protoc_insertion_point(builder_implements:connector.TeamQueueStart)
      TeamQueueStartOrBuilder {
    // Construct using com.sandboxol.mgs.connector.TeamQueueStart.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * user priority
     * </pre>
     *
     * <code>optional int64 priority = 1;</code>
     */
    public long getPriority() {
      return instance.getPriority();
    }
    /**
     * <pre>
     * user priority
     * </pre>
     *
     * <code>optional int64 priority = 1;</code>
     */
    public Builder setPriority(long value) {
      copyOnWrite();
      instance.setPriority(value);
      return this;
    }
    /**
     * <pre>
     * user priority
     * </pre>
     *
     * <code>optional int64 priority = 1;</code>
     */
    public Builder clearPriority() {
      copyOnWrite();
      instance.clearPriority();
      return this;
    }

    /**
     * <pre>
     * user attributes, signed JWS messages.
     * </pre>
     *
     * <code>optional string attributes = 2;</code>
     */
    public String getAttributes() {
      return instance.getAttributes();
    }
    /**
     * <pre>
     * user attributes, signed JWS messages.
     * </pre>
     *
     * <code>optional string attributes = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAttributesBytes() {
      return instance.getAttributesBytes();
    }
    /**
     * <pre>
     * user attributes, signed JWS messages.
     * </pre>
     *
     * <code>optional string attributes = 2;</code>
     */
    public Builder setAttributes(
        String value) {
      copyOnWrite();
      instance.setAttributes(value);
      return this;
    }
    /**
     * <pre>
     * user attributes, signed JWS messages.
     * </pre>
     *
     * <code>optional string attributes = 2;</code>
     */
    public Builder clearAttributes() {
      copyOnWrite();
      instance.clearAttributes();
      return this;
    }
    /**
     * <pre>
     * user attributes, signed JWS messages.
     * </pre>
     *
     * <code>optional string attributes = 2;</code>
     */
    public Builder setAttributesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAttributesBytes(value);
      return this;
    }

    /**
     * <pre>
     * game type
     * </pre>
     *
     * <code>optional string gametype = 3;</code>
     */
    public String getGametype() {
      return instance.getGametype();
    }
    /**
     * <pre>
     * game type
     * </pre>
     *
     * <code>optional string gametype = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGametypeBytes() {
      return instance.getGametypeBytes();
    }
    /**
     * <pre>
     * game type
     * </pre>
     *
     * <code>optional string gametype = 3;</code>
     */
    public Builder setGametype(
        String value) {
      copyOnWrite();
      instance.setGametype(value);
      return this;
    }
    /**
     * <pre>
     * game type
     * </pre>
     *
     * <code>optional string gametype = 3;</code>
     */
    public Builder clearGametype() {
      copyOnWrite();
      instance.clearGametype();
      return this;
    }
    /**
     * <pre>
     * game type
     * </pre>
     *
     * <code>optional string gametype = 3;</code>
     */
    public Builder setGametypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGametypeBytes(value);
      return this;
    }

    /**
     * <pre>
     * map id
     * </pre>
     *
     * <code>optional string mapid = 4;</code>
     */
    public String getMapid() {
      return instance.getMapid();
    }
    /**
     * <pre>
     * map id
     * </pre>
     *
     * <code>optional string mapid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMapidBytes() {
      return instance.getMapidBytes();
    }
    /**
     * <pre>
     * map id
     * </pre>
     *
     * <code>optional string mapid = 4;</code>
     */
    public Builder setMapid(
        String value) {
      copyOnWrite();
      instance.setMapid(value);
      return this;
    }
    /**
     * <pre>
     * map id
     * </pre>
     *
     * <code>optional string mapid = 4;</code>
     */
    public Builder clearMapid() {
      copyOnWrite();
      instance.clearMapid();
      return this;
    }
    /**
     * <pre>
     * map id
     * </pre>
     *
     * <code>optional string mapid = 4;</code>
     */
    public Builder setMapidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMapidBytes(value);
      return this;
    }

    /**
     * <pre>
     * camp id
     * </pre>
     *
     * <code>optional string campid = 5;</code>
     */
    public String getCampid() {
      return instance.getCampid();
    }
    /**
     * <pre>
     * camp id
     * </pre>
     *
     * <code>optional string campid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCampidBytes() {
      return instance.getCampidBytes();
    }
    /**
     * <pre>
     * camp id
     * </pre>
     *
     * <code>optional string campid = 5;</code>
     */
    public Builder setCampid(
        String value) {
      copyOnWrite();
      instance.setCampid(value);
      return this;
    }
    /**
     * <pre>
     * camp id
     * </pre>
     *
     * <code>optional string campid = 5;</code>
     */
    public Builder clearCampid() {
      copyOnWrite();
      instance.clearCampid();
      return this;
    }
    /**
     * <pre>
     * camp id
     * </pre>
     *
     * <code>optional string campid = 5;</code>
     */
    public Builder setCampidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCampidBytes(value);
      return this;
    }

    /**
     * <pre>
     * captain id
     * </pre>
     *
     * <code>optional uint64 captainid = 6;</code>
     */
    public long getCaptainid() {
      return instance.getCaptainid();
    }
    /**
     * <pre>
     * captain id
     * </pre>
     *
     * <code>optional uint64 captainid = 6;</code>
     */
    public Builder setCaptainid(long value) {
      copyOnWrite();
      instance.setCaptainid(value);
      return this;
    }
    /**
     * <pre>
     * captain id
     * </pre>
     *
     * <code>optional uint64 captainid = 6;</code>
     */
    public Builder clearCaptainid() {
      copyOnWrite();
      instance.clearCaptainid();
      return this;
    }

    /**
     * <pre>
     * game ex options, json format.
     * </pre>
     *
     * <code>optional string gamexopt = 7;</code>
     */
    public String getGamexopt() {
      return instance.getGamexopt();
    }
    /**
     * <pre>
     * game ex options, json format.
     * </pre>
     *
     * <code>optional string gamexopt = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGamexoptBytes() {
      return instance.getGamexoptBytes();
    }
    /**
     * <pre>
     * game ex options, json format.
     * </pre>
     *
     * <code>optional string gamexopt = 7;</code>
     */
    public Builder setGamexopt(
        String value) {
      copyOnWrite();
      instance.setGamexopt(value);
      return this;
    }
    /**
     * <pre>
     * game ex options, json format.
     * </pre>
     *
     * <code>optional string gamexopt = 7;</code>
     */
    public Builder clearGamexopt() {
      copyOnWrite();
      instance.clearGamexopt();
      return this;
    }
    /**
     * <pre>
     * game ex options, json format.
     * </pre>
     *
     * <code>optional string gamexopt = 7;</code>
     */
    public Builder setGamexoptBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGamexoptBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:connector.TeamQueueStart)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new TeamQueueStart();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        TeamQueueStart other = (TeamQueueStart) arg1;
        priority_ = visitor.visitLong(priority_ != 0L, priority_,
            other.priority_ != 0L, other.priority_);
        attributes_ = visitor.visitString(!attributes_.isEmpty(), attributes_,
            !other.attributes_.isEmpty(), other.attributes_);
        gametype_ = visitor.visitString(!gametype_.isEmpty(), gametype_,
            !other.gametype_.isEmpty(), other.gametype_);
        mapid_ = visitor.visitString(!mapid_.isEmpty(), mapid_,
            !other.mapid_.isEmpty(), other.mapid_);
        campid_ = visitor.visitString(!campid_.isEmpty(), campid_,
            !other.campid_.isEmpty(), other.campid_);
        captainid_ = visitor.visitLong(captainid_ != 0L, captainid_,
            other.captainid_ != 0L, other.captainid_);
        gamexopt_ = visitor.visitString(!gamexopt_.isEmpty(), gamexopt_,
            !other.gamexopt_.isEmpty(), other.gamexopt_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                priority_ = input.readInt64();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                attributes_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                gametype_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                mapid_ = s;
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                campid_ = s;
                break;
              }
              case 48: {

                captainid_ = input.readUInt64();
                break;
              }
              case 58: {
                String s = input.readStringRequireUtf8();

                gamexopt_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (TeamQueueStart.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:connector.TeamQueueStart)
  private static final TeamQueueStart DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TeamQueueStart();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static TeamQueueStart getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TeamQueueStart> PARSER;

  public static com.google.protobuf.Parser<TeamQueueStart> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

