# 海外正式服配置

defaultInstanceType: c5.large
defaultServiceCount: 2
defaultServiceCpu: 0.3
defaultServiceMemory: 0.75

serviceTypes:
  - type: service
    instanceType: m5.large
    cpu: 0.3
    memory: 0.6
    count: 2
  - type: center
    instanceType: c5.large
    cpu: 0.5
    memory: 1.1
    count: 2
  - type: gateway
    instanceType: c5.large
    cpu: 1.5
    memory: 2.0
    count: 2
  - type: eureka
    instanceType: c5.large
    cpu: 1.5
    memory: 2.0
    count: 2

services:
  - name: gamedata-service
    instanceType: c5.large
    cpu: 1.5
    memory: 2
    count: 2
  - name: activity-service
    instanceType: c5.large
    cpu: 0.8
    memory: 1.2
    count: 4
  - name: auth-center
    cpu: 0.8
    memory: 1.2
    count: 4
  - name: charmingtown-service
    cpu: 0.6
    memory: 0.8
    count: 4
  - name: clan-center
    cpu: 0.8
    memory: 1.0
    count: 3
  - name: clan-service
    cpu: 0.6
    memory: 1.0
    count: 3
  - name: decoration-center
    cpu: 0.8
    memory: 1.2
    count: 4
  - name: decoration-service
    cpu: 0.8
    memory: 1.0
    count: 4
  - name: friend-center
    cpu: 0.8
    memory: 1.2
    count: 4
  - name: friend-service
    cpu: 0.7
    memory: 1.2
    count: 6
  - name: game-center
    cpu: 0.8
    memory: 1.2
    count: 4
  - name: game-service
    cpu: 0.5
    memory: 1.0
    count: 5
  - name: gameaide-service
    instanceType: c5.large
    cpu: 0.8
    memory: 1.2
    count: 4
  - name: gateway-service
    count: 5
  - name: mailbox-center
    cpu: 0.8
    memory: 1.0
    count: 2
  - name: mailbox-service
    cpu: 0.3
    memory: 1.0
    count: 3
  - name: msg-center
    cpu: 0.8
    memory: 1.2
    count: 4
  - name: message-process
    cpu: 0.65
    memory: 1.2
    count: 4
  - name: msg-service
    cpu: 0.5
    memory: 0.8
    count: 3
  - name: pay-center
    cpu: 0.8
    memory: 1.0
    count: 3
  - name: pay-service
    cpu: 0.5
    memory: 0.8
    count: 3
  - name: shop-service
    cpu: 0.3
    memory: 0.8
    count: 3
  - name: user-center
    cpu: 0.8
    memory: 1.0
    count: 5
  - name: user-service
    cpu: 0.6
    memory: 1.0
    count: 5
  - name: singleton-service
    cpu: 0.6
    count: 1
  - name: web-service
    cpu: 0.6
    memory: 0.32
    count: 2
  - name: admin-service
    cpu: 0.1
    memory: 0.6
    count: 1
  - name: geoinfo-service
    cpu: 0.3
    memory: 0.6
    count: 2
  - name: gamedata-center
    cpu: 0.8
    memory: 1.2
    count: 3
  - name: editorpay-center
    cpu: 0.52
    memory: 1.2
    count: 1
  - name: editorpay-service
    cpu: 0.5
    memory: 0.8
    count: 1
  - name: statistic-service
    cpu: 0.7
    memory: 1.2
    count: 3
  - name: editorstatistic-service
    cpu: 0.7
    memory: 0.8
    count: 1
  - name: ranking-service
    cpu: 0.7
    memory: 0.8
    count: 3
  - name: video-service
    cpu: 0.7
    memory: 0.8
    count: 3
  - name: datareport-service
    cpu: 1.5
    memory: 1.2
    count: 10
    instanceType: c5.large
  - name: mongo-center
    cpu: 0.8
    memory: 1.2
    count: 2
  - name: slow-service
    instanceType: c5.large
    cpu: 0.8
    memory: 1.0
    count: 3
  - name: search-center
    cpu: 0.8
    memory: 1.2
    count: 2
  - name: gamemongo-center
    cpu: 0.8
    memory: 1.2
    count: 2
  - name: bedwar-service
    instanceType: c5.large
    cpu: 0.8
    memory: 1.2
    count: 3
  - name: gatewaynew-service
    cpu: 1.5
    memory: 2.0
    count: 1
  - name: backpack-center
    cpu: 0.8
    memory: 1.0
    count: 2
  - name: backpack-service
    cpu: 0.6
    memory: 1.0
    count: 3
  - name: gtemporary-service
    instanceType: c5.large
    cpu: 0.6
    memory: 1.6
    count: 2
  - name: stemporary-service
    instanceType: c5.large
    cpu: 0.6
    memory: 1.6
    count: 4
  - name: route-service
    instanceType: c5.large
    cpu: 0.6
    memory: 1.6
    count: 4
  - name: notice-service
    instanceType: c5.large
    cpu: 0.8
    memory: 1.2
    count: 3
  - name: process-service
    instanceType: c5.large
    cpu: 0.8
    memory: 1.2
    count: 2

serviceNames:
  - decoration-center
  - game-center
  - friend-center
  - clan-center
  - user-center
  - auth-center
  - msg-center
  - mailbox-center
  - pay-center
  - gamedata-center
  - editorpay-center
  - mongo-center
  - search-center
  - gamemongo-center

  - decoration-service
  - game-service
  - friend-service
  - message-process
  - clan-service
  - user-service
  - mailbox-service
  - msg-service
  - charmingtown-service
  - pay-service
  - activity-service
  - gamedata-service
  - shop-service
  - singleton-service
  - web-service
  - gameaide-service
  - admin-service
  - geoinfo-service
  - editorpay-service
  - statistic-service
  - gateway-service
  - editorstatistic-service
  - ranking-service
  - video-service
  - datareport-service
  - slow-service
  - bedwar-service
  - gatewaynew-service
  - backpack-center
  - backpack-service
  - gtemporary-service
  - stemporary-service
  - route-service
  - notice-service
  - process-service

# reservedInstance:
#   - serviceType: service
#     instanceType: m5.large
#     count: 10

specialServices:
  - name: gamedata-service
    awsRegion: ap-northeast-2
    vpcId: vpc-3e34f957
    imageId: ami-048d908705f84db9d
    securityGroups: ['sg-38ec7752', 'sg-ee1fb087', 'sg-a9ff51c0', 'sg-a8196dc2']
    instanceProfile: s3-reader-writer-dynamodb

# base.08 image id ami-0adcaef2bd1212e9c 
imageId: ami-02951cdb8a8adedbf
securityGroups: ['sg-b0bd5bc9', 'sg-0a82cdd9c37bbe0f4', 'sg-052360770789e6a2a']
#securityGroups: ['default', 'bmg.webservice', 'prometheus-service-port']
vpcId: vpc-1d079e79
instanceProfile: s3-reader-writer
tags:
  namespace: webservice-02
  lang: java
  business: server
  env: prod
  dept: web

targetGroupEnalbed: true
targetGroups:
  - service: admin-service
    arn: arn:aws:elasticloadbalancing:us-east-1:163639519626:targetgroup/xyx-admin-service/628fe11c99ad1744
    port: 8892
  - service: gateway-service
    arn: arn:aws:elasticloadbalancing:us-east-1:163639519626:targetgroup/gateway-service-instances/60acce13a3790ea1
    port: 8899
  - service: web-service
    arn: arn:aws:elasticloadbalancing:us-east-1:163639519626:targetgroup/xyx-web-service/fb0a9a9600d12afe
    port: 8831
  - service: user-service
    arn: arn:aws:elasticloadbalancing:us-east-1:163639519626:targetgroup/user-service-instances/120c65f72c20ce77
    port: 8810
  - service: datareport-service
    arn: arn:aws:elasticloadbalancing:us-east-1:163639519626:targetgroup/xyx-datatrport-service/6412eb9c1f0cdf8a
    port: 8849
  - service: gatewaynew-service
    arn: arn:aws:elasticloadbalancing:us-east-1:163639519626:targetgroup/gateway-service-instances/60acce13a3790ea1
    port: 8899

# 预留cpu给操作系统使用
reservedCpu:
  # fixed: 固定大小，fixed-service: 按服务数量叠加，每个服务固定大小
  strategy: fixed-service
  value: 0.1

# 预留内存给操作系统使用
reservedMemory:
  # fixed: 固定大小，fixed-service: 按服务数量叠加，每个服务固定大小, 单位GB
  strategy: fixed-service
  value: 0.3

instanceTypeDetails:
  - name: c4.large
    cpu: 2
    memory: 3.75
  - name: m4.large
    cpu: 2
    memory: 8
  - name: t2.small
    cpu: 1
    memory: 2
  - name: c5.large
    cpu: 2
    memory: 3.62
  - name: c5.xlarge
    cpu: 4
    memory: 8
  - name: m5.large
    cpu: 2
    memory: 7.51
  - name: m5.xlarge
    cpu: 4
    memory: 16

profiles:
  us-east-1: oversea
  ap-northeast-2: oversea
  cn-northwest-1: ningxia

staticConfigs:
  bucket: blockmango-res
  groupKey: monitoring/config/webservice-groups.json
  nodeGroupKey: monitoring/config/webservice-nodes-groups.json

collectlogConfigs:
  collectlog_region: us-east-1-internet
  machine_id: sla-prod