# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'BlockyModes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlockyModes

pod 'RxSwift',    '~> 3.0'
pod 'RxCocoa',    '~> 3.0'
pod 'Moya/RxSwift'
pod 'HandyJSON', '~> 1.8.0'
pod 'MJRefresh'
pod 'R.swift', '~> 3.0.0'
pod 'SnapKit', '~> 3.2.0'
pod 'Kingfisher', '~> 3.13.1'
pod 'SDCycleScrollView', '~> 1.73'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'FCUUID'
pod 'FBSDKLoginKit'
#pod 'RealmSwift'

end

target 'BlockyModes_Oversea' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for BlockyModes_Oversea
    
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'Moya/RxSwift'
    pod 'HandyJSON', '~> 1.8.0'
    pod 'MJRefresh'
    pod 'R.swift', '~> 3.0.0'
    pod 'SnapKit', '~> 3.2.0'
    pod 'Kingfisher', '~> 3.13.1'
    pod 'SDCycleScrollView', '~> 1.73'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'FCUUID'
    pod 'FBSDKLoginKit'
#    pod 'RealmSwift'
end
