#不指定limitMemory等，默认为memory的1.2倍
#举例，在servics设置了pay-service的值，pay-service的值就会顶掉全局的service的值
#伸缩(hpa)默认是开启的，autoscaling设置为false不开启，默认为cpu的85%
#memory需要大于-Xmx，建议为-Xmx的120%

serviceTypes:
  - type: service
    cpu: 0.3
    memory: 0.45
    count: 1
#    limitMemory: 0.8
#    limitCpu: 0.8
    autoscaling: true
    autoscalingTargetCPU: 86
    APP_PARAMETER: -Xms307m -Xmx307m -Xss256k
  - type: center
    cpu: 0.3
    memory: 0.45
    count: 1
#    limitMemory: 1.0
#    limitCpu: 0.8
    autoscaling: true
    autoscalingTargetCPU: 85
    APP_PARAMETER: -Xms307m -Xmx307m -Xss257k
  - type: process
    cpu: 0.31
    memory: 0.45
    count: 1
    autoscaling: true
    autoscalingTargetCPU: 85
    APP_PARAMETER: -Xms307m -Xmx307m -Xss256k

services:
  - name: decoration-center
    cpu: 0.6
    memory: 0.7
    count: 1
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: game-service
    memory: 1.1
    count: 1
    APP_PARAMETER: -Xms1000m -Xmx1000m -Xss256k
  - name: game-center
    cpu: 1.0
    memory: 1.1
    count: 2
    APP_PARAMETER: -Xms1000m -Xmx1000m -Xss256k
  - name: search-center
    cpu: 0.6
    memory: 0.7
    count: 1
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: user-center
    cpu: 0.6
    memory: 0.7
    count: 1
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: auth-center
    cpu: 0.6
    memory: 0.7
    count: 1
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: gamedata-center
    cpu: 0.6
    memory: 0.7
    count: 1
    APP_PARAMETER: -Xms1000m -Xmx1000m -Xss256k
  - name: message-process
    cpu: 1
    memory: 1.1
    count: 1
  - name: pay-service
    count: 1
  - name: shop-serivce
    count: 1
  - name: mailbox-center
    count: 1
  - name: mailbox-service
    count: 1
  - name: activity-service
    count: 1
    cpu: 0.6
    memory: 0.7
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: statistic-service
    count: 1
    cpu: 0.6
    memory: 0.7
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: singleton-service
    count: 1
  - name: web-service
    count: 1
  - name: friend-service
    count: 1
  - name: friend-center
    cpu: 0.6
    memory: 0.7
    count: 1
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: clan-service
    count: 1
  - name: clan-center
    cpu: 0.5
    memory: 0.5
    count: 1
    APP_PARAMETER: -Xms387m -Xmx387m -Xss256k
  - name: pay-center
    cpu: 0.5
    memory: 0.5
    count: 1
    APP_PARAMETER: -Xms387m -Xmx387m -Xss256k
  - name: geoinfo-service
    count: 1
  - name: gameaide-service
    cpu: 0.6
    memory: 0.7
    count: 1
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: gateway-service
    cpu: 0.5
    memory: 1
    count: 2
  - type: eureka-service
    cpu: 0.5
    memory: 1
    count: 2
  - name: bedwar-service
    count: 1
    cpu: 0.6
    memory: 0.7
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k
  - name: process-service
    count: 1
    cpu: 0.6
    memory: 0.7
    APP_PARAMETER: -Xms507m -Xmx507m -Xss256k

profiles: oversea-test
#  us-east-1: oversea
#  ap-northeast-2: oversea
#  cn-northwest-1: ningxia
#  us-east-2: ohio