- name: deploy {{ service }}
  hosts: "{{ service }}"
  remote_user: deploy
  serial: 10
  
  tasks:
  - file: path=./apps state=directory mode=755
  - file: path=./logs state=directory mode=755
  - file: path=./logs/supervisor state=directory mode=755
  - name: cp {{ service }} jar
    copy: |
      src={{ work_dir }}/apps/{{ service }}-0.0.1-SNAPSHOT.jar
      dest=/home/deploy/apps/{{ service }}-0.0.1-SNAPSHOT.jar
      backup=yes
      mode=600 
  - name: cp service ini
    template: src={{ work_dir }}/templates/service.ini.j2 dest=/etc/supervisor/conf.d/{{ service }}.ini

  - name: restart
    supervisorctl: |
      name="{{service}}"
      state=restarted
    when: action == "restart"
  - name: start supervisord
    supervisorctl: |
      name="{{service}}"
      state=present
    when: action == 'start'
  - name: stop
    supervisorctl: |
      name="{{service}}"
      state=stopped
    when: action == "stop"
  - name: pause 40 waiting for service ready
    pause: seconds=40
    when: action == "restart"