- name: remove {{service}}
  hosts: "{{ service }}"
  remote_user: deploy
  
  tasks:
  - name: remove program config file
    file: state=absent path="/etc/supervisor/conf.d/{{service}}.ini"
  - name: stopped
    supervisorctl: |
      name="{{service}}"
      state=stopped
  - name: absent
    supervisorctl: |
      name="{{service}}"
      state=absent