- name: deploy {{ service }}
  hosts: "{{ service }}"
  remote_user: deploy
  serial: 1
  vars:
    service_code_dir: "{{ repo_dir }}/server/com/sandbox/{{ service_type }}/{{ service }}"
    build_code_dir: "{{ build_dir }}/{{ service_type }}"
    application_yaml: "{{ build_code_dir }}/{{ service }}/src/main/resources/application.yml"
    jar_path: "{{ build_code_dir }}/build/libs/{{ service }}-0.0.1-SNAPSHOT.jar"
    HOST_COUNT: "{{ ansible_play_hosts | length }}"

  tasks:
  - debug: var=HOST_COUNT
  - name: update code from github
    git: |
      repo='git@github.com:blockmangame/pickaxe.git'
      dest={{ repo_dir }}
      force=yes
      version=deploy-web
    run_once: true
    delegate_to: localhost
    when: not disable_update_code

  - name: copy {{ repo_dir }}/server/com/sandbox/  to  {{ build_dir }}
    command: cp -rf {{ repo_dir }}/server/com/sandbox/. {{ build_dir }}
    run_once: true
    delegate_to: localhost

  - name: set execute permission to gradlew
    copy: |
      src={{ service_code_dir }}/gradlew
      dest={{ build_code_dir }}/{{ service }}/gradlew
      mode=0700
    run_once: true
    delegate_to: localhost

  - name: replace eureka config for {{ application_yaml }}
    template: |
      src={{ application_yaml }}
      dest={{ application_yaml }}
    run_once: true
    delegate_to: localhost

  - name: gradlew build
    command: ./gradlew clean build
    args:
      chdir: "{{ build_code_dir }}/{{ service }}"
    run_once: true
    delegate_to: localhost

  - file: path=./apps state=directory mode=755
  - file: path=./logs state=directory mode=755
  - file: path=./logs/supervisor state=directory mode=755
  - name: cp {{ build_code_dir }}/{{ service }}/build/libs/{{ service }}-0.0.1-SNAPSHOT.jar
    copy: |
      src={{ build_code_dir }}/{{ service }}/build/libs/{{ service }}-0.0.1-SNAPSHOT.jar
      dest=/home/deploy/apps/{{ service }}-0.0.1-SNAPSHOT.jar
      backup=yes
      mode=600 
  - name: cp {{ template_dir }}/service.ini.j2
    template: src={{ template_dir }}/service.ini.j2 dest=/etc/supervisor/conf.d/{{ service }}.ini
  
  - file: path=./jks state=directory mode=755
    when: service == 'singleton-service'
  - name: cp google refund key
    copy: |
      src={{ repo_dir }}/server/com/sandbox/service/singleton-service/src/main/resources/gpa-key.p12
      dest=/home/deploy/jks/gpa-key.p12
      mode=600
    when: service == 'singleton-service'
  - name: cp game reward rule file
    copy: |
      src={{ repo_dir }}/server/com/sandbox/center/game-center/src/main/resources/templates/
      dest=/home/deploy/resources/game
      mode=600
    when: service == 'game-center'
  - name: cp payssion pay config file
    copy: |
      src={{ repo_dir }}/server/com/sandbox/center/pay-center/src/main/resources/
      dest=/home/deploy/resources/pay
      mode=600
    when: service == 'pay-center'
  - name: cp clan task config file
    copy: |
      src={{ repo_dir }}/server/conf/json/
      dest=/home/deploy/resources/clan
      mode=600
    when: service == 'clan-center'
  - name: cp game country config file
    copy: |
      src={{ repo_dir }}/server/com/sandbox/service/game-service/src/main/resources/
      dest=/home/deploy/resources/game
      mode=600
    when: service == 'game-service'
  - name: cp activity config file
    copy: |
      src={{ repo_dir }}/server/com/sandbox/service/activity-service/src/main/resources/json/
      dest=/home/deploy/resources/activity
      mode=600
    when: service == 'activity-service'
  - name: cp user center config file
    copy: |
      src={{ repo_dir }}/server/com/sandbox/center/user-center/src/main/resources/
      dest=/home/deploy/resources/user
      mode=600
    when: service == 'user-center'

  - name: restart
    supervisorctl: |
      name="{{service}}"
      state=restarted
    when: service_action == "restart"
  - name: start supervisord
    supervisorctl: |
      name="{{service}}"
      state=present
    when: service_action == 'start'
  - name: stop
    supervisorctl: |
      name="{{service}}"
      state=stopped
    when: service_action == "stop"
  - name: pause 40 waiting for service ready
    pause: seconds=40
    when: service_action == "restart" and HOST_COUNT != "1"